### ISSUE TITLE
dns diagnosis tool proposal: test

### ISSUE THREAD

**Issue by fgimenez** [kubernetes/dns#102]
Hello everyone, this is a first proposal for implementing the idea suggested in kubernetes/kubernetes#45934, describing the tests to be implemented by the tool. I probably will miss things to check, any ideas are more than welcome! :)  I'm a newbie on the internals of kubernetes' DNS, but very keen to learn, please do not hesitate to correct me if I propose silly things :)

**Tests to be run**

* **Related to endpoints**
  * Number of endpoints
  *  Replicas behind each endpoint
  * Restarts of each replica

* **Related to lookups**
  * In-cluster
    * For each service (without port associated) and endpoint query for A record and measure latency and dropped packages
    * For each service (with port associated) and endpoint query for SRV record and measure latency and dropped packages
    * For each service and endpoint do a reverse IP adress lookup and measure latency and dropped packages

  * Out-of-cluster
    * For each domain name in a predetermined external set and endpoint measure latency and dropped packages

Questions:

* In order to make sure that SRV records are checked, should specific services with named ports be created and removed after the test is done? In general, if any of the items to be checked is not present, should the tool setup the check conditions and teardown them after the checks finish?
* Should pod's A records be checked?

So, what do you thing? Should any of these be done differently, or totally removed? Are there any relevant checks missing? 

Cheers,

**Comment by cmluciano** [comment]
cc @thockin @bowei

**Comment by bowei** [comment]
Some thoughts:

From what I've seen, a lot of the problems are related to DNS working in general but not for a specific service entry, meaning testing latency across different kube-dns managed entries would be less informational. Some other things to possible for the tool to look at:

- QPS that is seen at each of the kube-dns instances; {in,out} of dnsmasq, kube-dns.
- Contents of `kube-system:kube-dns`.
- `/etc/resolv.conf`, `/etc/hosts` for the pod that is having DNS connectivity issues
- Number of UDP conntrack entries present on the node with problems.

**Comment by fgimenez** [comment]
thanks @bowei, sounds great, for the last two tests/queries, how to identify nodes with problems? Maybe the execution should be split into two rounds, one for checking if there are faulty nodes (eg. QPS < threshold) and a second pass to extract more info about them?

**Comment by cmluciano** [comment]
We can take a look at failing DNS pods. Frequently issues are opened stating that pods can't be scheduled or are bouncing between healthy/unhealthy.

**Comment by fgimenez** [comment]
cool @cmluciano thanks! Do you think we need an issue for discussing the process to be performed by the tool itself?

**Comment by cmluciano** [comment]
I think we have a few ideas captured in this issue that can be placed in a PR.

**Comment by fgimenez** [comment]
Indeed :) on it

**Comment by fgimenez** [comment]
Ok, I have already this https://github.com/kubernetes/dns/compare/master...fgimenez:diagnoser?expand=1 with e2e tests passing, it would be great to get some feedback before it gets too hairy, mainly about the general implementation, if that's ok i'll continue with the actual tasks. 

Not sure if I should propose it as is or wait until it does something moderately useful, maybe in that case the PR will be big(ish) WDYT?

It follows the suggestion by @thockin of having a job that exits with error so that it gets rescheduled, currently the job definition is under a `manifests` directory, probably this should go somewhere else.

In order to get info about a real running kubedns in the e2e tests i'll need to set it up, should i deploy the complete addon? If so, how to do that from the repo? haven't found any example in the existing tests, probably the most simlar to this situation is the `sidecar-e2e` test, should i follow that pattern?

Thanks!

cc/ @thockin @cmluciano @bowei

**Comment by bowei** [comment]
@fgimenez -- you can open that as a PR and assign it to me, it will be much easier to comment on in that form

**Comment by fgimenez** [comment]
thanks @bowei, done #129 not able to assign it though
