### ISSUE TITLE
Unable to build Kubernetes DNS

### ISSUE THREAD

**Issue by kcao3** [kubernetes/dns#110]
Hello,
Currently, I receive the following errors while attempting to run the make build target:
 ...
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.84815163.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
v3.6.1-61-gc32140e9a2 [http://dl-cdn.alpinelinux.org/alpine/v3.6/community]
1 errors; 2892 distinct packages available
make[3]: *** [_output/amd64/dnsmasq] Error 1
make[3]: Leaving directory `/tmp/dns/images/dnsmasq'
make[2]: *** [build-dnsmasq] Error 2
make[2]: Leaving directory `/tmp/dns/images'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/tmp/dns/images'
make: *** [images-build] Error 2

Does anyone have any idea how to resolve this problem? Thank you for your help!

**Comment by bowei** [comment]
That looks like you are having problems accessing to the Alpine image distro website (it looks like it's overloaded). I would check that `curl http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz > /dev/null` works.

I'm going to close this issue as it should be a temporary problem with Alpine Linux, not kube-dns. Please reopen if you encounter further problems.
