### ISSUE TITLE
k8s-dns-dnsmasq-nanny-arm:1.14.3 broken for 'arm'

### ISSUE THREAD

**Issue by asac** [kubernetes/dns#111]
/ # uname -a
Linux 26e00a3161d1 4.9.20-std-1 #1 SMP Wed Apr 5 15:38:34 UTC 2017 armv7l GNU/Linux

```
# docker run -it   --entrypoint=/bin/sh gcr.io/google_containers/k8s-dns-dnsmasq-nanny-arm:1.14.3
/ # /dnsmasq-nanny 
F0622 23:21:33.323491       7 nanny.go:173] Could not start dnsmasq with initial configuration: fork/exec /usr/sbin/dnsmasq: no such file or directory
goroutine 1 [running]:
k8s.io/dns/vendor/github.com/golang/glog.stacks(0x131b000, 0x0, 0x97, 0xcb)
	/go/src/k8s.io/dns/vendor/github.com/golang/glog/glog.go:769 +0x84
k8s.io/dns/vendor/github.com/golang/glog.(*loggingT).output(0x130a968, 0x3, 0x11698dc0, 0x12a53d1, 0x8, 0xad, 0x0)
	/go/src/k8s.io/dns/vendor/github.com/golang/glog/glog.go:720 +0x2f8
k8s.io/dns/vendor/github.com/golang/glog.(*loggingT).printf(0x130a968, 0x3, 0xcb7f76, 0x36, 0x1171bee4, 0x1, 0x1)
	/go/src/k8s.io/dns/vendor/github.com/golang/glog/glog.go:655 +0x10c
k8s.io/dns/vendor/github.com/golang/glog.Fatalf(0xcb7f76, 0x36, 0x1171bee4, 0x1, 0x1)
	/go/src/k8s.io/dns/vendor/github.com/golang/glog/glog.go:1148 +0x4c
k8s.io/dns/pkg/dnsmasq.RunNanny(0x12c4560, 0x118d12a0, 0xc90bb1, 0x11, 0x131b138, 0x0, 0x0, 0x0)
	/go/src/k8s.io/dns/pkg/dnsmasq/nanny.go:173 +0x1dc
main.main()
	/go/src/k8s.io/dns/cmd/dnsmasq-nanny/main.go:80 +0x21c
```

**Comment by asac** [comment]
Yeah,

if i am not mistaken build always uses glibc toolchain for the cross archs as one can see in https://github.com/kubernetes/dns/blob/master/images/dnsmasq/Makefile ... but then in the end nanny docker build mix and matches that glibc binary into images without glibc?

Let me know if I shall test anything or if you need more info...

**Comment by bowei** [comment]
Is the executable file missing or the .so dependency (e.g. ldd dnsmasq has unresolved libs)

**Comment by asac** [comment]
glibc isnt in the image where the build copies it in ... at best we could
just build it all static i guess...

**Comment by ixdy** [comment]
https://github.com/kubernetes/dns/pull/108#issuecomment-308262259

I guess that's what broke arm, maybe?

**Comment by asac** [comment]
Thanks @ixdy! changing base image to use armhf/busybox instead of armel/busybox does indeed do the trick for me....

**Comment by luxas** [comment]
@asac yes, gcc binary was changed to armhf, but it wasn't reflected by changing the baseimage -- please fix that if you have time

**Comment by asac** [comment]
i made a pull request, got asked to sign CLA, did that, resubmitted new pull request and still get complain about not signed CLA. if i click on details there, linux foundation tells me its all fine....  so not sure how to proceed. Guess I wait a bit and hope that the CLA just takes a while to update on github side...

**Comment by asac** [comment]
ok just when i wanted to give up , CLA is finally "check" :P... and travis is running on #114 ... thx.

**Comment by luxas** [comment]
@asac Perfect, thank you!
I'm sorry you had trouble getting the CLA bot to work... not sure what happened there. May just be a slight (too long UX though) delay in the process.

I'll take a look at your PR

**Comment by luxas** [comment]
@bowei Will you release the .4 now?

**Comment by bowei** [comment]
1.14.4 has been pushed to google_containers.

**Comment by bowei** [comment]
https://github.com/kubernetes/kubernetes/pull/48044

**Comment by asac** [comment]
quick ack so you guys know that 1.14.4 works out of the box now on armhf
... thanks for the release!
