### ISSUE TITLE
Please document how kube-dns works.

### ISSUE THREAD

**Issue by dElogics** [kubernetes/dns#122]
Currently kubedns is a black box and no one knows how it works (for e.g. the --kube-master-url= switch). As a result, except for a static set of cloud based infrastructure, it's practically impossible to get it working any place else.

So please document how kubedns works at the daemon level so the ecosystem can be created on a physical machine or custom containers based on custom OS can be build for those daemons.

**Comment by marcellodesales** [comment]
@dElogics is there any other reference we can find on how to setup kube-dns with `dnsmasq`?

**Comment by vidhy** [comment]
I am wondering why the dnsPolicy is not set to clusterFirst by default.

**Comment by bowei** [comment]
I think it is set to clusterFirst by default? Can you give me an example?

**Comment by bowei** [comment]
For the original bug filer, can you give more details on what you would want to be documented?

**Comment by chrisohaver** [comment]
@bowei, I suspect @vidhy is asking about why kube-dns does not default to use clusterFirst policy. 

I explain how this would create a loop ... here kubernetes/kops#5592

**Comment by vidhy** [comment]
@bowei  The name being 'Default' I assumed that it will be the default dnsPolicy. After your comment  I refered  the docs. It says

>  “Default” is not the default DNS policy. If dnsPolicy is not explicitly specified, then “ClusterFirst” is used."

The naming was quite confusing. Now I get that clusterFirst is the default dnsPolicy. Thanks.
