### ISSUE TITLE
Add support for serving on specified namespaces

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/dns#132]
kube-dns is serving on all namespaces today. As we are moving on to support multiple networks, pods on different networks may not access each other, e.g. in a multi-tenant environment. 

So I propose to support serving on specified namespace in kube-dns, so as to conform such use cases.

cc/ @bowei

**Comment by thockin** [comment]
This might be premature.  Without a larger design it's sort of
speculative.  At the very least, it should be a list of namespaces or
better - a selector.

**Comment by feiskyer** [comment]
> This might be premature.  Without a larger design it's sort of speculative. 

Yep, this still needs more ideas from community. e.g. 

- does the feature make sense for most multi network use cases?
- if yes, how to make it general enough?

> At the very least, it should be a list of namespaces or better - a selector.

Good catch. Currently kubernetes api doesn't support watching on a list of namespaces, but we could support this by filtering namespaces in client side. 

cc/ @kubernetes/sig-network-feature-requests

**Comment by thockin** [comment]
I think a selector is closest to current thinking on multi-tenancy.  We may have to implement something like a selector-based watch or a listed watch to make this possible.

@davidopp @smarterclayton

**Comment by davidopp** [comment]
https://github.com/kubernetes/ingress/issues/816 is vaguely relevant

**Comment by cmluciano** [comment]
Also related https://github.com/kubernetes/community/pull/269

**Comment by cmluciano** [comment]
I tried pushing this for a while, but I think we ran into  "are namespaces sufficient for tenancy" as Tim mentioned. 

Relevant mailing list threads:
- [DNS servers: shared or per-namespace](https://groups.google.com/d/msg/kubernetes-sig-network/3q7xMw21Y5s/oqDlVOCwCQAJ)
- [RBAC Oddity](https://groups.google.com/d/msg/kubernetes-sig-network/3q7xMw21Y5s/oqDlVOCwCQAJ)

[Proposal DNS per namespace](https://github.com/kubernetes/community/pull/269)

**Comment by johnbelamaric** [comment]
We do this in CoreDNS, you can configure a selector. But it's configured for the whole instance, so you need to run separate instances with different namespaces configured. And then you would need to deal with pointing the pods at the right instance that is configured for those namespaces.

I think a more general solution would be to allow enforcement of RBAC in the DNS. So the DNS server will infer the pod from the source IP and from that the security context, and enforce the visibility based on that.

**Comment by thockin** [comment]
I worry that different customers will have different needs.  Per-tenant DNS
seems likely, as different apps will have different needs for DNS.  We'll
have to re-think a lot of pieces to make that work.

@davidopp
