### ISSUE TITLE
SRV records for external services

### ISSUE THREAD

**Issue by johnbelamaric** [kubernetes/dns#140]
The spec (at least with #89) says to return a CNAME for an external service. This is fine for A records. The question is what to do about SRV records. There are four scenarios:

1. There *is not* an SRV record for the name in the upstream, and port info *is not* specified in the external service definition. I think return no data.
2. There *is* an SRV record in the upstream for that name, and port info *is not* specified in the external service definition. I think return the upstream SRV (which would be the normal DNS thing to do)
3. There *is not* an SRV record for the name in the upstream, and port info *is* specified in the external service definition. I think return a synthetic SRV based on external service definition.
4. There *is* an SRV record for the name in the upstream, and port info *is* specified in the external service definition. Umm...not sure here. Probably prefer the K8s external service definition. Or maybe return both.

We should specify the correct result in each of these scenarios.

Here's what `kube-dns` (using `minikube` with K8s v1.7.0) does today in each of these scenarios.

*Scenario 1*
```
dnstools# host ext-svc-no-port.test-1.svc.cluster.local.
ext-svc-no-port.test-1.svc.cluster.local is an alias for example.com.
example.COM has address 93.184.216.34
example.COM has IPv6 address 2606:2800:220:1:248:1893:25c8:1946
dnstools# host -t srv ext-svc-no-port.test-1.svc.cluster.local.
ext-svc-no-port.test-1.svc.cluster.local has SRV record 10 100 0 example.com.
dnstools#
```

WTH? It just made up a bogus SRV record.

*Scenario 2*
Here is an example of a CNAME whose target has an SRV, using records in the upstream DNS (i.e., `kube-dns` is forwarding this query):

```
dnstools# host -t srv foo.kops.belamaric.com
foo.kops.belamaric.COM is an alias for kops.belamaric.com.
kops.belamaric.com has SRV record 1 10 9876 kops.belamaric.com.
dnstools#
```

In K8s, I have defined an external name service without any port specified, and pointing to `kops.belamaric.com` which holds an SRV record. The first query here shows that the normal A record lookup for the external name works; the second shows what you get for the SRV query:

```
dnstools# host ext-svc-srv-no-port.test-1.svc.cluster.local.
ext-svc-srv-no-port.test-1.svc.cluster.local is an alias for kops.belamaric.com.
dnstools# host -t srv ext-svc-srv-no-port.test-1.svc.cluster.local.
ext-svc-srv-no-port.test-1.svc.cluster.local has SRV record 10 100 0 kops.belamaric.com.
dnstools#
```

Again, the same bogus SRV record. 

*Scenario 3*
Same thing:

```
dnstools# host ext-svc.test-1.svc.cluster.local.
ext-svc.test-1.svc.cluster.local is an alias for example.net.
example.net has address 93.184.216.34
example.net has IPv6 address 2606:2800:220:1:248:1893:25c8:1946
dnstools# host -t srv ext-svc.test-1.svc.cluster.local.
ext-svc.test-1.svc.cluster.local has SRV record 10 100 0 example.net.
dnstools#
```

*Scenario 4*
```
dnstools# host ext-svc-srv.test-1.svc.cluster.local.
ext-svc-srv.test-1.svc.cluster.local is an alias for kops.belamaric.com.
dnstools# host -t srv ext-svc-srv.test-1.svc.cluster.local.
ext-svc-srv.test-1.svc.cluster.local has SRV record 10 100 0 kops.belamaric.com.
dnstools#
```

Same thing again.

So today it looks like `kube-dns` just creates a fake, incorrect SRV record in all these cases. Today in CoreDNS, I think we return nodata in most of these cases.

**Comment by johnbelamaric** [comment]
@miekg @chrisohaver

**Comment by thockin** [comment]
DNS RFC is pretty clear that if there is a CNAME record there must be no
other records for that name.  It also seems that an SRV must point to an A,
not a CNAME.

https://serverfault.com/questions/765743/published-srv-records-pointing-to-cname-alias-in-violation-of-rfc-2782

**Comment by johnbelamaric** [comment]
Yes, SRV points to A, the question is CNAME pointing to SRV.

**Comment by thockin** [comment]
The first example seems to be RFC-breaking to me:

```
dnstools# host ext-svc-no-port.test-1.svc.cluster.local.
ext-svc-no-port.test-1.svc.cluster.local is an alias for example.com.
example.COM has address 93.184.216.34
example.COM has IPv6 address 2606:2800:220:1:248:1893:25c8:1946
dnstools# host -t srv ext-svc-no-port.test-1.svc.cluster.local.
ext-svc-no-port.test-1.svc.cluster.local has SRV record 10 100 0 example.com
.
```

You're asking for an SRV record for
`ext-svc-no-port.test-1.svc.cluster.local.` when you know that there is a
CNAME record for it.  The correct response is NXDOMAIN or NODATA or an
error (not sure).

**Comment by johnbelamaric** [comment]
No, pretty sure this is legit. The client doesn't know if there is a CNAME or not, and the server should follow it regardless of the original type the client asked for. @cricketlui can you confirm?

**Comment by cricketliu** [comment]
@thockin is correct.  If ext-svc-no-port-test-1.svc.cluster.local is an alias (i.e., owns a CNAME RR), then it can't also own an SRV RR.  The SRV RR would need to be attached to the target of the alias, example.com.

**Comment by johnbelamaric** [comment]
Ok, I think I am just not being clear then, because that isn't what I meant to suggest. What I am saying is that if that CNAME points to a name, it's fine for that name to have an SRV record. So, in that case, if mycname.example.com is a CNAME for foo.example.com, then 

host -t srv mycname.belamaric.com

should return the SRV at foo.example.com. Does that makes sense?
would r

**Comment by johnbelamaric** [comment]
In the example Tim quotes, I would have expected nodata for the SRV, instead of the bogus SRV record.

But scenario two should return the SRV, like it does in the example:

```
dnstools# host -t srv foo.kops.belamaric.com
foo.kops.belamaric.COM is an alias for kops.belamaric.com.
kops.belamaric.com has SRV record 1 10 9876 kops.belamaric.com.
dnstools#
```

For `ext-svc-srv-no-port.test-1.svc.cluster.local` which is a CNAME to `kops.belamaric.com`, I should see:

```
dnstools# host -t srv ext-svc-srv-no-port.test-1.svc.cluster.local.
ext-svc-srv-no-port.test-1.svc.cluster.local is an alias for kops.belamaric.com.
kops.belamaric.com has SRV record 1 10 9876 kops.belamaric.com.
```

But instead I am getting:

```
dnstools# host ext-svc-srv-no-port.test-1.svc.cluster.local.
ext-svc-srv-no-port.test-1.svc.cluster.local is an alias for kops.belamaric.com.
dnstools# host -t srv ext-svc-srv-no-port.test-1.svc.cluster.local.
ext-svc-srv-no-port.test-1.svc.cluster.local has SRV record 10 100 0 kops.belamaric.com.
dnstools#
```

**Comment by bowei** [comment]
@johnbelamaric -- in your example, are you saying the DNS server should implicitly resolve CNAME chains? I don't think that is RFC compliant (as mentioned above).

Some DNS servers/services implement this as a feature internally, but it never leaks out to the world as an actual CNAME record.

**Comment by johnbelamaric** [comment]
No, I don't think there are any chains here. I am just saying it's OK for CNAME (our external service name) to point to a name that has an SRV record, and we should be resolving that.

**Comment by johnbelamaric** [comment]
All I am saying is that the target of the CNAME can be a name with SRV records, and that should resolve successfully.

**Comment by cricketliu** [comment]
That is certainly true.

cricket

On Aug 16, 2017, at 5:13 PM, John Belamaric <notifications@github.com<mailto:notifications@github.com>> wrote:


All I am saying is that the target of the CNAME can be a name with SRV records, and that should resolve successfully.

**Comment by thockin** [comment]
> Ok, I think I am just not being clear then, because that isn't what I meant to suggest. What I am saying is that if that CNAME points to a name, it's fine for that name to have an SRV record. So, in that case, if mycname.example.com is a CNAME for foo.example.com, then
>
> host -t srv mycname.belamaric.com
>
> should return the SRV at foo.example.com. Does that makes sense?
> would r

I just do not think that is true.  It's a weird corner case, to be
sure, but I don't think it is true.  That aside, the true SRV names
are _svc._tcp.... which do not have to follow the CNAME rule.  I
think.

**Comment by cricketliu** [comment]
No, I'm fairly certain John's right. And the fact that a domain name contains labels that begin with underscores has no bearing on whether it can own a CNAME RR.

cricket

On Aug 16, 2017, at 5:33 PM, Tim Hockin <notifications@github.com<mailto:notifications@github.com>> wrote:

> Ok, I think I am just not being clear then, because that isn't what I meant to suggest. What I am saying is that if that CNAME points to a name, it's fine for that name to have an SRV record. So, in that case, if mycname.example.com<http://mycname.example.com> is a CNAME for foo.example.com<http://foo.example.com>, then
>
> host -t srv mycname.belamaric.com<http://mycname.belamaric.com>
>
> should return the SRV at foo.example.com<http://foo.example.com>. Does that makes sense?
> would r

I just do not think that is true. It's a weird corner case, to be
sure, but I don't think it is true. That aside, the true SRV names
are _svc._tcp.... which do not have to follow the CNAME rule. I
think.

**Comment by johnbelamaric** [comment]
Yeah, the name doesn't matter. Here is an example (not in k8s) of a CNAME that points to name that has no A record but does have an SRV record. You can see it returns nodata for the A, but returns the SRV record just fine.

```
ANN-M-JBELAMARIC:~ jbelamaric$ host bar.kops.belamaric.com
bar.kops.belamaric.COM is an alias for _test._tcp.kops.belamaric.com.
ANN-M-JBELAMARIC:~ jbelamaric$ host -t srv bar.kops.belamaric.com
bar.kops.belamaric.COM is an alias for _test._tcp.kops.belamaric.com.
_test._tcp.kops.belamaric.COM has SRV record 1 10 1022 api.us-east-1.kops.belamaric.com.
ANN-M-JBELAMARIC:~ jbelamaric$ host -t a bar.kops.belamaric.com
bar.kops.belamaric.COM is an alias for _test._tcp.kops.belamaric.com.
ANN-M-JBELAMARIC:~ jbelamaric$
```

And I don't think it's that strange of a corner case. All it is is wanting to do an SRV-based discovery on an external name service, instead of getting just an IP.

**Comment by bowei** [comment]
Can you show what `dig` returns? I'm not very familiar with the internal logic of the `host` command

**Comment by johnbelamaric** [comment]
I can do that. However, I actually think this is a distraction. The point of this issue wasn't so much about what `kube-dns` does today, but was about what the *spec* should say about this subject.

That said, let's dig into the distraction a bit. A few things to address.

*Proper _port, _proto SRV formatting*

I don't think this is relevant to the question at hand. This is a convention, and SRV works without it. In fact, if you look at how SRV is used in peer-finder, it passes empty port and protocol, but still expects a result: https://github.com/kubernetes/contrib/blob/master/peer-finder/peer-finder.go#L50. In CoreDNS we followed the RFC and wouldn't return the SRV records for those, which broke stuff, so now we will return those (SkyDNS already did this I believe).

So, what that means is that we don't need to specify those _ labels in our external name definition, which is a good thing because you can't:

```
ANN-M-JBELAMARIC:~ jbelamaric$ cat /tmp/ext.yaml
apiVersion: v1
kind: Service
metadata:
  name: ext-svc-no-port
spec:
  externalName: _test._tcp.kops.belamaric.com
  sessionAffinity: None
  type: ExternalName
ANN-M-JBELAMARIC:~ jbelamaric$ kubectl apply -f /tmp/ext.yaml
The Service "ext-svc-no-port" is invalid: spec.externalName: Invalid value: "_test._tcp.kops.belamaric.com": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
ANN-M-JBELAMARIC:~ jbelamaric$
```

Instead, you create one without it and just create SRV records at the target.

*Query Results*

In my case, here is what I have set up:

`foo.kops.belamaric.com.` has a CNAME record with target `kops.belamaric.com`
`kops.belamaric.com.` has an SRV record `1 10 1022 api.us-east-1.kops.belamaric.com.`
`kops.belamaric.com.` does NOT have an A record
`api.us-east-1.kops.belamaric.com.` has an A record
`ext-srv-no-port` is an External Name service in the default namespace, with `externalName` pointing to `kops.belamaric.com`:

```
apiVersion: v1
kind: Service
metadata:
  name: ext-svc-no-port
spec:
  externalName: kops.belamaric.com
  type: ExternalName
```

*Results of dig*

Here are the results of various `dig` commands.

*On my laptop (no `kube-dns`)*
```
ANN-M-JBELAMARIC:~ jbelamaric$ dig kops.belamaric.com.

; <<>> DiG 9.8.3-P1 <<>> kops.belamaric.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19209
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;kops.belamaric.com.		IN	A

;; AUTHORITY SECTION:
kops.belamaric.com.	900	IN	SOA	ns-1148.awsdns-15.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 111 msec
;; SERVER: 10.120.3.10#53(10.120.3.10)
;; WHEN: Thu Aug 17 16:01:16 2017
;; MSG SIZE  rcvd: 118

ANN-M-JBELAMARIC:~ jbelamaric$ dig -t srv kops.belamaric.com.

; <<>> DiG 9.8.3-P1 <<>> -t srv kops.belamaric.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18759
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kops.belamaric.com.		IN	SRV

;; ANSWER SECTION:
kops.belamaric.com.	60	IN	SRV	1 10 1022 api.us-east-1.kops.belamaric.com.

;; Query time: 100 msec
;; SERVER: 10.102.3.10#53(10.102.3.10)
;; WHEN: Thu Aug 17 16:01:29 2017
;; MSG SIZE  rcvd: 88

ANN-M-JBELAMARIC:~ jbelamaric$ dig foo.kops.belamaric.com.

; <<>> DiG 9.8.3-P1 <<>> foo.kops.belamaric.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4424
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;foo.kops.belamaric.com.		IN	A

;; ANSWER SECTION:
foo.kops.belamaric.com.	300	IN	CNAME	kops.belamaric.com.

;; AUTHORITY SECTION:
kops.belamaric.com.	505	IN	SOA	ns-1148.awsdns-15.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 102 msec
;; SERVER: 10.102.3.10#53(10.102.3.10)
;; WHEN: Thu Aug 17 16:03:08 2017
;; MSG SIZE  rcvd: 136

ANN-M-JBELAMARIC:~ jbelamaric$ dig -t srv foo.kops.belamaric.com.

; <<>> DiG 9.8.3-P1 <<>> -t srv foo.kops.belamaric.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52684
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;foo.kops.belamaric.com.		IN	SRV

;; ANSWER SECTION:
foo.kops.belamaric.com.	300	IN	CNAME	kops.belamaric.com.
kops.belamaric.com.	60	IN	SRV	1 10 1022 api.us-east-1.kops.belamaric.com.

;; Query time: 180 msec
;; SERVER: 10.120.3.10#53(10.120.3.10)
;; WHEN: Thu Aug 17 16:03:17 2017
;; MSG SIZE  rcvd: 106

ANN-M-JBELAMARIC:~ jbelamaric$
```

*Results running in a pod with `kube-dns` doing resolution*

Running the same queries in minikube with `kube-dns`, we get the same results (this is expected because here `kube-dns` is just forwarding the queries, not answering them itself).

```
ANN-M-JBELAMARIC:~ jbelamaric$ kubectl run --rm --image=infoblox/dnstools -it dnstools
If you don't see a command prompt, try pressing enter.
dnstools# dig kops.belamaric.com.

; <<>> DiG 9.11.1-P1 <<>> kops.belamaric.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54205
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;kops.belamaric.com.		IN	A

;; AUTHORITY SECTION:
kops.belamaric.com.	691	IN	SOA	ns-1148.awsdns-15.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 2501 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Thu Aug 17 20:04:46 UTC 2017
;; MSG SIZE  rcvd: 129

dnstools# dig -t srv kops.belamaric.com.

; <<>> DiG 9.11.1-P1 <<>> -t srv kops.belamaric.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27843
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;kops.belamaric.com.		IN	SRV

;; ANSWER SECTION:
kops.belamaric.com.	60	IN	SRV	1 10 1022 api.us-east-1.kops.belamaric.com.

;; Query time: 113 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Thu Aug 17 20:04:54 UTC 2017
;; MSG SIZE  rcvd: 99

dnstools# dig foo.kops.belamaric.com.

; <<>> DiG 9.11.1-P1 <<>> foo.kops.belamaric.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37207
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;foo.kops.belamaric.com.		IN	A

;; ANSWER SECTION:
foo.kops.belamaric.com.	188	IN	CNAME	kops.belamaric.com.

;; AUTHORITY SECTION:
kops.belamaric.com.	393	IN	SOA	ns-1148.awsdns-15.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 103 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Thu Aug 17 20:05:00 UTC 2017
;; MSG SIZE  rcvd: 147

dnstools# dig -t srv foo.kops.belamaric.com.

; <<>> DiG 9.11.1-P1 <<>> -t srv foo.kops.belamaric.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4001
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;foo.kops.belamaric.com.		IN	SRV

;; ANSWER SECTION:
foo.kops.belamaric.com.	183	IN	CNAME	kops.belamaric.com.
kops.belamaric.com.	50	IN	SRV	1 10 1022 api.us-east-1.kops.belamaric.com.

;; Query time: 99 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Thu Aug 17 20:05:04 UTC 2017
;; MSG SIZE  rcvd: 117

dnstools#
```

Now what happens with `ext-svc-no-port`, which *should* just be like any other CNAME:

```
dnstools# dig ext-svc-no-port.default.svc.cluster.local.

; <<>> DiG 9.11.1-P1 <<>> ext-svc-no-port.default.svc.cluster.local.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2150
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ext-svc-no-port.default.svc.cluster.local. IN A

;; ANSWER SECTION:
ext-svc-no-port.default.svc.cluster.local. 30 IN CNAME kops.belamaric.com.

;; Query time: 97 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Thu Aug 17 20:07:42 UTC 2017
;; MSG SIZE  rcvd: 91

dnstools# dig -t srv ext-svc-no-port.default.svc.cluster.local.

; <<>> DiG 9.11.1-P1 <<>> -t srv ext-svc-no-port.default.svc.cluster.local.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62776
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ext-svc-no-port.default.svc.cluster.local. IN SRV

;; ANSWER SECTION:
ext-svc-no-port.default.svc.cluster.local. 30 IN SRV 10 100 0 kops.belamaric.com.

;; Query time: 194 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Thu Aug 17 20:08:08 UTC 2017
;; MSG SIZE  rcvd: 97

dnstools#
```

What we see here is the first query works as it should - it returns the CNAME but since there is no A record it returns NODATA (if it had an A record it would have worked, too).

The second query manufactures a fake SRV.

John
