### ISSUE TITLE
no RRs for domain "kubernetes.default.svc.cluster.local."

### ISSUE THREAD

**Issue by aanm** [kubernetes/dns#141]
I'm getting a weird error from kube-dns that is preventing it from starting.

Apparently the livenessProbe is returning this error:

`{"IsOk":false,"LatencySeconds":0,"Err":"no RRs for domain \"kubernetes.default.svc.cluster.local.\""}`

What does it mean? It seems kube-dns can't find the endpoint address of the kubernetes service, is that correct? If yes, how can I debug the reason for `that?

`kubectl describe endpoints kubernetes` shows the endpoints addresses on a ready state.

**Comment by aanm** [comment]
If anyone got this error, make sure the `sidecar` probes are checking for the correct IP address records with the options provided

**Comment by keir-rex** [comment]
@aanm could you clarify on what you mean and what the solution was?

**Comment by aanm** [comment]
@keir-rex for example, if your `kube-master` is running on IPv6, the entry that will be created on the DNS will be the type of `AAAA` for domain `kubernetes.default.svc.cluster.local.`. The probes specified on the kube-dns spec file will check if the kube-dns is up an running by checking if there's a type `A` entry (IPv4) for `kubernetes.default.svc.cluster.local.`. That probe will always fail because there isn't any `A` record, only `AAAA`.
