### ISSUE TITLE
Add support for nameservers with IPv6 addresses

### ISSUE THREAD

**Issue by leblancd** [kubernetes/dns#147]
If kube-dns is run on a minion that has a nameserver listed in
/etc/resolv.conf with an IPv6 address, then the dnsmasq nanny container
dies shortly after reading this resolv.conf file, and the liveness probe
never indicates a healthy pod (pod is restarted after a few minutes).

**Comment by leblancd** [comment]
@thockin: Can you please add an area/ipv6 to this issue?

**Comment by bowei** [comment]
ah -- we haven't propagated labels to this project yet

**Comment by valentin2105** [comment]
In my case, I use ConfigMap to give kube-dns's Backends DNS servers, and with a IPv6 server, it seem to be ignored, because kube-dns work properly but it never contact my IPv6 DNS server.

It would be great to support this feature. (on a road, to get at end, only IPv6 pods).

**Comment by leblancd** [comment]
@valentin2015: Thanks. Yes, this change is needed for IPv6-only clusters (not so much for dual-stack clusters), and our first target is IPv6-only operation, and then dual-stack support will follow.
