### ISSUE TITLE
Questioning probe_latency_ms buckets

### ISSUE THREAD

**Issue by bboreham** [kubernetes/dns#149]
In `pkg/sidecar/dnsprobe.go` the code calls `prometheus.LinearBuckets(0, 10, 500)`, which creates 500 buckets at 0ms, 10ms, 20ms, ...

My kube-dns manages to serve nearly everything in under 10ms, so these buckets are (a) very numerous and (b) telling me nothing.

I would be interested to know what the thinking was - why not use `ExponentialBuckets()` to save space and start at a lower interval?

**Comment by bowei** [comment]
You probably right, exponential makes more sense.

**Comment by bboreham** [comment]
I just realised the units are in _seconds_.
