### ISSUE TITLE
1.14.5 version is missing

### ISSUE THREAD

**Issue by mindw** [kubernetes/dns#153]
kubernetes 1.7.7 released with the above version.
Where can the changelog and release be found?

**Comment by euank** [comment]
Presumably the version was embargoed for security reasons. However, I think they should be public now given Google wrote the following blogpost: https://security.googleblog.com/2017/10/behind-masq-yet-more-dns-and-dhcp.html

@bowei do you perhaps know when the associated source code will be posted? It's technically a GPL violation to be shipping dnsmasq binaries for which code is not available.

**Comment by bowei** [comment]
The updated sources should be updated today. I was waiting for upstream, which it looks like it is now.
@thockin @cjcullen

**Comment by thockin** [comment]
Should be OK to get everything merged properly now.

**Comment by bowei** [comment]
1.14.5 tag is available now. It is on the `1.14.4+security-fix` branch and tagged with `1.14.5`.

**Comment by bowei** [comment]
Closing issue - please reopen if you have further questions.
