### ISSUE TITLE
1.14.5 vs 1.15.6

### ISSUE THREAD

**Issue by SleepyBrett** [kubernetes/dns#155]
After hearing about the CVE fixes to dnsmasq yesterday I upgrade my kubedns to 1.14.5 which uses the following dnsmasq:

    / # dnsmasq --version
    Dnsmasq version 2.78-security-prerelease  Copyright (c) 2000-2017 Simon Kelley 
    Compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify

This morning I see a new release of 1.14.6 but the commit looks the same as 1.14.5? Is there any difference?

**Comment by bowei** [comment]
1.14.5 is only 1.14.4 + dnsmasq update
1.14.6 is HEAD (include dnsmasq update)

We decided that it was much safer to release 1.14.5 without additional changes.
1.14.6 will go into1.9 very soon.
