### ISSUE TITLE
Not able to access external resources outside pod (docker container)

### ISSUE THREAD

**Issue by wheestermans** [kubernetes/dns#156]
I know it is not really DNS related, but didn't find other group fro this question.

When I telnet aaa.bbb.ccc.ddd 3202 on host node the connection is working fine, acceptance (DB2 connection) . Now when I do exactly the same outside running pod (docker container), the connectivity is not working.

From the host:

_telnet 150.45.92.41 3200
Trying 150.45.92.41...
Connected to 150.45.92.41.
Escape character is '^]'_

From the pod (docker container)

_sh-4.2$ telnet 150.45.92.41 3200
Trying 150.45.92.41..._

 **kubectl describe pod npaqit-service-2193241535-8f3x6**
Name:           npaqit-service-2193241535-8f3x6
Namespace:      default
Node:           lxdocapt14/150.45.89.109
Start Time:     Mon, 09 Oct 2017 14:55:52 +0200
Labels:         io.kompose.service=npaqit-service
                pod-template-hash=2193241535
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"npaqit-service-2193241535","uid":"2e3d351c-acf1-11e7-9138-005056...
Status:         Running
IP:             10.244.3.30
Created By:     ReplicaSet/npaqit-service-2193241535
Controlled By:  ReplicaSet/npaqit-service-2193241535
Containers:
  npaqit-service:
    Container ID:       docker://dd6e7226ba757f310051645129bf2650bb537da219abba16113492143d3ba637
    Image:              dockerdtrtest.toyota-europe.com/toyota/npaqit:2.5
    Image ID:           docker-pullable://dockerdtrtest.toyota-europe.com/toyota/npaqit@sha256:d216922feb0a625e282b50bc2a5582bb6f4336262c45eebb57142eae97d1794a
    Port:               <none>
    State:              Running
      Started:          Mon, 09 Oct 2017 14:55:55 +0200
    Ready:              True
    Restart Count:      0
    Environment:
      ENVIRONMENT:      uat
      SERVICE_NAME:     npaqit
    Mounts:
      /opt/apps-logs from volume-appslogs (rw)
      /opt/data/npaa from volume-npaa (rw)
      /opt/secrets from admin-confidential (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5mzdh (ro)
Conditions:
  Type          Status
  Initialized   True 
  Ready         True 
  PodScheduled  True 
Volumes:
  volume-appslogs:
    Type:       HostPath (bare host directory volume)
    Path:       /opt/apps-logs
  volume-npaa:
    Type:       HostPath (bare host directory volume)
    Path:       /opt/data/npaa
  admin-confidential:
    Type:       Secret (a volume populated by a Secret)
    SecretName: npaqit-admin-confidential
    Optional:   false
  default-token-5mzdh:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-5mzdh
    Optional:   false
QoS Class:      BestEffort
Node-Selectors: <none>
Tolerations:    node.alpha.kubernetes.io/notReady:NoExecute for 300s
                node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath                   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------                   --------        ------                  -------
  22m           22m             1       default-scheduler                                       Normal          Scheduled               Successfully assigned npaqit-service-2193241535-8f3x6 to lxdocapt14
  22m           22m             1       kubelet, lxdocapt14                                     Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "volume-npaa" 
  22m           22m             1       kubelet, lxdocapt14                                     Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "volume-appslogs" 
  22m           22m             1       kubelet, lxdocapt14                                     Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "admin-confidential" 
  22m           22m             1       kubelet, lxdocapt14                                     Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "default-token-5mzdh" 
  22m           22m             1       kubelet, lxdocapt14     spec.containers{npaqit-service} Normal          Pulled                  Container image "dockerdtrtest.toyota-europe.com/toyota/npaqit:2.5" already present on machine
  22m           22m             1       kubelet, lxdocapt14     spec.containers{npaqit-service} Normal          Created                 Created container
  22m           22m             1       kubelet, lxdocapt14     spec.containers{npaqit-service} Normal          Started                 Started container

**docker inspect dd6e7226ba75**
[
    {
        "Id": "dd6e7226ba757f310051645129bf2650bb537da219abba16113492143d3ba637",
        "Created": "2017-10-09T12:55:53.512971109Z",
        "Path": "/docker-entrypoint.bash",
        "Args": [
            "java",
            "-jar",
            "/opt/jetty/start.jar"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 15345,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-10-09T12:55:55.589943142Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:f937f9fd70a140d8c9a1d806a998a5444d9ac50ba659f00c4a5e16502ced8c95",
        "ResolvConfPath": "/var/lib/docker/containers/8bdcbe05986ac06eff4c70720cd252706acd744b4c6e6e289007abf5d6104e07/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/8bdcbe05986ac06eff4c70720cd252706acd744b4c6e6e289007abf5d6104e07/hostname",
        "HostsPath": "/var/lib/kubelet/pods/2e3e59dd-acf1-11e7-9138-005056800b9d/etc-hosts",
        "LogPath": "/var/lib/docker/containers/dd6e7226ba757f310051645129bf2650bb537da219abba16113492143d3ba637/dd6e7226ba757f310051645129bf2650bb537da219abba16113492143d3ba637-json.log",
        "Name": "/k8s_npaqit-service_npaqit-service-2193241535-8f3x6_default_2e3e59dd-acf1-11e7-9138-005056800b9d_0",
        "RestartCount": 0,
        "Driver": "devicemapper",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/opt/apps-logs:/opt/apps-logs",
                "/opt/data/npaa:/opt/data/npaa",
                "/var/lib/kubelet/pods/2e3e59dd-acf1-11e7-9138-005056800b9d/volumes/kubernetes.io~secret/admin-confidential:/opt/secrets:ro",
                "/var/lib/kubelet/pods/2e3e59dd-acf1-11e7-9138-005056800b9d/volumes/kubernetes.io~secret/default-token-5mzdh:/var/run/secrets/kubernetes.io/serviceaccount:ro",
                "/var/lib/kubelet/pods/2e3e59dd-acf1-11e7-9138-005056800b9d/etc-hosts:/etc/hosts",
                "/var/lib/kubelet/pods/2e3e59dd-acf1-11e7-9138-005056800b9d/containers/npaqit-service/8dec9878:/dev/termination-log"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "container:8bdcbe05986ac06eff4c70720cd252706acd744b4c6e6e289007abf5d6104e07",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "container:8bdcbe05986ac06eff4c70720cd252706acd744b4c6e6e289007abf5d6104e07",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 1000,
            "PidMode": "container:8bdcbe05986ac06eff4c70720cd252706acd744b4c6e6e289007abf5d6104e07",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "seccomp=unconfined"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 2,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "/kubepods/besteffort/pod2e3e59dd-acf1-11e7-9138-005056800b9d",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "8103",
                "DeviceName": "docker-251:0-264590-5b4f9f315a9a70957ea2468813b7c97d249f44d86281593b6551e3b5b6ac13ba",
                "DeviceSize": "10737418240"
            }
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/opt/apps-logs",
                "Destination": "/opt/apps-logs",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/opt/data/npaa",
                "Destination": "/opt/data/npaa",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/var/lib/kubelet/pods/2e3e59dd-acf1-11e7-9138-005056800b9d/volumes/kubernetes.io~secret/admin-confidential",
                "Destination": "/opt/secrets",
                "Mode": "ro",
                "RW": false,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/var/lib/kubelet/pods/2e3e59dd-acf1-11e7-9138-005056800b9d/volumes/kubernetes.io~secret/default-token-5mzdh",
                "Destination": "/var/run/secrets/kubernetes.io/serviceaccount",
                "Mode": "ro",
                "RW": false,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/var/lib/kubelet/pods/2e3e59dd-acf1-11e7-9138-005056800b9d/etc-hosts",
                "Destination": "/etc/hosts",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/var/lib/kubelet/pods/2e3e59dd-acf1-11e7-9138-005056800b9d/containers/npaqit-service/8dec9878",
                "Destination": "/dev/termination-log",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "npaqit-service-2193241535-8f3x6",
            "Domainname": "",
            "User": "jetty",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "ENVIRONMENT=uat",
                "SERVICE_NAME=npaqit",
                "KUBERNETES_SERVICE_PORT=443",
                "KUBERNETES_SERVICE_PORT_HTTPS=443",
                "KUBERNETES_PORT=tcp://10.96.0.1:443",
                "KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443",
                "KUBERNETES_PORT_443_TCP_PROTO=tcp",
                "KUBERNETES_PORT_443_TCP_PORT=443",
                "KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1",
                "KUBERNETES_SERVICE_HOST=10.96.0.1",
                "PATH=/opt/jetty/bin:/opt/jdk8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "REFRESHED_AT=2017-09-04",
                "http_proxy=150.45.87.133:8080",
                "https_proxy=150.45.87.133:8080",
                "JAVA_HOME=/opt/jdk8",
                "JETTY_HOME=/opt/jetty",
                "JETTY_VERSION=9.3.21.v20170918",
                "JETTY_TGZ_URL=https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.3.21.v20170918/jetty-distribution-9.3.21.v20170918.tar.gz",
                "JETTY_GPG_KEYS=AED5EE6C45D0FE8D5D1B164F27DED4BF6216DB8F \t2A684B57436A81FA8706B53C61C3351A438A3B7D \t5989BAF76217B843D66BE55B2D0E1FB8FE4B68B4 \tB59B67FD7904984367F931800818D9D68FB67BAC \tBFBB21C246D7776836287A48A04E0C74ABB35FEA \t8B096546B1A8F02656B15D3B1677D141BCF3584D \tFBA2B18D238AB852DF95745C76157BDF03D0DCD6 \t5C9579B3DB2E506429319AAEF33B071B29559E1E",
                "JETTY_BASE=/opt/jetty-toyota",
                "TMPDIR=/tmp/jetty"
            ],
            "Cmd": [
                "java",
                "-jar",
                "/opt/jetty/start.jar"
            ],
            "ArgsEscaped": true,
            "Image": "dockerdtrtest.toyota-europe.com/toyota/npaqit@sha256:d216922feb0a625e282b50bc2a5582bb6f4336262c45eebb57142eae97d1794a",
            "Volumes": null,
            "WorkingDir": "/opt/jetty-toyota",
            "Entrypoint": [
                "/docker-entrypoint.bash"
            ],
            "OnBuild": null,
            "Labels": {
                "annotation.io.kubernetes.container.hash": "3aae2497",
                "annotation.io.kubernetes.container.restartCount": "0",
                "annotation.io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
                "annotation.io.kubernetes.container.terminationMessagePolicy": "File",
                "annotation.io.kubernetes.pod.terminationGracePeriod": "30",
                "io.kubernetes.container.logpath": "/var/log/pods/2e3e59dd-acf1-11e7-9138-005056800b9d/npaqit-service_0.log",
                "io.kubernetes.container.name": "npaqit-service",
                "io.kubernetes.docker.type": "container",
                "io.kubernetes.pod.name": "npaqit-service-2193241535-8f3x6",
                "io.kubernetes.pod.namespace": "default",
                "io.kubernetes.pod.uid": "2e3e59dd-acf1-11e7-9138-005056800b9d",
                "io.kubernetes.sandbox.id": "8bdcbe05986ac06eff4c70720cd252706acd744b4c6e6e289007abf5d6104e07"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {}
        }
    }
]

What can be the issue

Regards

**Comment by bowei** [comment]
Post your issue to kubernetes stackoverflow. This does not seem to involve kube-dns at all...

**Comment by thockin** [comment]
There's just not enough information here to help.

When you post to SO, please include:
- What environment/cloud
- What network config (native, calico, weave, flannel, etc)
- Where the IPs you use come from
- What version of kubernetes

etc.

At a glance, 150.45.92.41 is not a typical pod IP - that looks like a
public IP, so there's some information missing.

If you're trying to go from a pod to a public IP, check your network
firewalls, and often check your host's iptables MASQUERADE rules (some edge
systems only allow known host IPs out, e.g. Google Cloud).
