### ISSUE TITLE
kube-dns 1.14.7 fails to resolve cluster services with 2 search domains on host's resolv.conf

### ISSUE THREAD

**Issue by tuminoid** [kubernetes/dns#170]
If host does have two `search` domains in `/etc/resolv.conf`, kube-dns fails to resolve cluster services.

I created a single-machine k8s cluster (1.7.4, kube-dns 1.14.7) in a OpenStack VM. This VM has `search localdomain openstacklocal` in `/etc/resolv.conf`.

In this case, kube-dns fails to resolve any cluster service in any namespace, including `kube-dns` itself, unless queried using FQDN, `kube-dns.kube-system.svc.cluster.local`, despite `/etc/resolv.conf` in container pointing correctly to kube-dns, and containing correct `search` options (`kube-system.svc.cluster.local svc.cluster.local cluster.local`).

If either search domain is removed from host, and kube-dns pod recreated, kube-dns starts immediately resolving cluster services correctly.

**Comment by taozhi8833998** [comment]
got the same issue, remove the `localdomain` in search list can fix my problem, but it's strange.
