### ISSUE TITLE
dns设置问题

### ISSUE THREAD

**Issue by xiaosadexiaohai** [kubernetes/dns#175]
情况是这样的:有1个域名外网解析了指到外部ip,然后内部dns也解析指到内部ip,pods ping的时候有时候是外网有时候是内网,没有办法跟宿主机一致,老是跑到外网ip去
宿主机访问的情况下是这样的:
![image](https://user-images.githubusercontent.com/18409309/33474238-b2072e6c-d6b4-11e7-9ccf-dad1d68253ec.png)
容器访问这个域名情况是这样的:
![image](https://user-images.githubusercontent.com/18409309/33474251-c172c96a-d6b4-11e7-9c81-47f3326819b8.png)
环境:
k8s1.8.4
flannel

**Comment by bowei** [comment]
What is your DNS setup? Are you using kube-dns with any modifications/upstream nameservers? What is your host resolv.conf?
