### ISSUE TITLE
when cni use ipvlan plugin, can't work with kube-dns

### ISSUE THREAD

**Issue by woshihaoren** [kubernetes/dns#176]
container use  iptables nat to transfer traffic,when pod use ipvlan ,it can't use node iptables rules.

I think  kube-dns  use hostNetwork:true and scheduling to  specify nodes, let ip unchanged,
whole pods 's /etc/resolv.conf uses these ip.

Is it a good idea? 
Give me some advice.

**Comment by bowei** [comment]
kube-dns does not use host network in the default setup. What is your environment?

Also, your issues sounds like a networking environment issue which is more appropriate for kubernetes/kubernetes. This repository is just the code for the DNS server, but does not contain the k8s cluster addon code.

**Comment by thockin** [comment]
The general observation about ipvlan is true - as long as you rely on the
host's iptables for doing things like Services, you can not use a pass-thru
driver like ipvlan or macvlan.  The good news is that kube-proxy is just
one way to implement Services.  The bad news is that nobody has really
published great alternatives yet.

**Comment by woshihaoren** [comment]
yeah ,  pass-thru dirver can't use Services.. I close it.

**Comment by wanghaibo** [comment]
maybe we can use ipvlan like[ this](https://eng.lyft.com/announcing-cni-ipvlan-vpc-k8s-ipvlan-overlay-free-kubernetes-networking-in-aws-95191201476e) with a Unnumbered point-to-point interface as default route
