### ISSUE TITLE
Kube-dns uses workaround for Prometheus Counters 

### ISSUE THREAD

**Issue by rramkumar1** [kubernetes/dns#177]
In order to stay compatible with Stackdriver API's, #173 made the change to start using Prometheus Counter instead of Gauge for dnsmasq metrics. In order to facilitate this change, some caching logic was introduced in order to ensure that the value set to the Counter was consistent with the way the Gauge set the value.

Once Prometheus provides support within the Counter API to set a value directly, stop using the caching logic introduced in #173.

**Comment by cmluciano** [comment]
@rramkumar1 Do you know of an upstream Prometheus issue that we can link here?

**Comment by rramkumar1** [comment]
@cmluciano As of now, no. However, I believe that @piosz will be working with Prometheus on efforts to converge Stackdriver and Prometheus API's.

**Comment by piosz** [comment]
Are you talking about the effort to standardize metrics format aka [Open Metrics](https://github.com/RichiH/OpenMetrics)? I'm not involved into this, as it requires much smarter guys;)

**Comment by rramkumar1** [comment]
Not really, I was referring to our chat elsewhere that we would talk to the Prometheus folks to see if we can bring convergence between Prometheus and Stackdriver API's so that we don't have to use this workaround.
