### ISSUE TITLE
can kubedns return non-cluster IP (endpoint IP)

### ISSUE THREAD

**Issue by kidiyoor** [kubernetes/dns#180]
Is there a standard way to setup a selector less service (or equivalent) so that kubedns return endpoint IP and not clusterIP.

Usecase bellow - 

If we use kubedns as DNS for istio mesh outside kubernetes. When envoy running in a VM makes a discovery call to pilot **ie** istio-pilot.istio-system.svc.cluster.local, kubedns can(possibly) return IP of VM that runs pilot.

Currently I have a selector less service for pilot and respective endpoint pointing to VM running pilot. But kubedns return cluster IP of the service(which is default behavior) but envoy can't reach pilot via cluster IP it needs VM IP.

More context on what I mean by running istio mesh outside kubernetes - 
Running Kube apiserver (backed with ETCD) standalone in a VM. 
Pointing pilot to talk to apiserver for configuration and service registry(optional).
Workload runs in bare VM. All workload registration in apiserver is via selectorless service and kube endpoints.

**Comment by johnbelamaric** [comment]
Is the clusterIP used for anything? If not can you just use a headless service (i.e., `clusterIP: None`)?

**Comment by kidiyoor** [comment]
Is it possible to create a headless selector less service ? so the DNS would resolve to endpoint IPs not POD IPs ?

**Comment by johnbelamaric** [comment]
Is this what you are looking for?

```
ANN-M-JBELAMARIC:~ jbelamaric$ cat svc.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: mysvc
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
    name: mysvc
subsets:
- addresses:
  - ip: 100.100.100.100
  - ip: 100.100.100.200
  ports:
  - name: http
    port: 80
    protocol: TCP
ANN-M-JBELAMARIC:~ jbelamaric$ kubectl  apply -f svc.yaml
service "mysvc" created
endpoints "mysvc" created
ANN-M-JBELAMARIC:~ jbelamaric$ kubectl run dnstools --image=infoblox/dnstools --restart=Never -it --rm
If you don't see a command prompt, try pressing enter.
dnstools# host mysvc
mysvc.default.svc.cluster.local has address 100.100.100.100
mysvc.default.svc.cluster.local has address 100.100.100.200
dnstools#
```

**Comment by kidiyoor** [comment]
yep. Thats exactly what we need, a 'headless selector less service'  👍 thanks @johnbelamaric
