### ISSUE TITLE
dnsmasq container exists random port

### ISSUE THREAD

**Issue by DaiHao** [kubernetes/dns#182]
In dnsmasq container, it somtime opens a random port on listen , what does it use for?

**Comment by thockin** [comment]
You'll need to provide more information.  When do you see this?  How did you observe it?  What protocol and port number?  What process is attached to that listen?

**Comment by DaiHao** [comment]
**In dnsmasq's FAQ, it explains as follows:**

The high ports that dnsmasq opens are for replies from the upstream
nameserver(s). Queries from dnsmasq to upstream nameservers are sent
from these ports and replies received to them. The reason for doing this is
that most firewall setups block incoming packets _to_ port 53, in order
to stop DNS queries from the outside world. If dnsmasq sent its queries
from port 53 the replies would be _to_ port 53 and get blocked.

This is not a security hole since dnsmasq will only accept replies to that
port: queries are  dropped. The replies must be to oustanding queries
which dnsmasq has forwarded, otherwise they are dropped too.
