### ISSUE TITLE
Spec allows for SRV on headless Services but not on individual hostnames.

### ISSUE THREAD

**Issue by thockin** [kubernetes/dns#184]
From our spec I observe:

We allow A lookups like "pod2.hostnames.default.svc.cluster.local"
* pod.spec.hostname = pod2
* pod.spec.subdomain = hostnames
* pod.namespace = default

We allow SRV lookups like "_http._tcp.hostnames.default.svc.cluster.local"
* service.spec.ports[0].name = http
* service.spec.ports[0].protocol = TCP
* pod.spec.subdomain = hostnames
* pod.namespace = default

We DO NOT allow SRV lookups like "_http._tcp.pod2.hostnames.default.svc.cluster.local" - this was somewhat surprising to me.  It sort of feels like any name we have an A record for, we should allow SRV records for, no?

**Comment by johnbelamaric** [comment]
I don’t know that there needs to be a direct relationship between names with A records and those with SRV records. That is, I don’t know if we want to make that a “rule”.

In this case, where should we get the ports in the SRV for the endpoint? Still from the Service not the pod? And then just return a single A record for the endpoint?

On a related note, one thing I noticed is that while SRVs could allow different ports for each IP, we now tie that to the Service ports not the pod ones, so they must all have the pods using the same ports. Probably not worth changing though; I haven’t seen requests to do it differently. But in theory you could have each pod using a different port number for the snake named port.

On Dec 28, 2017, at 3:06 PM, Tim Hockin <notifications@github.com<mailto:notifications@github.com>> wrote:


We allow A lookups like "pod2.hostnames.default.svc.cluster.local"

  *   pod.spec.hostname = pod2
  *   pod.spec.subdomain = hostnames
  *   pod.namespace = default

We allow SRV lookups like "_http._tcp.hostnames.default.svc.cluster.local"

  *   service.spec.ports[0].name = http
  *   service.spec.ports[0].protocol = TCP
  *   pod.spec.subdomain = hostnames
  *   pod.namespace = default

We DO NOT allow SRV lookups like "_http._tcp.pod2.hostnames.default.svc.cluster.local" - this was somewhat surprising to me. It sort of feels like any name we have an A record for, we should allow SRV records for, no?

**Comment by thockin** [comment]
I think it comes down to what a headless Service is about.  It is a group
of endpoints with no abstraction over them.  But it is rooted in Service,
so service ports seem to make sense.

How would someone use them?  If they do an A lookup, they get a list of
endpoints.  If they do an SRV lookup they get a similar list.

Maybe I am wrong, and the fact that we do support A for individual pods,
but don't support SRV is ok.  It has certainly never come up in practice,
it just seemed like something missing, to me.

Of course, to make that work with short lookups, we might need ndots=6 :)
