### ISSUE TITLE
kube-dns returns NXDOMAIN when not yet synced with apiserver

### ISSUE THREAD

**Issue by thockin** [kubernetes/dns#186]
From https://github.com/kubernetes/kubernetes/issues/57111

**What happened**:
when kube-dns has not yet synced with the apiserver, it return NXDOMAIN for all cluster names

**What you expected to happen**:
It should return SERVFAIL

**Anything else we need to know?**:
NXDOMAIN is the wrong status. It even can be cached by downstream DNS servers.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.4

@bowei @rramkumar1 @johnbelamaric

**Comment by rramkumar1** [comment]
I can't assign myself but I'll go ahead and take care of this

**Comment by johnbelamaric** [comment]
@chrisohaver can you make sure CoreDNS doesn't have this issue?

**Comment by chen-anders** [comment]
any updates on this issue? I saw that https://github.com/skynetservices/skydns/pull/327 was reverted due to non-working Travis CI configuration.

**Comment by rramkumar1** [comment]
@chen-anders I will take another look this week.

**Comment by chen-anders** [comment]
@rramkumar1 Thanks! - I do have a branch that passes CI for what it's worth https://github.com/skynetservices/skydns/pull/335

**Comment by rramkumar1** [comment]
@chen-anders That looks great! Once that get's in, I can vendor skydns and work on the kube-dns changes.

**Comment by chen-anders** [comment]
Any updates on this?
