### ISSUE TITLE
Unreachable Backend after changing backend

### ISSUE THREAD

**Issue by tommyknows** [kubernetes/dns#187]
Hi,
I've got a really weird issue with CoreDNS. I use it as a DNS for the federation, and set it up like described here:
https://github.com/ufcg-lsd/k8s-onpremise-federation#-deploy-coredns
I then created another etcd-backend, with the service-name "etcd-dns-cluster-client.default".
I can execute the following inside one of the containers of the etcd-cluster:
```
/ # etcdctl ls -r
/skydns
/skydns/local
/skydns/local/federation
/skydns/local/federation/svc
/skydns/local/federation/svc/federation
/skydns/local/federation/svc/federation/default
/skydns/local/federation/svc/federation/default/hello-world
/skydns/local/federation/svc/federation/default/hello-world/9502f681
...
```

My Corefile for the DNS server looks like this, after changing it to the new endpoint:
```
.:53 {
    cache 30
    errors stdout
    etcd federation.local., custom.domain. {
      path /skydns
      endpoint http://etcd-dns-cluster-client.default:2379
      debug
    }
    health
    loadbalance round_robin
    prometheus 0.0.0.0:9153
    proxy . /etc/resolv.conf
}
```

And getting a key from the etcd-server works (from inside the CoreDNS Container):
```
/ # wget http://etcd-dns-cluster-client.default:2379/v2/keys/skydns/local/federation/svc/federation/default/hello-world/9502f681
Connecting to etcd-dns-cluster-client.default:2379 (10.109.101.247:2379)
9502f681             100% |*******************************************************************************************************************************************************************************************************************************|   258   0:00:00 ETA
/ # cat 9502f681 
{"action":"get","node":{"key":"/skydns/local/federation/svc/federation/default/hello-world/9502f681","value":"{\"host\":\"192.168.1.129\",\"ttl\":180,\"group\":\"hello-world.default.federation.svc.federation.local.\"}","modifiedIndex":30,"createdIndex":30}}
```

However, when trying to resolve a hostname:
```
# dig -p 32680 @192.168.1.41 hello-world.default.federation.svc.federation.local.

; <<>> DiG 9.10.3-P4-Ubuntu <<>> -p 32680 @192.168.1.41 hello-world.default.federation.svc.federation.local.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 45817
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;hello-world.default.federation.svc.federation.local. IN	A

;; Query time: 0 msec
;; SERVER: 192.168.1.41#32680(192.168.1.41)
;; WHEN: Wed Jan 03 15:20:14 UTC 2018
;; MSG SIZE  rcvd: 8
```

And the logfile of the CoreDNS Container contains the following line (multiple times):
```
03/Jan/2018:15:20:14 +0000 [ERROR 2 hello-world.default.federation.svc.federation.local. A] unreachable backend: no upstream host
```

Some help would be greatly appreciated, as I do not know how to debug this further.

**Comment by miekg** [comment]
Your `etcd` line in your config contains a comma that shouldn't be there.
`etcd federation.local., custom.domain.` -> `etcd federation.local. custom.domain`

And what's resolving the etcd endpoint name? `endpoint http://etcd-dns-cluster-client.default:2379`

**Comment by tommyknows** [comment]
Resolving the etcd endpoint was the kube-dns - which wasn't working correctly as I figured out.
(I don't know why the wget worked, though...)

Now that the Kube-DNS works, I get the error 
```
04/Jan/2018:08:30:03 +0000 [ERROR 2 hello-world.default.federation.svc.sc.sc-admin.federation.local. A] unreachable backend: read udp 10.244.3.186:49912->10.96.0.10:53: i/o timeout
```
I was able to solve this error by removing the comma from the config file and killing the pod. 
Now it's working again. Thanks!

BTW: The error message doesn't really makes sense, does it? Am I missing something why this is an i/o timeout?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [kubernetes/dns] Unreachable Ba..." ]
>Resolving the etcd endpoint was the kube-dns - which wasn't working correctly as I figured out.
>(I don't know why the wget worked, though...)
>
>Now that the Kube-DNS works, I get the error
>```
>04/Jan/2018:08:30:03 +0000 [ERROR 2 hello-world.default.federation.svc.sc.sc-admin.federation.local. A] unreachable backend: read udp 10.244.3.186:49912->10.96.0.10:53: i/o timeout
>```
>I was able to solve this error by removing the comma from the config file and killing the pod.
>Now it's working again. Thanks!
>
>BTW: The error message doesn't really makes sense, does it? Am I missing something why this is an i/o timeout?

I don't know i/o timeout indicates an actuall network timeout. Because of 
federation it is a bit hard to see what's actually being asked (need tcpdump 
prolly), but maybe your upstream really hates commas in domain names and doesn't 
reply?

**Comment by tommyknows** [comment]
Sorry - couldn't test this.
Thus, closing

/close
