### ISSUE TITLE
kube-dns cannot run as non-root user

### ISSUE THREAD

**Issue by diegs** [kubernetes/dns#190]
I attempted to run kube-dns as a non-root user by modifying the example YAML files to:

- have dnsmasq serve on a high port using the `--port` flag
- fix the service to point at the high port
- add a non-root security context to the pod

This seems like it would be sufficient, but then I found that there are several hard-coded assumptions in the container image that dnsmasq will run as root:

https://github.com/kubernetes/dns/blob/master/images/dnsmasq/Dockerfile.cross
https://github.com/kubernetes/dns/blob/master/images/dnsmasq/dnsmasq.conf

Unless there is a strong reason why dnsmasq needs to run as root, I think it would be a better practice to run it as non-root.

**Comment by thockin** [comment]
I would love for it to run as non-root.  cap_net_bind_service might allow
us to not muck with ports, too.

**Comment by thockin** [comment]
@johnbelamaric can CoreDNS run as non-root?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [kubernetes/dns] kube-dns canno..." ]
>@johnbelamaric can CoreDNS run as non-root?

yes:

% ./coredns -dns.port=1043
.:1043
2018/04/29 20:28:15 [INFO] CoreDNS-1.1.2
2018/04/29 20:28:15 [INFO] linux/amd64, go1.10.1, 
CoreDNS-1.1.2
linux/amd64, go1.10.1,

**Comment by johnbelamaric** [comment]
yep, as @miekg said

**Comment by thockin** [comment]
We should give it CAP_NET_BIND and run as non-root by default, perhaps?

**Comment by redbaron** [comment]
@thockin, apparently it requires setcap call on a file: https://github.com/moby/moby/issues/8460

**Comment by johnbelamaric** [comment]
It’s a cluster IP anyway, why not just listen on port 5300 instead and set the targetPort?
