### ISSUE TITLE
Reverse IP lookup of external IPs not working with kube-dns upstreamNameservers

### ISSUE THREAD

**Issue by RochesterinNYC** [kubernetes/dns#198]
**What happened**:

We’re trying to do reverse IP lookups from a GKE container (ex. `dig +short -t PTR x.x.x.x.in-addr.arpa`)  and this doesn’t seem to be working. `kube-dns` is set with `upstreamNameservers` via the `kube-dns` ConfigMap in the `kube-system` namespace.

**What you expected to happen**:

I would expect the reverse IP lookups to be passed along to the specified upstream nameservers similar to regular DNS lookups but it doesn’t seem like this is the case.

From within a running container in k8s:

```
root@debugging-65cb9f5b47-rbf99:/# dig +short -t PTR y.y.y.y.in-addr.arpa
root@debugging-65cb9f5b47-rbf99:/# dig @x.x.x.x +short -t PTR y.y.y.y.in-addr.arpa
hostname.company.net.
```

where `x.x.x.x` is the IP address of one of the `upstreamNameserver`s we set in the `kube-dns` configmap in the `kube-system` namespace (this is on GKE).

**Comment by RochesterinNYC** [comment]
Additionally, issuing the reverse IP lookup directly against kube-dns does not work/return a record:

```
root@debugging-65cb9f5b47-p48sz:/# nslookup 10.63.240.10
Server:		10.63.240.10
Address:	10.63.240.10#53

Non-authoritative answer:
10.240.63.10.in-addr.arpa	name = kube-dns.kube-system.svc.cluster.local.

Authoritative answers can be found from:
root@debugging-65cb9f5b47-p48sz:/# dig @10.63.240.10 +short -t PTR x.x.x.x.in-addr.arpa
root@debugging-65cb9f5b47-p48sz:/# 
```

**Comment by MrHohn** [comment]
> I would expect the reverse IP lookups to be passed along to the specified upstream nameservers similar to regular DNS lookups but it doesn’t seem like this is the case.

It seems current kube-dns implementation doesn't support this case, as we explicitly redirect PTR query to kubedns container (https://github.com/kubernetes/kubernetes/blob/v1.10.0-rc.1/cluster/addons/dns/kube-dns.yaml.base#L170-L171). Even if [a stubdomain is setup](https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configure-stub-domain-and-upstream-dns-servers) for `in-addr.arpa`, it will be overriden by our default config.

This may be fixable if we modify kube-dns in a way such that it will send non-cluster queries to the upstream server (e.g. PTR queries for IPs that are not pod or service IPs). Will explore this idea a bit more.

**Comment by bowei** [comment]
@cc @grayluck

**Comment by grayluck** [comment]
Working on it. PR#220
