### ISSUE TITLE
DNS stops working for addresses outside of the cluster

### ISSUE THREAD

**Issue by dynek** [kubernetes/dns#204]
Hello,

From time to time we have a DNS resolution issue with one of our k8s cluster.
It's isolated to the cluster ifself because the same resolutions work from outside the cluster.
Also, only resolution belonging to outside the cluster is impacted, intra-cluster dns works (services).

We are running k8s 1.5.2 with kubedns 1.9 and dnsmasq 1.14.5.

10.1.0.1 is one of the dns serving dns for the whole company.

When query doesn't work, here the output:
```
/ # dig www.google.ch @10.1.0.1

; <<>> DiG 9.11.2-P1 <<>> www.google.ch @10.1.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 64173
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 7f524c0a6acfe7e1 (echoed)
;; QUESTION SECTION:
;www.google.ch.                 IN      A

;; Query time: 1 msec
;; SERVER: 10.1.0.1#53(10.1.0.1)
;; WHEN: Wed Feb 28 15:17:14 UTC 2018
;; MSG SIZE  rcvd: 54
```
Odd thing is, if I add ```+nocookie``` at the end, I get the expected answer:
```
/ # dig www.google.ch @10.1.0.1 +nocookie

; <<>> DiG 9.11.2-P1 <<>> www.google.ch @10.1.0.1 +nocookie
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51261
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;www.google.ch.                 IN      A

;; ANSWER SECTION:
www.google.ch.          281     IN      A       209.85.202.94

;; Query time: 1 msec
;; SERVER: 10.1.0.1#53(10.1.0.1)
;; WHEN: Wed Feb 28 15:17:38 UTC 2018
;; MSG SIZE  rcvd: 58
```
And here's a query without ```+nocookie``` from a machine outside the cluster:
```
$ dig www.google.ch @10.1.0.1

; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.3 <<>> www.google.ch @10.1.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34675
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;www.google.ch.                 IN      A

;; ANSWER SECTION:
www.google.ch.          267     IN      A       209.85.202.94

;; Query time: 0 msec
;; SERVER: 10.1.0.1#53(10.1.0.1)
;; WHEN: Wed Feb 28 16:17:52 CET 2018
;; MSG SIZE  rcvd: 58
```
Does anyone have a clue?

Thank you!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[kubernetes/dns] DNS stops working ..." ]
>Hello,
>
>From time to time we have a DNS resolution issue with one of our k8s cluster.
>It's isolated to the cluster ifself because the same resolutions work from outside the cluster.
>Also, only resolution belonging to outside the cluster is impacted, intra-cluster dns works (services).
>
>We are running k8s 1.5.2 with kubedns 1.9 and dnsmasq 1.14.5.
>
>10.1.0.1 is one of the dns serving dns for the whole company.
>
>When query doesn't work, here the output:

do you have tcpdump of the query and reply from both within the cluster and 
outside the cluster?

**Comment by dynek** [comment]
I'll reopen this issue if needs be with requested traces because, so far, I am unable to reproduce the problem.
