### ISSUE TITLE
Trying to create a headless-like SRV result from discrete static ClusterIPs

### ISSUE THREAD

**Issue by josdotso** [kubernetes/dns#209]
Hi.

I'm working on making etcdv3 run better in Kubernetes, the results of which should come in a PR to kubernetes/charts. 

Etcdv3 basically requires consistency of IP address.  Although previously hostnames were supported for "peer-urls", this bug was fixed and so IP addresses are again the currency of etcd clustering. 

What I'm looking for is: https://github.com/kubernetes/kubernetes/issues/28969

However, I'm trying to hack together a similar functionality with the intent on making etcdv3 StatefulSet pod IPs consistent across: cluster reboots, kubernetes node addition and subtraction, service removal/addition (think `helm delete --purge` + `helm install`).

I'm thinking that one service per etcd pod, each with static ClusterIP (calculated from starting IP/subnet in helm chart) might do the trick.  However, with this multi-service approach, I believe service discover via SRV records would suffer, provided that would work at all given etcd's SRV expectations: https://coreos.com/etcd/docs/latest/op-guide/clustering.html#dns-discovery

So anyway, the question is: how can I achieve (logically speaking) Sticky IP addresses for these StatefulSet Pods with the above constraints, while generating SRV records as etcd would expect?  One idea I have is to create a boilerplate headless service and use initcontainers to add pod endpoints.

Am I completely lost? lol

**Comment by thockin** [comment]
On Thu, Mar 8, 2018 at 9:58 AM, Joshua Dotson <notifications@github.com> wrote:
>
> Hi.
>
> I'm working on making etcdv3 run better in Kubernetes, the results of which should come in a PR to kubernetes/charts.
>
> Etcdv3 basically requires consistency of IP address. Although previously hostnames were supported for "peer-urls", this bug was fixed and so IP addresses are again the currency of etcd clustering.

You say "bug" and I say "regression".  Assuming static IPs is a pretty
unfriendly design choice, and should be avoided for software built in
the modern era.

> What I'm looking for is: kubernetes/kubernetes#28969
>
> However, I'm trying to hack together a similar functionality with the intent on making etcdv3 StatefulSet pod IPs consistent across: cluster reboots, kubernetes node addition and subtraction, service removal/addition (think helm delete --purge + helm install).

With the exception of the latter, the rest are what Services are for.
The latter seems just wrong, unless you're willing to make dubious
assumptions about availability of IPs.

> I'm thinking that one service per etcd pod, each with static ClusterIP (calculated from starting IP/subnet in helm chart) might do the trick. However, with this multi-service approach, I believe service discover via SRV records would suffer, provided that would work at all given etcd's SRV expectations: https://coreos.com/etcd/docs/latest/op-guide/clustering.html#dns-discovery

Static IPs per pod and SRV seem at odds - one is designed to be
dynamic, and the other is not.

> So anyway, the question is: how can I achieve (logically speaking) Sticky IP addresses for these StatefulSet Pods with the above constraints, while generating SRV records as etcd would expect? One idea I have is to create a boilerplate headless service and use initcontainers to add pod endpoints.

We have no real primitive that adds Services to other DNS records.
You could manually configure it, perhaps?  But it seems like a bad
idea to me.

I just tried it - manually added an "ordinal=" label to each replica
and created a service per pod, then created a headless service with
selector={} and a manual endpoints, pointing to the 3 svc IPs.  That
much seems OK (if a bit odd).  Not sure if the SRV records give you
what you need.

**Comment by jmdots** [comment]
Thanks for your help!  You can close this if you want.  I'll need to study a bit more before deciding next steps
