### ISSUE TITLE
Add an e2e test that goes through dnsmasq -> kubedns -> upstream servers path

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/dns#226]
Ref https://github.com/kubernetes/dns/issues/224, a recent regression was introduced without being caught by any of the tests. The dnsmasq -> kubedns -> upstream servers path is currently a blindspot in test and we should surely include that to prevent future regression.

cc @grayluck

**Comment by grayluck** [comment]
PR created. Please take a look :)
