### ISSUE TITLE
Update miekg/dns up to v1.0.5

### ISSUE THREAD

**Issue by aandryashin** [kubernetes/dns#228]
Please update miekg/dns up to v1.0.5 due this [#642](https://github.com/miekg/dns/pull/642) issue. When resolv.conf contains option attempts kube-dns crashes with panic.

**Comment by MrHohn** [comment]
cc @grayluck

**Comment by grayluck** [comment]
I seems that miekg/dns v1.0.5 depends on golang.org/x/net/internal/socket, which appears only after release-branch.go1.9 of "golang.org/x/net/internal/socket". 
But the current GoVersion in Godeps.json is "GoVersion": "go1.8". 
See if we have to drop support for go version below 1.9.
