### ISSUE TITLE
response for a headless service with no ready endpoints

### ISSUE THREAD

**Issue by chrisohaver** [kubernetes/dns#234]
kube-dns replies with NXDOMAIN, for a headless service that has no ready endpoints.
But the [spec](https://github.com/kubernetes/dns/blob/master/docs/specification.md#241---a-records) says that the response should be NODATA, "because the service exists".

Presumably the spec wrong, since the spec was originally based off of kube-dns behavior at the time.
Or, in this case, is the spec behavior preferred?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[kubernetes/dns] response for a hea..." ]
>kube-dns replies with NXDOMAIN, for a headless service that has no ready endpoints.
>But the [spec](https://github.com/kubernetes/dns/blob/master/docs/specification.md#241---a-records) says that the response should be NODATA, "because the service exists".

I take it 'service exist' means the domain name exist, but there is no rdata; a 
NODATA response is correct in that case.

**Comment by chrisohaver** [comment]
> I take it 'service exist' means the domain name exist...

In the context of the spec, "service exists" only means that there is a headless service defined in kubernetes.  Whether or not the cluster DNS should produce a domain with that service name is the question.

> NODATA response is correct in that case.

On the other hand, for a headless service with no ready endpoints, there is no record at that level, or beneath it.  Which suggests NXDOMAIN is more correct. e.g. 
`headless.default.svc.cluster.local` -> no records at this level
`*. headless.default.svc.cluster.local` -> no records beneath it

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [kubernetes/dns] response for a..." ]
>> I take it 'service exist' means the domain name exist...
>
>In the context of the spec, "service exists" only means that there is a headless service defined in kubernetes.  Whether or not the cluster DNS should produce a domain with that service name is the question.
>
>> NODATA response is correct in that case.
>
>On the other hand, for a headless service with no ready endpoints, there is no record at that level, or beneath it.  Which suggests NXDOMAIN is more correct. e.g.
>`headless.default.svc.cluster.local` -> no records at this level
>`*. headless.default.svc.cluster.local` -> no records beneath it

fair enough, but nodata/nxdomain should matter to a client.

**Comment by chrisohaver** [comment]
> nodata/nxdomain should matter to a client.

Yes (e.g. search path completion), which is why changing the current implementation to match the spec should be taken delicately.  Changing the spec to match the implementation has less disruptive potential.

In concept `NODATA` _would be_ more consistent with the clusterIP service response.  For a clusterIP service, DNS always returns a record with the clusterIP, even if there are no ready endpoints behind it.  But even this behavior is undesirable to some (hence coredns/coredns#1813) - meaning that some users would prefer an `NXDOMAIN` response when a service is effectively dead.

But based on the spec origins, I would lean toward changing the spec to match the current implementation - unless this was an intentional divergence when writing the spec - or a regression since the spec was written.

@johnbelamaric
