### ISSUE TITLE
kube-dns resolution for external domains slow due to external PTR record lookup failure

### ISSUE THREAD

**Issue by sppadic17** [kubernetes/dns#235]
Hi there
  Currently running a 1.7.0 K8 cluster on Ubuntu 16.04 LTS with kube-dns v1.14.10. Seeing issues with slow nslookup responses (avg 7- 10 seconds) within application pods , when going to an external  endpoint which does not have PTR record  assinged to it

Seeing the same behaviour on pods using both dnsPolicy Default as well as for ClusterFirst

pod1 > nslookup xx.yy.zz.com
nslookup: can't resolve '(null)': Name does not resolve

After 6-10 seconds

Name: xx.yy.zz.com
Address1: xx.xxx.xxx.xx

Doing a tcpdump on the docker bridge interface from the VM  where the pod is running shows the following PTR record lookups failing at the end of tcpdump trace, which seem to be cause of the slowness from what best can gather 

Can see a few  repeats of the same message as below for each of the nameservers on the Host resolv.conf  (10.xx being the nameserves listed in the Host resolv.conf)
 
192.168.95.6.36491 > 10.xx.xxx.xxx.domain: [bad udp cksum 0x74a3 -> 0x4fcd!] 22902+ PTR? xx.xxx.xxx.xx.in-addr.arpa. (44)
12:48:17.630267 IP (tos 0x0, ttl 64, id 34551, offset 0, flags [DF], proto UDP (17), length 72)
    192.168.95.6.36491 > 10.xx.xx.xxx.domain: [bad udp cksum 0x74a4 -> 0x4fcc!] 22902+ PTR? xx.xxx.xxx.xx.in-addr.arpa. (44)
10.xx.xx.xxx.domain > 192.168.95.6.59068: [udp sum ok] 10889 ServFail q: PTR? xx.xxx.xxx.xx.in-addr.arpa. 0/0/0 (44)
12:31:13.616369 IP (tos 0x0, ttl 62, id 43144, offset 0, flags [none], proto UDP (17), length 72)

[sppadictest.yaml.txt](https://github.com/kubernetes/dns/files/2017641/sppadictest.yaml.txt)

The kube-dns deployment being used is attached here

Please could you advise if there's an option to disable PTR lookups as a flag or option within kube-dns container args. Have tried a few options with dnsmasq container as well but having no luck so far. Any help would be greatly appreciated

Cheers
Sppadic

**Comment by include** [comment]
same behaviour here.
