### ISSUE TITLE
Set low dnsmasq --neg-ttl instead of --no-negcache

### ISSUE THREAD

**Issue by joekohlsdorf** [kubernetes/dns#239]
The following PR disabled caching of negative responses: https://github.com/kubernetes/kubernetes/pull/53604

I instead propose to have a negative response cache with a very low TTL. In our environment setting just `--neg-ttl=5` reduced the amount of queries to the upstream DNS server by a factor of 10. I think 5-10s is a reasonable tradeoff between speed of service-discovery, performance and cache effectiveness.

Reasoning: Every major cloud provider has a limit for the number of queries to their DNS servers, kube-dns should do as much as possible to reduce the number of queries hitting these. One kube-dns instance could be serving hundreds of containers and none of them are doing DNS caching.
Imagine an application which doesn't have database connection pooling, this leads to a query for every connection attempt to the upstream DNS servers because the resolver will always try to also look up AAAA records which in most cases don't exist. You could argue that the app is broken but traditionally the argument has always been that you should implement DNS caching, in Kubernetes the right place to do this is kube-dns.

I'll follow this issue up with a PR.

**Comment by joekohlsdorf** [comment]
PR is now here: https://github.com/kubernetes/kubernetes/pull/64534

**Comment by attila-lendvai** [comment]
@joekohlsdorf 

IIUC, `--neg-ttl=5` only applies when upstream doesn't send TTL data together with its NXDOMAIN response.

but correct me if i'm wrong! because what i'm looking for is exactly what you describe, but the dnsmasq man page says:

> Negative replies from upstream servers normally contain time-to-live information in SOA records which dnsmasq uses for caching. If the replies from upstream servers omit this information, dnsmasq does not cache the reply. This option gives a default value for time-to-live (in seconds) which dnsmasq uses to cache negative replies even in the absence of an SOA record.

IOW, what we need, i think, is a hypothetical `--max-neg-ttl`.
