### ISSUE TITLE
Resolve external IP addresses

### ISSUE THREAD

**Issue by mat1010** [kubernetes/dns#242]
We'd like to access kube-dns from outside the k8s cluster to use it as discovery service also for services outside of the cluster. We were able to achive this by exposing kube-dns through a dedicated service with an external ip address (which is a zone internal GCP address).

A drawback is that it seems not possible to resolve the external ip of an service through kube-dns.

Would it be feasible to have an additional zone to resolve the external ip address of a service?

**Comment by thockin** [comment]
I don't think this is a kube-dns problem, unless I misunderstand.  You're
adding an IP above and beyond what it understands.  You could add that IP
to GCP's DNS or you could add an empty-selector service with a manual
endpoint to "trick" kube-dns into serving something...

**Comment by johnbelamaric** [comment]
That would work. However, this has also come up in CoreDNS as a feature request on several occasions:

https://github.com/coredns/coredns/issues/1851

https://github.com/coredns/coredns/issues/839


I think there are some issues to sort out here. How should we handled adding features like this to CoreDNS vs. extending the standard K8s DNS schema? As CoreDNS becomes a GA option in 1.11, what kind of constraints (if any) do we put on it from a cluster compliance point of view?

Today we already support a few options that are not following the exact schema, if you veer off of the standard default configuration.

John


On Jun 5, 2018, at 11:08 AM, Tim Hockin <notifications@github.com<mailto:notifications@github.com>> wrote:

I don't think this is a kube-dns problem, unless I misunderstand. You're
adding an IP above and beyond what it understands. You could add that IP
to GCP's DNS or you could add an empty-selector service with a manual
endpoint to "trick" kube-dns into serving something...

**Comment by mat1010** [comment]
> I don't think this is a kube-dns problem, unless I misunderstand.  You're adding an IP above and beyond what it understands.

The external ip address, which will be requested by k8s from GCP, is known to k8s at some point after it has been assigned by GCP - right? So from my rough understanding it should be possible to "just" create an additional A record with the same name, but within a different zone, which holds this external address. Of course kube-dns might just hold this information and might not be the place where the information about the external ip addresses of services is gathered to create those records. 
I'm not that into detail about the whole API call flow of who is doing which call at which point to which API, so please correct my if I'm wrong with my assumptions about the whole process of adding a record to kube-dns.

> You could add that IP to GCP's DNS or you could add an empty-selector service with a manual endpoint to "trick" kube-dns into serving something...

This might work but I would like to avoid to have to manually create a  service after the address has been assigned to my service. This should be automated in the same way as the cluster ips are automatically added as A records to kube-dns.

As @johnbelamaric noted: coredns/coredns#1851 is exactly my usecase.

**Comment by thockin** [comment]
The problem is that if we make kube-dns start serving a second zone, the
user has to make that zone's NS records point to kube-DNS.

I'm not against that sort of idea, but it's a net new surface to consider -
not just a tiny extension. :)

**Comment by mat1010** [comment]
> I'm not against that sort of idea, but it's a net new surface to consider - not just a tiny extension.

Thanks for pointing this out. At least that verifies that this feature is not there right now, so I don't have to search any deeper for a hidden / undocumented implementation. As an interim solution we might go for the empty-selector service to still make use of the already available kubernetes services.
