### ISSUE TITLE
x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate

### ISSUE THREAD

**Issue by geosword** [kubernetes/dns#244]
This is happening on version 1.14.8 and potentially others.

Its running in a container, specifically gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.8 as part of a kubernetes cluster.
I have a self signed certificate on the apiserver, which understandably throws the usual verification errors if accessed with curl (from the command line of anything), without -k. The output from kube-dns however seems to imply that -k is used, although I can find no evidence of curl actually existing on the container, which leads me to believe that the binary curl is not actually being called, but the curl command is just being output to "help". The existence of toCurl in round_trippers.go seems to back this theory up.

The problem I am facing is this error message:

```
I0610 06:47:06.051414       1 round_trippers.go:398] curl -k -v -XGET  -H "User-Agent: kube-dns/1.14.10 (linux/amd64)" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6Ikp... rest of barer token" -H "Accept: application/vnd.kubernetes.protobuf, */*" https://172.17.0.1:443/api/v1/services?resourceVersion=0
`E0610 06:47:05.058513       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:189: Failed to list *v1.Endpoints: Get https://172.17.0.1:443/api/v1/endpoints?resourceVersion=0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "10.16.23.40")`
```
10.16.23.40 is the "real" address of my master, 172.17.0.1 is the service address of the master.

Yes, the certificate is self-signed, and therefore "signed by an unknown authority" but if its making the call with -k (or whatever its equivalent is within the code) Then that should not be an issue. 

I have attached the output of openssh x509 on the certificate served by 172.17.0.1 / 10.16.23.40 for review. Please let me know if you need more information. 

How can I get around this problem? Thanks in advance.

Dylan
[certinfo.txt](https://github.com/kubernetes/dns/files/2087616/certinfo.txt)

**Comment by MrHohn** [comment]
This isn't really a kube-dns issue. But one thought is maybe checking the mounted `/run/secrets/kubernetes.io/serviceaccount/ca.crt` in kube-dns pod to see if that matches the cert you use for apiserver.
