### ISSUE TITLE
How make all this ??

### ISSUE THREAD

**Issue by Grigsuv** [kubernetes/dns#249]
I need some docs,guide on how to build/create or smt else,I need internal dns addresses,In repo I can't find full info

**Comment by chrisohaver** [comment]
Does `make build` work?

**Comment by Grigsuv** [comment]
And how it must works on kubernetes cluster  if i build it local?

**Comment by chrisohaver** [comment]
You'll need to update your kube-dns deployment to point to the image.

What's your bigger goal here?  To use a custom build of kube-dns?  Have you made local changes and what to use your own custom version?  If so, what changes have you made?

**Comment by Grigsuv** [comment]
My goal is have internal dns addresses for pods on AKS,Just latest  working version.I find out tabout his repo but can't find information about deployment.Can you help me?

**Comment by chrisohaver** [comment]
That function should be part of AKS.  You should not be required to build and deploy kube-dns manually.

**Comment by Grigsuv** [comment]
Where can I get  dns information about pod/service?There are only ip addresses.How deploy it manually?

**Comment by chrisohaver** [comment]
You should be able to make a dns request, _from a pod_ for the service using the service name and namespace.  For example:  `dig myservice.mynamespace.svc.cluster.local.` where _myservice_ and _mynamespace_, are the service name and namespace name that the service is in.

**Comment by chrisohaver** [comment]
Here are more docs, from kubernetes: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by Grigsuv** [comment]
Thank you!

**Comment by Grigsuv** [comment]
Can you tell me more about what can I change in kube-dns?

**Comment by Grigsuv** [comment]
Can it be smt like serviceName.servicNamespace or smt like real address(github.com,google.com) ?

**Comment by chrisohaver** [comment]
> Can you tell me more about what can I change in kube-dns?

You can configure stub zones and upstream servers in a kube-dns configmap.
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/

CoreDNS, a kubernetes approved alternative to kube-dns, is much more configurable/flexible.

> Can it be smt like serviceName.servicNamespace or smt like real address(github.com,google.com)?

Both should work.  For the latter, kube-dns will forward them to upstream resolvers.

**Comment by chrisohaver** [comment]
This is a good link for troubleshooting that sort of thing... 
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-application/

**Comment by Grigsuv** [comment]
Pod id working correctly,getting response from pod's ip,app port and container name is the same..,Ok thank you,you helped me a lot
