### ISSUE TITLE
querying service wont show pods 

### ISSUE THREAD

**Issue by gabrielfsousa** [kubernetes/dns#252]
kubernetes version 1.11.0

shouldn't the query return the pods ?

```
[root@app197 gabriel]$ dig @10.96.0.10  -t SRV _vaultport._tcp.vault.vault.svc.cluster.local

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7 <<>> @10.96.0.10 -t SRV _vaultport._tcp.vault.vault.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60739
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_vaultport._tcp.vault.vault.svc.cluster.local. IN SRV

;; ANSWER SECTION:
_vaultport._tcp.vault.vault.svc.cluster.local. 5 IN SRV 0 100 8200 vault.vault.svc.cluster.local.

;; ADDITIONAL SECTION:
vault.vault.svc.cluster.local. 5 IN     A       10.107.214.96

;; Query time: 0 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Fri Aug 10 13:34:26 CEST 2018
;; MSG SIZE  rcvd: 213
```

**Comment by chrisohaver** [comment]
You'll see IPs of pods in the response if the service is a _headless_ service.  But for a normal service with a ClusterIP, you just see the service IP here.

**Comment by gabrielfsousa** [comment]
ok, thanks.
any disadvantages using a  headless service ?

**Comment by chrisohaver** [comment]
> any disadvantages using a headless service ?

You don't get k8s based load balancing.  But you should be able to use the `loadbalance` plugin in coredns to randomly order responses.

Without changing the service to headless, you can also do the following...

`dig @10.96.0.10  -t SRV *.vault.vault.svc.cluster.local` => will return list of open ports on all endpoints (aka pods) of `vault.vault.svc.cluster.local`

`dig @10.96.0.10 *.vault.vault.svc.cluster.local` => does the same, but as an `A` request, so just lists the pods (not open ports as you get with the `SRV` request)

**Comment by thockin** [comment]
The main disadvantage is that your clients are not protected from pods
changing, so they might get an IP that stops working if the pod is deleted
(scale down, rolling update, etc)
