### ISSUE TITLE
Kube-DNS service seems to keep sending traffic to a terminating/ed pod

### ISSUE THREAD

**Issue by mmingorance-dh** [kubernetes/dns#277]
Hi all,
I have a question about a certain issue we are facing.
We have recently change to Kubernetes 1.10.6 with kops 1.10 and we started to use IPVS instead of IPtables. We have created our own AMI for this purpose. Everything seems to be working fine with this setup however we experience some issues in the kube-dns issue (managed by kube-dns instead of coreDNS).
Whenever a kube-dns pod gets terminated, the service seems to still be sending traffic to this pod and therefore we start to have resolution's issues in our cluster. This resolution issue happens for exactly 5 minutes right after the pod starts to be deleted.

Do you have any idea why the service is still sending this traffic even though the pod is terminating? As far as I know, the service should immediately disrupt the connection with this pod.

**Comment by thockin** [comment]
@m1093782566 Seems IPVS related?

**Comment by mmingorance-dh** [comment]
If it was IPVS related I should be able to see the same behaviour in the rest of the services and this is not the case. We noticed this issue only on kube-dns

**Comment by thockin** [comment]
And you're accessing it via the service IP, right?

The backends (kubedns) is well after the decision of which backend
instance to route to.  That's done at IPVS.  And for comparison, we
know iptables kube-proxy does not suffer this (at least we test it,
and nobody has reported it broken).

More likely there's something not being flushed (e.g. conntrack for
UDP, which is notoriously finicky) when the backend set changes (we
had this bug in iptables mode).

**Comment by mmingorance-dh** [comment]
Yes, we are using the service's IP.

If this is the case and IPVS is producing these errors by not cutting off the connection efficiently when a pod is terminating... is there any possible workaround we could try or implement for it?

Is anybody already aware of this issue and working on it?

Thanks!

**Comment by m1093782566** [comment]
IPVS proxy already supported graceful termination since v1.12.2

**Comment by mmingorance-dh** [comment]
We can't upgrade to Kubernetes 1.12 unfortunately. We run our clusters managed by Kops and this one only supports up to 1.10.X currently.

Any other alternative?

**Comment by m1093782566** [comment]
@mmingorance-dh 

I would strongly upgrade to v1.13 as we fixed IPVS UDP graceful termination in Kubernetes v1.13. Please check #71515.

**Comment by mmingorance-dh** [comment]
@m1093782566 thanks for the advice.

Indeed it's the only solution. We can't upgrade to Kubernetes 1.13 at the moment because Kops does not support this version yet but we will look into how to get to this version as soon as possible.

Thanks everyone for your help

**Comment by bowei** [comment]
Closing issue, this does not seem relevant to kube-dns.
