### ISSUE TITLE
kube-dns pod crashing with panic error

### ISSUE THREAD

**Issue by thebag25** [kubernetes/dns#283]
Hi all.
I got follow problem - after i restart kubernetes server I got error with kube-dns - it stops with CrashLoopback error. I check container logs and found that kubedns container itself crashig with panic error. Look like this is happened when it got first dns request - I try to disable sidecar and dnsmasq containers and kubedns itself run OK. But when it get any DNS request- it crashed with  panic. Everything worked fine before restart.

Kube DSN 1.14.7 and 1.14.10, kubernetes 1.9.2 on RedHat 7.5

I1226 13:11:22.640901 1 server.go:119] Status HTTP port 8081
I1226 13:11:23.256656 1 dns.go:436] No service for endpoint "kube-scheduler" in namespace "kube-system"
I1226 13:11:23.256675 1 dns.go:436] No service for endpoint "kube-scheduler" in namespace "kube-system"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9b74b3]

goroutine 130 [running]:
k8s.io/dns/vendor/github.com/skynetservices/skydns/server.(*server).ServeDNS(0xc420019dc0, 0x1fd63a0, 0xc4202bc000, 0xc4200903f0)
/go/src/k8s.io/dns/vendor/github.com/skynetservices/skydns/server/server.go:202 +0x293
k8s.io/dns/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS(0xc420444010, 0x1fd63a0, 0xc4202bc000, 0xc4200903f0)
/go/src/k8s.io/dns/vendor/github.com/miekg/dns/server.go:210 +0x65
k8s.io/dns/vendor/github.com/miekg/dns.(*Server).serve(0xc420656000, 0x1fc6260, 0xc42023e1b0, 0x1fbb6e0, 0xc420444010, 0xc4200fac00, 0x36, 0x200, 0xc4206ca000, 0xc4204f61c0, ...)
/go/src/k8s.io/dns/vendor/github.com/miekg/dns/server.go:577 +0x2fb
created by k8s.io/dns/vendor/github.com/miekg/dns.(*Server).serveUDP
/go/src/k8s.io/dns/vendor/github.com/miekg/dns/server.go:531 +0x2d5_

**Comment by MrHohn** [comment]
Ref the panic line:
https://github.com/kubernetes/dns/blob/5900070ee13547517a0b6c5d9ac70d6fda9e7733/vendor/github.com/skynetservices/skydns/server/server.go#L202

where `stub` is: 
https://github.com/kubernetes/dns/blob/9bd4bd4450eceb73cdd6a86abb481bd9058145e6/vendor/github.com/skynetservices/skydns/server/config.go#L78-L80

`stub` is set at the very end of the `SetDefaults` func. And seems like we don't check error when calling that:
https://github.com/kubernetes/dns/blob/c85a61ffaa3dfe2d237f2a141d279a08a5237ab6/cmd/kube-dns/app/server.go#L170-L175

So possibly `SetDefaults` hits an error before actually setting the `stub` field in your case, kubedns continues regardless, and it panics when a DNS request comes.

**Comment by MrHohn** [comment]
The only place I can find in `SetDefaults` that can return an error earlier is:
https://github.com/kubernetes/dns/blob/9bd4bd4450eceb73cdd6a86abb481bd9058145e6/vendor/github.com/skynetservices/skydns/server/config.go#L121-L126

**Comment by MrHohn** [comment]
@thebag25 will you able to check if there is anything abnormal in the `/etc/resolv.conf` file on your machine? Or are you open to build and deploy a latest version kube-dns so that the actual error would be logged?

**Comment by thebag25** [comment]
Hi,
Ok. I will check it and back with results...

**Comment by thebag25** [comment]
I check resolv.conf file and found interesting thing: in my DNS yaml file run user set as 1999. 
securityContext:
runAsUser: 1999

But /etc/resolv.conf access set as 
-rw-r--- root root /etc/rosolv.conf

After I comment out runAsUser pod is started !

**Comment by MrHohn** [comment]
@thebag25 Great that you found and fixed the issue. Given that, closing this issue.
