### ISSUE TITLE
Spec: Update the spec for federation

### ISSUE THREAD

**Issue by johnbelamaric** [kubernetes/dns#29]
The current spec covers only a single cluster. It needs to be updated to reflect federation records and behavior.

**Comment by thockin** [comment]
The federation records need to be totally revamped - last I looked at them they were ambiguous.  @csbell  @madhusudancs

**Comment by csbell** [comment]
@thockin The best reference outside of code that I could find is located [here](https://github.com/kubernetes/kubernetes/pull/25107#issuecomment-218026648). By revamp, do you mean merging the current federation behavior into the spec here or is there more involved?

**Comment by thockin** [comment]
Welcome to the real guts of the project :)

From that doc:  `mysvc.myns.myfed.svc.u7s.io` is proposed as an example.
This is ambiguous.  It could just as likely mean a pod "mysvc" ins a
stateful set "myns" in namespace "myfed".  The hope waas that the extra
token was enough to disambiguate but it's not.  This snuck in without me
catching it, and now we need to find a way to fix it.

We proposed something like `mysvc.myns.myfed.fed.u7s.io` as an alternative,
but we need a plan to migrate people.  Madhu might recall more details.

@bowei

**Comment by bowei** [comment]
Given federation is still in its early stages, it would be great to get ahead of this issue

**Comment by madhusudancs** [comment]
Oh wow! Did not know about the existence of this repo and was hence missing the notifications. 

> We proposed something like `mysvc.myns.myfed.fed.u7s.io` as an alternative,
> but we need a plan to migrate people. Madhu might recall more details.

This and in addition we had the literal `svc` somewhere in there. IIRC. Something like `mysvc.myns.svc.myfed.fed`. We still need to come up with a concrete migration plan.

There is also this doc that Quinton wrote - https://docs.google.com/document/d/1tSTgqSy7iR8cQx2z-bbqaYVITrraDQmV_aE43PuRPoI/edit#heading=h.ys8jzm2jzab9

**Comment by nikhiljindal** [comment]
Also ref https://github.com/kubernetes/kubernetes/issues/27969

> We proposed something like `mysvc.myns.myfed.fed.u7s.io` as an alternative,

We had also discussed supporting DNS names for ingress. So `fsvc` and `fing` should be better than `fed`.
Also, with that proposal, we will need more than 6 dots for stateful sets (extra dot for federation name). Is that acceptable?


> Given federation is still in its early stages, it would be great to get ahead of this issue

+1.

**Comment by bowei** [comment]
@nikhiljindal One thing to keep in mind, increases in ndots can have a dramatic impact on performance.

When a name has fewer dots than ndots, external names result in 10 DNS lookups/name. Modulo negative caching, this can easily result in DNS server meltdown.
