### ISSUE TITLE
node-local-dns crashes on failing to obtain iptables access

### ISSUE THREAD

**Issue by JaveriaK** [kubernetes/dns#292]
The upstream node-local-dns implementation (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns) version `k8s.gcr.io/k8s-dns-node-cache:1.15.0` crashes frequently when used in a setup that has another application that also modifies iptables rules. 

I see this in my 1.10 cluster using weave-net cni that also runs on hostNetwork. Details of my setup are below:

```
$ weave version: 2.5.0 / 2.5.1

$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:09:56 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:09:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ uname -a
Linux ip-172-31-42-248 4.4.121-k8s #1 SMP Sun Mar 11 19:39:47 UTC 2018 x86_64 GNU/Linux

$ kubectl version
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
With @prameshj 's help, we were able to see that when the nodelocaldns pod has issues with obtaining access to iptables it gives up too quickly with a locking error and then crashes:

```Failed to add back non-existent rule {raw PREROUTING [-p tcp -d 169.254.20.10 --dport 53 -j NOTRACK]} - error checking rule: exit status 4: Another app is currently holding the xtables lock. Stopped waiting after 2s.```

**Comment by dkowsley** [comment]
I am also seeing this in 1.15.1
