### ISSUE TITLE
This repo should not require 'strict' status contexts.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/dns#293]
This repo currently has strict status context requirements enabled: https://github.com/kubernetes/test-infra/blob/b6737faf9879cba0aed01b782057aee47ad2664c/prow/config.yaml#L120

The `strict` setting corresponds to "Require branches to be up to date before merging" below:
![image](https://user-images.githubusercontent.com/5334145/54947756-4fd92e80-4ef8-11e9-8f94-d882c6a2a58a.png)

This setting requires that PR branches be rebased off the latest base branch commit meaning that if multiple PRs are open and one merges, other PRs must always rebase before merging. This is a simplistic method that GitHub provides for ensuring that PRs are tested against the most recent base branch commit before merging.

Tide uses a strictly superior method to provide the same guarantees without requiring PRs to be rebased whenever something else merges. This is possible because ProwJobs don't run on the PR head commits, they run on the merge commits and the base branch commit used in the merge is recorded. Tide can use this information to ensure that PRs are tested against the most recent changes without requiring PRs to be rebased unless there is an actual merge conflict.

Enabling the `strict` context requirements in a repo managed by Tide forces PR authors to rebase their PRs whenever something else merges even though this provides no benefit at all. Additionally, it is causing Tide to get stuck trying to merge some PRs because Tide doesn't know how to properly handle this merge requirement (since it doesn't makes sense to ever use this requirement with Tide).

Please remove this `strict: true` configuration ASAP:
https://github.com/kubernetes/test-infra/blob/b6737faf9879cba0aed01b782057aee47ad2664c/prow/config.yaml#L120

**Comment by MrHohn** [comment]
cjwagner@ Thanks for your detailed explanation. I've sent https://github.com/kubernetes/test-infra/pull/11928 for this.

**Comment by MrHohn** [comment]
Closing as kubernetes/test-infra#11928 is merged.
