### ISSUE TITLE
kubedns metrics abnormal

### ISSUE THREAD

**Issue by pulord** [kubernetes/dns#298]
I scraped some metrics from port 10055，but i find that
skydns_skydns_dns_request_count_total always < skydns_skydns_dns_request_count_total ?

**Comment by hipyhop** [comment]
Did you mean to list a different metric is always less than `skydns_skydns_dns_request_count_total`?

**Comment by pulord** [comment]
> Did you mean to say a different metric is always less than `skydns_skydns_dns_request_count_total`?

sorry！clerical error
i mean that skydns_skydns_dns_request_count_total always < skydns_skydns_dns_error_count_total ?

for my opinion,  reqeust_count_total should contains error_count_total, so reqeust_count_total must greater than error_count_total

**Comment by yuzhiquan** [comment]
/remove-lifecycle rotten
/reopen
So what is the reason?Cann't find any code about these metrics...

**Comment by prameshj** [comment]
Will need to look into this.. I know that skydns library treats NXDOMAINs also as error, that would explain skydns_skydns_dns_error_count_total being equal to skydns_skydns_dns_request_count_total, but not greater. Are we seeing this in a live cluster?

**Comment by yuzhiquan** [comment]
The skydns_skydns_dns_error_count_total larger than skydns_skydns_dns_request_count_total ,because one domain with less '.' may be searched for  many times, if ndots config set to 5.
