### ISSUE TITLE
Safely updating nodelocaldns image tag

### ISSUE THREAD

**Issue by rgembalik** [kubernetes/dns#310]
I keep seeing `nodelocaldns` restarts on more loaded nodes. The last message usually reads something like `2019-06-18T14:14:57.749Z [FATAL] Failed to add back non-existent rule {raw PREROUTING [-p tcp -d 169.254.25.10 --dport 53 -j NOTRACK]}`. I see similarities with the issue: https://github.com/kubernetes/dns/issues/292

I do have `k8s.gcr.io/k8s-dns-node-cache:1.15.1` and calico alongisde, so symptoms do match in my opinion. 

Now the question is: can I safely `kubectl edit ds nodelocaldns` and replace image tag with one up? Is there any other recommended way of updating `nodelocaldns`? 

The nodes are set up with `kubespray` and I do know, that there is `nodelocaldns` yaml in `/etc/kubernetes` on the master node, but I have no Idea if it changes anything. 

Currently, I am sitting on kubernetes 1.14.1 and calico 3.4.0.

**Comment by bowei** [comment]
@prameshj

**Comment by prameshj** [comment]
You can edit the nodelocaldns yaml in the master node "/etc/kubernetes/addons..." directly and change the image there. Editing via `kubectl edit ds` will temporarily update and will be reconciled.
There will be dns downtime as nodelocaldns pods on each node terminate and restart. When i had measured on my test setup, this was around 20 seconds. If this is an issue, the recommendation is to use [custom DNS config ](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-config) on those pods to directly talk to kube-dns service while nodelocaldns is updating.

**Comment by rgembalik** [comment]
@prameshj Thank you for the answer. Actually, the yaml is directly in `/etc/kubernetes/` (`/etc/kubernetes/nodelocaldns-daemonset.yml`), but I doubt it changes much. 

Is it worth to go for any specific version? or should I go for `1.15.2` just to be safe?

**Comment by prameshj** [comment]
1.15.2 is fine. 1.15.3 has some changes that let you configure multiple listen ip addresses, skip iptables setup. 
https://github.com/kubernetes/dns/releases/tag/1.15.3
If you don't need those, you can stick to 1.15.2.

**Comment by rgembalik** [comment]
@prameshj I jumped to 1.15.3 - no reason to hold on if the changes are minor. The update went well, so I'll close the ticket. Will reopen if I see anything suspicious after updating.

**Comment by prameshj** [comment]
thank you for the update!

**Comment by prameshj** [comment]
By any chance, did you measure how long the dns downtime was?

**Comment by rgembalik** [comment]
@prameshj I didn't, sorry. It took less than 30s per node (so your description of 20s is pretty much accurate), and ContainerCreating was by far the most time consuming (I assume it's because image downloading).
