### ISSUE TITLE
Domain Name Resolution will be reported occasionally:UnknownHostException

### ISSUE THREAD

**Issue by zkf1987** [kubernetes/dns#312]
Cluster size: 100 nodes
Number of services: 1300
POD: 4000
The DUBBO framework is used.
Question: KUBE-DNS runs for a period of time, and DNS domain name resolution fails. As follows:UnknownHostException

**Comment by bowei** [comment]
Need more information. What is the QPS rate, how many instances of kube-dns, what is the resource allocated to dns etc.
