### ISSUE TITLE
amd64 binaries in arm64 images

### ISSUE THREAD

**Issue by tyuio1** [kubernetes/dns#314]
I tried to deploy `k8s.gcr.io/k8s-dns-node-cache-arm64:1.15.4` on an arm64 device (Odroid C2) but it ended in a crashloop. It always happened when `sbin/xtables-multi` was called (iptables).

I exported the image filesystem and used `file` on the binaries:
```
$ docker create --name nodecache-1.15.4 k8s.gcr.io/k8s-dns-node-cache-arm64:1.15.4
$ docker export nodecache-1.15.4 | tar x
$ file node-cache
node-cache: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, not stripped
$ file sbin/xtables-multi
sbin/xtables-multi: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=a774205ce47d45ce8fd1872c1204baba1808798a, stripped
```

As you can see the node-cache binary is aarch64, which it should be, but `sbin/xtables-multi` is x86-64, which I suspect is the reason it doesn't work on arm64.

This also applies to other binaries in the image, I guess it's because the wrong base image is being used?

**Comment by MrHohn** [comment]
Seems like we hardcoded the base image  to amd64 at the moment.
https://github.com/kubernetes/dns/blob/468d4e407089a0999d9417f44165487d49ba2f6c/Dockerfile.node-cache#L15

/kind bug
/assign @prameshj

**Comment by BiG86** [comment]
When do you plan to rebuild and push the images k8s.gcr.io/k8s-dns-node-cache-arm64:1.15.* ?

**Comment by prameshj** [comment]
We will be pushing a new tag and the images in a day or two.

**Comment by prameshj** [comment]
Images available now - k8s.gcr.io/k8s-dns-node-cache:1.15.5
