### ISSUE TITLE
Add support for AAAA records in dns specification

### ISSUE THREAD

**Issue by sftim** [kubernetes/dns#315]
[DNS specification 1.0.1](https://github.com/kubernetes/dns/blob/cf7588d7932db067f376c5903e8b21fca769a4ba/docs/specification.md) covers IPv4 via A records, and does not mention IPv6 support via AAAA records.

As a feature request, add details to the specification that explain how to use DNS service discovery with IPv6.

**Comment by bowei** [comment]
Would be great to link this from the IPv6 KEPs/todo list.

**Comment by aojea** [comment]
I thought that KubeDNS was deprecated and replaced by CoreDNS, that has support for AAAA records since https://github.com/kubernetes/kubernetes/pull/44403

**Comment by chrisohaver** [comment]
This issue refers to updating the k8s cluster dns spec itself, which does not currently mention AAAA records.

The update could be as simple as replacing `A` with `A/AAAA`, in the document.

**Comment by bowei** [comment]
cc: @lachie83 
Is this tracked on the IPv6 work?

**Comment by lachie83** [comment]
Investigating

**Comment by aojea** [comment]
@bowei @lachie83 I can take this and submit a PR to modify the DNS specification for IPv6
/assign

**Comment by lachie83** [comment]
Thanks @aojea
