### ISSUE TITLE
hostNetwork:True deployments can't resolve services by name

### ISSUE THREAD

**Issue by staticdev** [kubernetes/dns#316]
I am using kubernetes 1.15.0 along with calico 3.8 on a single-node kubeadm. I realized all my pods that uses `hostNetwork: True` can't resolve DNS using servicename.

Steps to reproduce:
I have 1 running service `servicename` as seen in `kubectl get svc`:

> NAME                                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
> servicename                                            ClusterIP   10.110.140.125   <none>        5000/TCP         3d

I have 2 deployments using base image python:3.6.8-alpine deployment1 without hostnetwork and deployment2 with hostnetwork.

I get pods from both of them and exec commands from each one with `kubectl exec -it podname sh`. Then I try the command: `nslookup servicename`.

From deployment1 I get:
```
nslookup: can't resolve '(null)': Name does not resolve

Name:      servicename
Address 1: 10.110.140.125 servicename.default.svc.cluster.local
```

From deployment2 I get:
```
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'servicename': Name does not resolve
```

**Comment by johnbelamaric** [comment]
You have to use dnsPolicy `ClusterFirstWithHostNet`:

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

/close
