### ISSUE TITLE
A plan of the component  which  supports HA for  NodeLocal DNSCache 

### ISSUE THREAD

**Issue by carterzhao** [kubernetes/dns#324]
[The enablement of HA for NodeLocal DNSCache ](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190424-NodeLocalDNS-beta-proposal.md) has given a solution of HA for node cache.  But some component is needed to dynamically determine when to use node-local-dns and when to flip to kube-dns endpoints. It  can be a  Daemonset  which managers the iptables NOTRACK rule to implement the "USE LOCAL?" .   I just want to know there are some plans of developing the component?  Looking forward to your reply！！

**Comment by prameshj** [comment]
The [alternatives](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190424-NodeLocalDNS-beta-proposal.md#alternatives) in that KEP, list the option to run 2 daemonsets with SO_REUSEPORT and use the same linklocal ip for both cache instances. that should work in IPVS mode too.

**Comment by carter-zhao** [comment]
@prameshj  Do you  mean that   running 2  daemonsets with SO_REUSEPORT  to realize HA  ？

**Comment by prameshj** [comment]
Yes

**Comment by prameshj** [comment]
/remove-lifecycle stale

I just realised that the initial ask is not about supporting IPVS. Regarding providing a component to switch between kube/CoreDNS and NodeLocalDNS, this was left as user's choice. Are you looking for some sample scripts/pod image for a component that will perform this check?

**Comment by bplotnick** [comment]
@prameshj This is necessary for us too. A sample script/pod image would be really helpful. But this would still cause drops during the time that it takes to detect the failure.

Running multiple instances with SO_REUSEPORT would _also_ be necessary to handle single pod failures without drops (technically DNS requests in flight for the failed pod would be dropped).

We also need to have a strategy for upgrading. With SO_REUSEPORT, we could do a graceful upgrade by having the old pod stop `recv`ing new DNS queries but still sending responses for any outstanding queries. This makes some assumptions about how the kernel handles UDP traffic with SO_REUSEPORT, which i'm not sure about.

This would have to be slightly adjusted for the TCP case. For TCP, the approach would have to be to close the listening socket first and then shut down after the grace period. There is still a chance for drops due to a [race condition](https://engineeringblog.yelp.com/2015/04/true-zero-downtime-haproxy-reloads.html) in the kernel, but solving is probably out of scope given that DNS over TCP is relatively rare compared to UDP.

**Comment by carter-zhao** [comment]
@prameshj   Currently we choose to use the proposal which uses dnsmasq as local dns.   The nameservers in the reslov.conf include local node ip and coredns cluster ip.

**Comment by prameshj** [comment]
> @prameshj This is necessary for us too. A sample script/pod image would be really helpful. But this would still cause drops during the time that it takes to detect the failure.
> 
> Running multiple instances with SO_REUSEPORT would _also_ be necessary to handle single pod failures without drops (technically DNS requests in flight for the failed pod would be dropped).
> 
> We also need to have a strategy for upgrading. With SO_REUSEPORT, we could do a graceful upgrade by having the old pod stop `recv`ing new DNS queries but still sending responses for any outstanding queries. This makes some assumptions about how the kernel handles UDP traffic with SO_REUSEPORT, which i'm not sure about.
> 
> This would have to be slightly adjusted for the TCP case. For TCP, the approach would have to be to close the listening socket first and then shut down after the grace period. There is still a chance for drops due to a [race condition](https://engineeringblog.yelp.com/2015/04/true-zero-downtime-haproxy-reloads.html) in the kernel, but solving is probably out of scope given that DNS over TCP is relatively rare compared to UDP.

You are right about there being drops while the pod performing checks detects nodelocaldns failure and flips to use CoreDNS/ClusterDNS. For example, performing a dns probe every second and setting a threshold of 5 continuous DNS failures and flipping to ClusterDNS can have a downtime of upto 5s, if nodelocaldns pod is actually not answering queries. Also frequently switching between nodelocaldns and ClusterDNS isn't great either. One concrete example I can see where nodelocaldns pod would be unresponsive, is if it got OOMKilled, in which case it would come back up in a few seconds. Any scenario where you foresee nodelocaldns to be down for a long time(10s of seconds or more) and the switch to clusterDNS being helpful?

Or is the need to use the HA approach for cuttind down the couple of seconds DNS outage?

**Comment by bplotnick** [comment]
@prameshj I think 5s is fine for now (though many clients will wait up to 5s for DNS timeouts, so this is something like 10s worst case). We'll just need to treat it as a critical service with a tight SLO. We can crank up the check frequency if needed. I don't foresee issues being frequent, and if it is we'll need to work really hard to ensure stability.

I think the upgrade story is actually trickier. These can potentially be much more frequent, so we don't have as high of a tolerance for drops. We could potentially fail over to remote while we upgrade and then fail back, though it seems like there may be drops in this case as well.

I saw that GKE added [NodeLocal cache](https://cloud.google.com/kubernetes-engine/docs/how-to/nodelocal-dns-cache) (if you were part of that, congrats). I assume for upgrades, the nodes are drained and recreated? And for HA there's some checker pod?

**Comment by prameshj** [comment]
Thanks @bplotnick . The failover to kube-dns service on upgrade happens automatically.. as node-local-dns pods exit cleanly, they will delete the custom iptables rules that were setup to intercept traffic to kube-dns service. As long as the node-local-dns pod is up, requests from client pods to kube-dns ip will go to node-local-dns pod.  Once node-local-dns exits cleanly, the rules are removed, and DNS is handled by kube-dns service endpoints. These would be pods running kube-dns or CoreDNS as the case may be. 
This is the same behavior on GKE as well. A checker pod is needed to handle an abrupt exit of node-local-dns where the iptables rules are not cleaned up.

**Comment by bplotnick** [comment]
Ah right. So in effect in a rolling upgrade, the rules will be deleted and then re-added by the new pods. This makes sense, thanks! And if you are able to share the checker code, that would be great too.

**Comment by prameshj** [comment]
sure, Will share it here as well as in the README/docs once I have something tested.

**Comment by yannh** [comment]
Hi @prameshj ! Congrats on shipping to GKE :tada:  :)

I think it might be a bit tricky to run two separate daemonsets of nodecache at the moment. Nodecache tries to remove the interface it binds to when it exits, and when it restarts, tries to remove it again & then recreate it. This would likely leave your other nodecache daemonset in an unknown state. 

Because this was a concern to us, we developped coredns-nodecache ( https://github.com/contentful-labs/coredns-nodecache ), an alternative nodecache implementation, and run multiple daemonsets of it. However, for this to work we tell the daemonsets to not remove the interface/rules on shutdown - so there is no fallback to kube-dns.

I believe you could still have a 0-downtime upgrade strategy without running HA setting ".spec.updateStrategy.type" to RollingUpdate: https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/ ? Warning: we've not tested this :)

**Comment by prameshj** [comment]
> Hi @prameshj ! Congrats on shipping to GKE  :)
> 
> I think it might be a bit tricky to run two separate daemonsets of nodecache at the moment. Nodecache tries to remove the interface it binds to when it exits, and when it restarts, tries to remove it again & then recreate it. This would likely leave your other nodecache daemonset in an unknown state.
> 
> Because this was a concern to us, we developped coredns-nodecache ( https://github.com/contentful-labs/coredns-nodecache ), an alternative nodecache implementation, and run multiple daemonsets of it. However, for this to work we tell the daemonsets to not remove the interface/rules on shutdown - so there is no fallback to kube-dns.
> 
> I believe you could still have a 0-downtime upgrade strategy without running HA setting ".spec.updateStrategy.type" to RollingUpdate: https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/ ? Warning: we've not tested this :) - edit: since this would mean running two nodecaches at the same time, you would probably encounter the same problems as with two Daemonsets, and face unknown behaviour. Coredns-nodecache with --skipteardown might work

Thanks Yann for trying out and reporting the issue. I think we will need something similar to your skipteardown flag in the node-cache binary as well, to snot tear down the interface in the ha mode. I have not begun working on this yet, will update here when I do.

**Comment by overdrive3000** [comment]
> The [alternatives](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190424-NodeLocalDNS-beta-proposal.md#alternatives) in that KEP, list the option to run 2 daemonsets with SO_REUSEPORT and use the same linklocal ip for both cache instances. that should work in IPVS mode too.

How can I achieve this? I am trying to setup two NodeLocalDNS daemonsets but just one of them is being deployed the other one keep in `Pending` status due this error:

```
7 node(s) didn't match node selector, 8 node(s) didn't have free ports for the requested pod ports.
```

Even if I try to use different linklocal ip in each daemonset. Some help would be appreciated it.

**Comment by yannh** [comment]
Hi @overdrive3000 , currently coredns-nodecache ( https://github.com/contentful-labs/coredns-nodecache ) is the only solution that allows you to run 2 daemonsets. It is a different project from Nodecache hosted here, and the configuration differs. As @prameshj  mentioned, additional work is needed for nodecache to supports this - someone needs to take the time to implement it!

**Comment by prameshj** [comment]
> > The [alternatives](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190424-NodeLocalDNS-beta-proposal.md#alternatives) in that KEP, list the option to run 2 daemonsets with SO_REUSEPORT and use the same linklocal ip for both cache instances. that should work in IPVS mode too.
> 
> How can I achieve this? I am trying to setup two NodeLocalDNS daemonsets but just one of them is being deployed the other one keep in `Pending` status due this error:
> 
> ```
> 7 node(s) didn't match node selector, 8 node(s) didn't have free ports for the requested pod ports.
> ```
> 
> Even if I try to use different linklocal ip in each daemonset. Some help would be appreciated it.

This specific error is because the ports are conflicting. Metrics port of 9253, health port of 8080 in addition to port 53. If you use different ports for health and metrics in the second daemonset, and specify a node-cache image of k8s.gcr.io/k8s-dns-node-cache:1.15.8, this should work. I have not completely verified it does. I can check and report back today or tomorrow. 

As Yann mentioned, additional work is required to support this, when the pod exits. The pods should come up fine, but it won't be a true HA solution until we have that flag. I can work on adding the flag to skip teardown, it is on my list of things to do before GA.

**Comment by overdrive3000** [comment]
Thank you @yannh @prameshj for your responses. If the current version of nodelocal-dns cannot guarantee true HA yet, then I will try another strategy like draining my nodes during nodelocal-dns updates and wait for final version when it gets GA.

**Comment by prameshj** [comment]
@overdrive3000 @yannh  I was able to get this to work with a second yaml like this:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: node-local-dns
    kubernetes.io/cluster-service: "true"
  name: node-local-dns-backup
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: node-local-dns
  template:
    metadata:
      labels:
        k8s-app: node-local-dns
    spec:
      containers:
      - args:
        - -localip
        - 169.254.20.10
        - -conf
        - /etc/Corefile
        - -upstreamsvc
        - kube-dns-upstream
        - -skipteardown
        image: gcr.io/pavithrar-k8s-dev/k8s-dns-node-cache-amd64:1.15.10-5-g6751821
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            host: 169.254.20.10
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: node-cache
        ports:
        - containerPort: 9254
          hostPort: 9254
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 25m
            memory: 5Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /etc/coredns
          name: config-volume
        - mountPath: /etc/kube-dns
          name: kube-dns-config
      dnsPolicy: Default
      hostNetwork: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: node-local-dns
      serviceAccountName: node-local-dns
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - configMap:
          defaultMode: 420
          name: kube-dns
          optional: true
        name: kube-dns-config
      - configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile.base
          name: node-local-dns-backup
        name: config-volume
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-local-dns-backup
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  Corefile: |
    cluster.local:53 {
        errors
        cache {
                success 9984 30
                denial 9984 5
        }
        reload
        loop
        bind 169.254.20.10
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :9254
        health 169.254.20.10:8081
        }
    in-addr.arpa:53 {
        errors
        cache 30
        reload
        loop
        bind 169.254.20.10
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :9254
        }
    ip6.arpa:53 {
        errors
        cache 30
        reload
        loop
        bind 169.254.20.10
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :9254
        }
    .:53 {
        errors
        cache 30
        reload
        loop
        bind 169.254.20.10
        forward . __PILLAR__UPSTREAM__SERVERS__ {
                force_tcp
        }
        prometheus :9254
        }
```

I had to skip specifying container port 53, otherwise, the pods were in pending state, even though CoreDNS uses SO_REUSEPORT. Both Daemonsets do listen on port 53 though.

I added a -skipteardown flag in https://github.com/kubernetes/dns/pull/354 , that's the image i used.  
The caveat here is : Both the primary and the backup nodelocaldns instances need to use the -skipteardown flag, so neither one tears down the iptables rules/interfaces upon exit. this way, upgrading one does not break DNS traffic temporarily. If nodelocaldns is removed from the cluster, these rules/interface will need to be cleaned up.

**Comment by lzp0412** [comment]
> he failover to kube-dns service on upgrade happens automatically.. as node-local-dns pods exit cleanly, they will delete the custom iptables rules that were setup to intercept traffic to kube-dns service. As long as the node-local-dns pod is up, requests from client pods to kube-dns ip will go to node-local-dns pod. Once node-local-dns exits cleanly, the rules are removed, and DNS is handled by kube-dns service endpoints. These would be pods running kube-dns or CoreDNS as the case may be.
> This is the same behavior on GKE as well. A checker pod is needed to handle an abrupt exit of node-local-dns where the iptables rules are not cleaned up.

 Hi,  cleaning the rules when node-local-dns exits may work well on  iptables mode,but what about ipvs mode.  On ipvs mode,When we just have one node-local-dns pod, is there any way to intercept traffic  to kube-dns  service when node-loca-dns need to upgrade? One of the ways I came up with was to intercept the request of 168.255.10.20 to Kube-DNS service. But  how to let it work, i have not idea now.

**Comment by prameshj** [comment]
> > he failover to kube-dns service on upgrade happens automatically.. as node-local-dns pods exit cleanly, they will delete the custom iptables rules that were setup to intercept traffic to kube-dns service. As long as the node-local-dns pod is up, requests from client pods to kube-dns ip will go to node-local-dns pod. Once node-local-dns exits cleanly, the rules are removed, and DNS is handled by kube-dns service endpoints. These would be pods running kube-dns or CoreDNS as the case may be.
> > This is the same behavior on GKE as well. A checker pod is needed to handle an abrupt exit of node-local-dns where the iptables rules are not cleaned up.
> 
> Hi, cleaning the rules when node-local-dns exits may work well on iptables mode,but what about ipvs mode. On ipvs mode,When we just have one node-local-dns pod, is there any way to intercept traffic to kube-dns service when node-loca-dns need to upgrade? One of the ways I came up with was to intercept the request of 168.255.10.20 to Kube-DNS service. But how to let it work, i have not idea now.

Does the yaml in https://github.com/kubernetes/dns/issues/324#issuecomment-595314169 work? For IPVS, running 2 node-local-dns is the approach that could work.
