### ISSUE TITLE
Headless Service DNS during rollingUpdate?

### ISSUE THREAD

**Issue by ScubaDrew** [kubernetes/dns#332]
I've searched the documentation thoroughly for the timing of pod removal from DNS in a headless setup. 

I am looking for this because I am concerned about this situation:  

I'm trying to use headless services and do DNS discovery as shown in the documentation. However, you have to poll DNS for changes. As far as I can tell, if I poll DNS every 2 seconds, and during a rollingUpdate a pod it terminated, I'll end up sending data to a failed pod for 1-2 seconds (before it is discovered as removed from DNS).

Thank you for any insight. I think this could be added to the documentation. It is important to understand when traffic may be dropped/sent to dead pods.

**Comment by chrisohaver** [comment]
> the timing of pod removal from DNS in a headless setup.

CoreDNS is informed relatively immediately about changes in Service Endpoints (via an Endpoint events watch).  However by default CoreDNS gives all records a TTL of 5 seconds, so a terminated Pod will not expire from cache for up to an addtl 5 seconds. You can configure the default TTL to be 0 to prevent records from caching.

**Comment by ScubaDrew** [comment]
Thank you @chrisohaver -- I checked it it looks like the default config might be 30 seconds?

https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options

```
cache 30
```

**Comment by chrisohaver** [comment]
> the default config might be 30 seconds? ... `cache 30`

That is the maximum time a record will be cached for. IOW if the TTL of a record is > 30 seconds, it will only remain in cache for 30 seconds.

The default TTL for Kubernetes DNS records is 5 seconds.  That can be changed by adding the `ttl` option to the [kubernetes](https://github.com/coredns/coredns/tree/master/plugin/kubernetes#syntax) section of the CoreDNS config.

**Comment by ScubaDrew** [comment]
@chrisohaver You are amazing. Thank you for your time. Beyond the DNS cache setting - do you think it is possible to get the same level of reliability with headless services as with routing through IPTABLES ie: via a Kubernetes service ?

**Comment by chrisohaver** [comment]
From the DNS perspective it should be.  I can't speak authoritatively of the reliability of cluster IP vs headless networking as a whole though.

**Comment by faucct** [comment]
Is there some way to put a delay between removing records from DNS and stopping the service, so the records would be able to expire?

**Comment by kuzaxak** [comment]
> Is there some way to put a delay between removing records from DNS and stopping the pods, so the records would be able to gracefully expire?

PreStop hook in a pod
