### ISSUE TITLE
Memory usage for kube-dns

### ISSUE THREAD

**Issue by axot** [kubernetes/dns#334]
We found the memory usage of kubedns container keep growing and will hit the resource limit(170Mi). For now we have to restart these PODs to prevent OOM Kill. Is it as expected?

Environment:
GKE 1.13.7-gke.24

![image](https://user-images.githubusercontent.com/611054/70131933-7fb31580-16c6-11ea-89e0-8ee74c3468c2.png)

**Comment by MrHohn** [comment]
@prameshj Is this the same as https://github.com/miekg/dns/issues/807? If so this is fixed in a newer GKE version.

**Comment by MrHohn** [comment]
> If so this is fixed in a newer GKE version.

Or will be fixed :)

**Comment by prameshj** [comment]
Are client pods connecting to kube-dns over tcp? If yes, then it is same as miekg/dns#807

**Comment by axot** [comment]
Yes, most connections are from node-cache with force tcp option.

--
Zheng Shao

**Comment by prameshj** [comment]
> Yes, most connections are from node-cache with force tcp option.

Yes, if you use nodelocaldns, that will be the default. That is a good point, the chance of hitting this OOMKill scenario is higher with nodelocaldns enabled.  The fixed kube-dns image is here - k8s.gcr.io/k8s-dns-kube-dns-amd64:1.15.8

**Comment by axot** [comment]
@prameshj Thanks for the latest image for fixing this. Is there a way to use this new image for GKE?

**Comment by prameshj** [comment]
I will submit a patch to update the image on GKE. You could run a custom kube-dns deployment and use the specified image until then.

**Comment by marcoamorales** [comment]
@prameshj what's the difference between `k8s.gcr.io/k8s-dns-kube-dns-amd64:1.15.8` and `k8s.gcr.io/k8s-dns-node-cache:1.15.8`?

we're still seeing a constant increase of memory usage using `k8s.gcr.io/k8s-dns-node-cache:1.15.8` FWIW

**Comment by prameshj** [comment]
The 2 images are very different. node-cache uses CoreDNS(https://github.com/coredns/coredns), kube-dns is a different DNS server with implementation in this repo.

Are you seeing a regression from a previous node-cache image?
