### ISSUE TITLE
k8s-dns-node-cache doesn't support iptables-nft

### ISSUE THREAD

**Issue by champtar** [kubernetes/dns#338]
Right now k8s-dns-node-cache only support iptables-legacy
It would be nice to select iptables-legacy / iptables-nft automatically
see https://github.com/kubernetes/kubernetes/pull/82966 for how kubeproxy does it

**Comment by caruccio** [comment]
This is a show stopper for centos 8.

**Comment by champtar** [comment]
I rebuilt with
```
BASEIMAGE?=k8s.gcr.io/debian-iptables-$(ARCH):v12.0.1
```
And tested on CentOS8 / nft it works fine
Just need to fight with the Makefile a bit and I'll try to send a PR

**Comment by caruccio** [comment]
Thanks! It's working now.

**Comment by champtar** [comment]
@caruccio you rebuilt the image yourself ? because I don't see a new release with #355 in it

**Comment by caruccio** [comment]
@chadswen I was able to run it with gcr.io/google-containers/kube-proxy:v1.16.9-beta.0

**Comment by caruccio** [comment]
@champtar where are you looking at for the builds? Is this a public read-only CI?

**Comment by champtar** [comment]
I was just looking at the tags:
https://github.com/kubernetes/dns/releases

**Comment by caruccio** [comment]
OH ... maybe google is building images from `master`?

**Comment by champtar** [comment]
You are talking about kube-proxy, this is k8s-dns-node-cache*
https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/k8s-dns-node-cache-amd64?gcrImageListsize=30

**Comment by caruccio** [comment]
<img src="https://user-images.githubusercontent.com/540936/76998671-441a1f80-6934-11ea-855c-5fcd30f0230d.gif" align="left" height="100">
Even so, this is the same issue in kube-proxy. I will wait for this fix to be release, until then, kube-node-dns is disabled for me. Thanks and sorry for the mess :)

**Comment by champtar** [comment]
For kube-proxy this is fixed in 1.17+

**Comment by caruccio** [comment]
For whoever makes the same mistake as I did, the PR for kube-proxy is this https://github.com/kubernetes/kubernetes/pull/82966

**Comment by champtar** [comment]
#355 was reverted, this will be fixed by #367

**Comment by justaugustus** [comment]
/reopen
(until https://github.com/kubernetes/dns/pull/367 merges)
