### ISSUE TITLE
-profiling flag for node-cache

### ISSUE THREAD

**Issue by Nastradamus** [kubernetes/dns#346]
In `k8s.gcr.io/k8s-dns-node-cache:1.15.8` I've got an error while trying to enable profiling with command args:

```
flag provided but not defined: -profiling
```

**Comment by Nastradamus** [comment]
I figured it out and made Helm chart with support of profiling in 1.15.8:
https://github.com/Nastradamus/myhelmcharts/tree/master/nodelocaldns

**Comment by prameshj** [comment]
Is the issue still valid? Does profiling work if a port is specified?

**Comment by Nastradamus** [comment]
> Is the issue still valid? Does profiling work if a port is specified?

Yes, issue is solved. Profiling is working if port is specified inside Coredns config (see my Helm chart example in the link above).
