### ISSUE TITLE
dns no servers could be reached

### ISSUE THREAD

**Issue by ianhe8x** [kubernetes/dns#347]
Hi all,
I have a gke cluster just setup, master version v1.15.7-gke.23

Werid thing happens for dns, and i uncover a few interesting thing about the dns.

during my debug:
`kubectl run -i --tty --image alpine dns-test --restart=Never --rm /bin/sh`

```
/ # cat /etc/resolv.conf
nameserver 10.6.0.10
search default.svc.cluster.local svc.cluster.local cluster.local us-west1-a.c.mx-prod.internal c.mx-prod.internal google.internal
options ndots:5
```

```
/ # nslookup www.google.com
;; connection timed out; no servers could be reached
```

but if i query via kube-dns's pod ip, it works

```
/ # nslookup www.google.com 10.6.0.77
Server:		10.6.0.77
Address:	10.6.0.77:53

Non-authoritative answer:
Name:	www.google.com
Address: 74.125.142.147
Name:	www.google.com
Address: 74.125.142.105
Name:	www.google.com
Address: 74.125.142.103
Name:	www.google.com
Address: 74.125.142.106
Name:	www.google.com
Address: 74.125.142.104
Name:	www.google.com
Address: 74.125.142.99

Non-authoritative answer:
Name:	www.google.com
Address: 2607:f8b0:400e:c07::6a
```

```
➤kubectl -n kube-system get svc,ep kube-dns
NAME               TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
service/kube-dns   ClusterIP   10.6.0.10    <none>        53/UDP,53/TCP   11d

NAME                 ENDPOINTS                   AGE
endpoints/kube-dns   10.6.0.77:53,10.6.0.77:53   11d
```

Anyone can help, i'm stucked here for whole day already.

**Comment by bowei** [comment]
Did you trace the packet to the DNS service? (It may not be a DNS problem, more like a generic networking problem)

https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

**Comment by ianhe8x** [comment]
It doesn't involve my own services, so i didn't try methods in debug-service.

**Comment by bowei** [comment]
We need more information to understand what is the problem.
If you can get the user to run the debug-service workflow, then we can make more progress on this issue.

**Comment by ianhe8x** [comment]
Thanks for your help. I think this issue isn't worthy our time for further investigation. It is newly created cluster, and i created a new one which works fine.

**Comment by GovardhanDo** [comment]
where you able to fix this issue?

**Comment by GovardhanDo** [comment]
I ran into the same problem,

**Comment by bowei** [comment]
Please open a new issue w/ your specific problem. Commenting on closed issues will likely be ignored.

**Comment by Davidrjx** [comment]
any progress or result? i was faced with same probles
