### ISSUE TITLE
kube-dns should use versioned client-go

### ISSUE THREAD

**Issue by bowei** [kubernetes/dns#35]
kube-dns should use a versioned copy of the client-go repository, rather than HEAD

**Comment by cmluciano** [comment]
I tried this locally, but DNS does not have the proscriptive procedure that [kube devel](https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md) has. 

Upon checking out release 1.5 for client-go, I ran ``godep save`` which seemed to change a bunch of stuff in ``vendor`` that was unrelated to this package. 

I also noticed that we are building with Go 1.6 and Kube master is using 1.7. Should we bump this too?

Please let me know if I'm heading in the right direction. I'm more familiar with dependency systems like glide.

**Comment by bowei** [comment]
@cmluciano -- thanks for taking a look at this.

The procedure from kube devel should work with modifications -- I will add a doc. Unfortunately, due to some issues with the way the kubernetes repo is setup, glide does not work at the moment.

**Comment by cmluciano** [comment]
Thanks a ton! I will try again with your doc.

**Comment by bowei** [comment]
@cmluciano -- I added some scripts to make it easier to use godep, please take a look:

https://github.com/kubernetes/dns/blob/master/docs/go-dependencies.md

**Comment by cmluciano** [comment]
Awesome PR forthcoming

**Comment by cmluciano** [comment]
Just conforming, would we like client-go v1.5 or the prerelease?

**Comment by GheRivero** [comment]
I'm not a fan of not using stable releases as dependencies, could be a nightmare to debug if they change something without noticing it

**Comment by bowei** [comment]
@cmluciano -- it should be client-go v.1.5

@GheRivero -- the vendored client must be updated explicitly (e.g. via a commit). Tracking an external version should be more stable than grabbing a commit off of HEAD.

**Comment by cmluciano** [comment]
Yep, the v1.5 has things stored under a 1.5 directory, which threw me off a bit.

**Comment by cmluciano** [comment]
Decision is to wait for the latest tagged release when all apimlchinery is figured out. Using the current tagged releases would result in reverted code.

**Comment by cmluciano** [comment]
@bowei going to take another stab at this today since the 1.6 compatible version is in beta
