### ISSUE TITLE
Cut a new tag/ release

### ISSUE THREAD

**Issue by pnovotnak** [kubernetes/dns#351]
We (Reddit) need to take advantage of the recent changes since 1.15.9 and are hoping a new release or at least new images pushed.

**Comment by bowei** [comment]
@prameshj

**Comment by prameshj** [comment]
I will try to get one more change PR in and get the release.

**Comment by prameshj** [comment]
1.15.9 images have been released.

**Comment by pnovotnak** [comment]
@prameshj Did you mean to push these images as `1.15.10`?

**Comment by prameshj** [comment]
oops... yes, you're right. I will update the tag 1.15.10 to also include https://github.com/kubernetes/dns/pull/354 and push the images today.

/reopen

**Comment by prameshj** [comment]
1.15.10 images are now available.
k8s.gcr.io/k8s-dns-node-cache:1.15.10

/close
