### ISSUE TITLE
Upgrade to coreDNS 1.7.0

### ISSUE THREAD

**Issue by prameshj** [kubernetes/dns#359]
Use the max_concurrent option to limit the number of concurrent connections in nodelocal DNSCache, to limit memory usage.

https://github.com/coredns/coredns/releases >v1.6.7 has https://github.com/coredns/coredns/pull/3640
#3640 plugins/forward: Add max_concurrent option

/assign

**Comment by prameshj** [comment]
OSS k8s is still using 1.6.7, Will wait for that to upgrade before upgrading in node-cache.

**Comment by rajansandeep** [comment]
> https://github.com/coredns/coredns/releases >v1.6.7 has coredns/coredns#3640
#3640 plugins/forward: Add max_concurrent option

This is included in CoreDNS 1.6.9. 
Although, CoreDNS 1.7.0 was released yesterday and we plan to include it for k8s 1.19

Note: 1.6.8 is a broken release

**Comment by prameshj** [comment]
Thanks for the information, Sandeep. I will aim to update to 1.7.0 after the k8s update.

**Comment by prameshj** [comment]
https://github.com/kubernetes/kubernetes/pull/92718 is updating CoreDNS in k8s.

**Comment by prameshj** [comment]
@pnovotnak are you planning to work on this? I can try to get to this next week, in case you aren't actively looking into it.

**Comment by prameshj** [comment]
WIP PR - https://github.com/kubernetes/dns/pull/400

Currently hitting a log_dir flag redefined error:

```
/tmp/go-build286760831/b485/sidecar.test flag redefined: log_dir
panic: /tmp/go-build286760831/b485/sidecar.test flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000c4120, 0x1350be0, 0x1b78350, 0x11db614, 0x7, 0x1204cb8, 0x2f)
	/usr/local/go/src/flag/flag.go:848 +0x4ae
flag.(*FlagSet).StringVar(...)
	/usr/local/go/src/flag/flag.go:751
k8s.io/klog.InitFlags(0xc0000c4120)
	/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:420 +0x7f
k8s.io/component-base/logs.init.0()
	/go/pkg/mod/k8s.io/component-base@v0.0.0-20190620085130-185d68e6e6ea/logs/logs.go:35 +0x2d
FAIL	k8s.io/dns/cmd/sidecar	0.209s
```
```

Looks like it is related to the issue - https://github.com/kubernetes/kubernetes/issues/74560, maybe we need to blacklist the glog flags that are getting redefined using something similar to - https://github.com/coredns/coredns/pull/1431/

**Comment by prameshj** [comment]
This was done in https://github.com/kubernetes/dns/pull/400
