### ISSUE TITLE
any better way to monitor lookup time?

### ISSUE THREAD

**Issue by guangbaowan** [kubernetes/dns#360]
hi, we build a micro service system using k8s and use jaeger for tracing .now found sometimes it takes hundreds of milliseconds when do dns lookup. is there any suggestions for monitoring the duration ? thx .

**Comment by chrisohaver** [comment]
CoreDNS exports a Prometheus metric for latency, but this is just the latency "within" CoreDNS.  It cannot capture the full round trip time to the client.

There are a handful of tools out there that monitor dns latency from the client perspective, but I could not find any that output metrics to Prometheus.  So, I wrote a simple monitoring program for my own purposes, [dnsdrone](https://github.com/chrisohaver/dnsdrone). It can be used to make test DNS lookups and it reports Prometheus metrics including full round trip latency to the client.

**Comment by guangbaowan** [comment]
thx. i will try it .
