### ISSUE TITLE
node-cache misleading default value for syncinterval

### ISSUE THREAD

**Issue by witalisoft** [kubernetes/dns#362]
https://github.com/kubernetes/dns/blob/9bec2dd2987430f68bc9c7e470c2260d6b1170d4/cmd/node-cache/main.go#L62

default value means 60ns, pretty often

**Comment by prameshj** [comment]
We create a ticker by treating this value as Second.
https://github.com/kubernetes/dns/blob/9bec2dd2987430f68bc9c7e470c2260d6b1170d4/cmd/node-cache/app/cache_app.go#L182

I wrote a simple example to make sure this works as expected (Used 6s in the example)
https://play.golang.org/p/_wzR-BXfuEb

**Comment by witalisoft** [comment]
Thanks
