### ISSUE TITLE
dns node cache container v1.15.11 is missing iptables binary

### ISSUE THREAD

**Issue by EppO** [kubernetes/dns#365]
current DNS node cache deployment using 1.15.11 are filled with this kind of logs:
```
[ERROR] Error adding iptables rule {filter OUTPUT [-p tcp -s 169.254.25.10 --sport 53 -j ACCEPT]} - error checking rule: executable file not found in $PATH:
```
Rolling back to 1.15.10 for now.

```
# docker run --rm -it --entrypoint=/bin/sh gcr.io/google-containers/k8s-dns-node-cache:1.15.11
# /sbin/iptables
/bin/sh: 1: /sbin/iptables: not found
# cd /usr/sbin
# iptables
/bin/sh: 3: iptables: not found
```

```
docker run --rm -it --entrypoint=/bin/sh gcr.io/google-containers/k8s-dns-node-cache:1.15.10
# find . -name iptables
./usr/share/iptables
./usr/share/doc/iptables
./sbin/iptables
#
```

**Comment by prameshj** [comment]
I was just about to open the same issue. Thanks for filing this. The base image was changed in https://github.com/kubernetes/dns/pull/355

@champtar can you take a look?

**Comment by champtar** [comment]
@prameshj I'll have a look right now

**Comment by champtar** [comment]
```
podman run --rm -it --entrypoint=/bin/sh k8s.gcr.io/debian-iptables-amd64:v12.0.1
...
# iptables
iptables v1.8.3 (legacy): no command specified
Try `iptables -h' or 'iptables --help' for more information.
```

**Comment by prameshj** [comment]
what about if you try the node-cache 1.15.11 image?

**Comment by champtar** [comment]
node-cache 1.15.11 is broken for sure
This if
https://github.com/kubernetes/dns/blob/40b665f324c13c7c52cffdfd3453a52af2375db5/rules.mk#L32
doesn't work, so we use debian-base instead of debian-iptables

**Comment by champtar** [comment]
Sorry for the poor testing, here a fixed version https://github.com/kubernetes/dns/pull/367

**Comment by prameshj** [comment]
This is fixed in image - k8s.gcr.io/k8s-dns-node-cache:1.15.12

/close
