### ISSUE TITLE
Add support for TXT entries

### ISSUE THREAD

**Issue by therc** [kubernetes/dns#38]
gRPC has a new proposal out for storing service configurations in TXT records:

https://github.com/grpc/proposal/pull/5

If you use gRPC under Kubernetes, you will now have two choices:

1. use parallel DNS hierarchies, one managed by kube-dns, one by a more traditional DNS server just for the TXT records
1. extend kube-dns to support custom TXT records

I would prefer the second, by far. This could be accomplished through either an annotation or a new field on the service. Since I have some experience with kube-dns, having implemented ExternalName support, I can help with some/all the code, too. Of course, gRPC is just going to be one use case for the feature.

This seems to be related to, but still independent from https://github.com/kubernetes/kubernetes/issues/6437

**Comment by thockin** [comment]
This isn't horrible, but I am not sure exactly how we would want to support
it.

@bowei

**Comment by bowei** [comment]
@therc -- let's start with a strawman proposal -- you can create a pull request against the docs/specification and proceed from there

**Comment by cmluciano** [comment]
@therc I can help out with this once we have a proposal.
