### ISSUE TITLE
Shared DNS between two kubernetes clusters

### ISSUE THREAD

**Issue by BigaDev** [kubernetes/dns#382]
Let us assume that there are two kubernetes clusters and there is a pod A in the first cluster and pod B in the second cluster and add to this that those two clusters in the same subnet. I need to call inside pod A and service inside pod B using the pod service record ( A/AAAA records) (for info about Kube dns: DNS for Services and Pods - Kubernetes 1)

Currently I depend on the pod internal private IP but I think it’s not the best way, so what do you think ?

**Comment by bowei** [comment]
We don't specify a Kubernetes API per se, however, have you look at something like https://coredns.io/plugins/transfer/ with a unique cluster suffix?

Another avenue is https://github.com/kubernetes-sigs/external-dns

**Comment by johnbelamaric** [comment]
Zone transfer works. Alternatively see the kubernetai plugin at
https://coredns.io/explugins/kubernetai/
 and
https://github.com/coredns/multicluster-dns.

None of this works as well as you’d like if cluster IPs are not routable -
which is normally the case.

John
