### ISSUE TITLE
How dns queries are redirected to nodeLocalcache pod

### ISSUE THREAD

**Issue by YanzhaoLi** [kubernetes/dns#399]
The contents of `/etc/resolv.conf` in normal pods is generally the `clusterip` of coredns. When pod do dns query to the clusterip of coredns, I wonder how are these requests redirected to nodeLocalCache Pod?

I think the iptables rules are just used for NOTRACK. These rules wouldn't do this redirection.  

BTW, how do I check whether the NodeLocalCache pod has intercepted the dns query

**Comment by YanzhaoLi** [comment]
I found that the dummy interface makes the clusterip as a link local ip. 
So in case of CNIs based on OpenvSwitch, the pod traffic would bypass guest cluster but instead enter into hypervisor directly, thus, nodeLocalCache wouldn't intercept any pod traffic

**Comment by chengzhycn** [comment]
check the output of $(iptables-save |grep OUTPUT), you will find that all pod's dns trafiic are redirected to the localhost:53. And there is a node-cache pod listening port 53 which running in hostnetwork will handle these traffic

**Comment by YanzhaoLi** [comment]
Thanks, @chengzhycn . But who created these rules on OUTPUT chain?  I didn't see these rules from the source code of NodeLocalCache: https://github.com/kubernetes/dns/blob/40926cd008c8f84c82b30bb0222450ddd30628d1/cmd/node-cache/app/cache_app.go#L94

**Comment by prameshj** [comment]
> I think the iptables rules are just used for NOTRACK. These rules wouldn't do this redirection.

The NOTRACK rules ensure that no connection tracking happens and also that NAT rules are skipped. The filter table INPUT and OUTPUT chain ACCEPT rules make sure that the packets don't get dropped.

https://github.com/kubernetes/dns/blob/40926cd008c8f84c82b30bb0222450ddd30628d1/cmd/node-cache/app/cache_app.go#L115



> BTW, how do I check whether the NodeLocalCache pod has intercepted the dns query

You can add the "log" plugin in node-local-dns configmap and check the pod logs. You can also look at the metrics for nodelocaldns pods using "curl http://localhost:9253/metrics | grep requests" and see if the request count goes up.

**Comment by prameshj** [comment]
Hope this answers your question @YanzhaoLi , please reopen if needed.
