### ISSUE TITLE
Support rewrite plugin for NodeLocal DNS

### ISSUE THREAD

**Issue by rtheis** [kubernetes/dns#406]
NodeLocal DNS does not support the CoreDNS `rewrite` plugin.  We have several customers that would like to enable NodeLocal DNS but are unable to do so because it does not support the `rewrite` plugin.

Related this, it would be ideal if there was documentation for which CoreDNS configurations are not supported for use with NodeLocal DNS.

**Comment by owengo** [comment]
rewrite plugin would allow to rewrite AAAA requests
