### ISSUE TITLE
Is version 1.15.4 the latest release?

### ISSUE THREAD

**Issue by tomfotherby** [kubernetes/dns#414]
_[Please close this Issue if it's not an appropriate question to ask - in which case, sorry for wasting time]_

We currently use a old version of `k8s-dns-node-cache`, `1.15.3`,  and I want to upgrade. I'm trying to work out what version of `node-cache` **is recommended.**

Looking at the releases page ( https://github.com/kubernetes/dns/releases ) the `latest release` tag is on version `1.15.4` (from 5/Jun/19). Is `1.15.4` really the recommended version? or is this simply a metadata issue and the `latest release` tag needs to be put on a newer version?

![Selection_839](https://user-images.githubusercontent.com/140179/96372594-70fb1300-115f-11eb-9768-36ace3c63b16.png)

The Kubernetes core project uses `k8s-dns-node-cache` version `1.15.14` : ref: https://github.com/kubernetes/kubernetes/pull/94951/files - is this the version I should choose?

The [README](https://github.com/kubernetes/dns/blob/master/README.md) mentions `1.15.14` but doesn't indicate it is the recommened release:

> Images will be available in the repo k8s.gcr.io/dns/. The node-cache image with tag 1.15.14 can be found at k8s.gcr.io/dns/k8s-dns-node-cache:1.15.14. Older versions are at k8s.gcr.io/k8s-dns-node-cache:

---

On a side note, I'm also confused how to map what version of CoreDNS is used by `node-cache`. For example, I'd like to check the relevant CoreDNS [CHANGLOG](https://coredns.io/2020/09/21/coredns-1.7.1-release/) when I upgrade the `k8s-dns-node-cache` docker image but I don't know how to tie the 2 versions together. I found the appropriate [Dockerfile](https://github.com/kubernetes/dns/blob/master/Dockerfile.node-cache) but was still in the dark. I found a related Issue: https://github.com/kubernetes/dns/issues/410

**Comment by prameshj** [comment]
We have been using tags to mark new releases, rather than explicitly create releases. 1.17.0 is the latest tag, the images havent been promoted.
https://github.com/kubernetes/dns/tags

1.16.0 is the latest release with the image available as well.  This is also being used in k/k - https://github.com/kubernetes/kubernetes/blob/bae644e85e085ce668c3edf23e8789fb623331b4/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml#L141
