### ISSUE TITLE
Align metrics names with upstream CoreDNS

### ISSUE THREAD

**Issue by tomfotherby** [kubernetes/dns#416]
We use Amazon Elastic Kubernetes Service (EKS) and recently upgraded from 1.17 to 1.18. Part of the [upgrade process](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html) recommends to upgrade DNS (CoreDNS) to `1.7.0`.

After the upgrade our DNS Dashboard in Grafana lost some observability. Metrics seemed to go missing :mag: . The "problem" is that CoreDNS 1.7 changed the metrics names ([CHANGELOG](https://coredns.io/2020/06/15/coredns-1.7.0-release/)) meaning we now have a situation where our `node-local-dns` service publishes different metrics from our `kube-dns` service.

We can modify our grafana dashboard so that it supports both types of metric names, but it would be best if we could upgrade `k8s-dns-node-cache` to a version that uses CoreDNS 1.7 and therefore uses consistent metrics names.

---

We use `k8s-dns-node-cache` v1.15.3 - I know this is a old version and it's bad form to raise a Issue unless using the latest release. But I'm not exactly sure [what the latest release is?](https://github.com/kubernetes/dns/issues/414)

**Comment by kirooshu** [comment]
Not answering what the latest release is but 

```
1.16.0  …
Upgraded to coreDNS 1.7, go modules.
Using debian-iptables in node-cache
Also updated to debian base buster-v1.2.0
```

**Comment by mvisonneau** [comment]
The latest seems to be `1.16.0` however it looks like `1.17.0` has been tagged: https://github.com/kubernetes/dns/releases/tag/1.17.0

```
~$ crane ls k8s.gcr.io/dns/k8s-dns-node-cache
1.15.14
1.15.16
1.16.0
```

It would be great to have more visibility around this! 🙏 🙇

**Comment by prameshj** [comment]
That is correct, we only use tags and not a release every single time. Once we create a tag in https://github.com/kubernetes/dns/tags, the new images are built and need to be manually promoted. This is detailed in the README - https://github.com/kubernetes/dns#release-process

Please suggest changes to this doc or feel free to send a PR. Thanks!

**Comment by prameshj** [comment]
Since 1.16.0 and later are using coreDNS 1.7, i hope this is now resolved. Please reopen if needed.
