### ISSUE TITLE
docker registry with a port breaks make script

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/dns#43]
The make script allows you to set a registry from the env; however, if it's something like `foo:5000` it will fail with:

`rules.mk:125: *** target pattern contains no `%'.  Stop.`

**Comment by cmluciano** [comment]
This seems to be a problem with make/bash. 

From the [make docs](https://www.gnu.org/software/make/manual/html_node/Using-Variables.html)
```
A variable name may be any sequence of characters not containing ‘:’, ‘#’, ‘=’, or whitespace.
```

We can escape the colon with a backslash, but that would be required input from the user. 

2 options I see so far:
- Document that custom registries require a backslash when a port is given
- Try rewriting the REGISTRY variable [like so](http://blog.jgc.org/2007/06/escaping-comma-and-space-in-gnu-make.html) if a colon is detected

**Comment by thockin** [comment]
Can you post an exact commandline you are using?

**Comment by cmluciano** [comment]
Steps to reproduce:
- Run local registry ``docker run -d -p 5000:5000 --restart=always --name registry registry:2``
- Pull alpine and golang from public registries (golang:1.7-alpine, alpine:3.4)
- Retag and push golang and alpine to local registry
- Change [registry](https://github.com/kubernetes/dns/blob/master/Makefile#L30) to  
localhost\:5000/cmluciano 
- Run ``make images-build && make images-push``
