### ISSUE TITLE
When will 1.17.0 container be published?

### ISSUE THREAD

**Issue by devteng** [kubernetes/dns#439]
Hi all, I see that 1.17.0 has been released. When does the 1.17.0 container get published? Thanks!

**Comment by prameshj** [comment]
Being promoted in https://github.com/kubernetes/k8s.io/pull/1640. Will aim to do this in the same week we tag a new release in future.

**Comment by antonio-te** [comment]
As it happens, I have the same question about `1.17.1`.

**Comment by prameshj** [comment]
I hadn't promoted the image since it was mostly reverting a dnsmasq version. I see there is also a iptables image being changed - https://github.com/kubernetes/dns/compare/1.17.0...1.17.1

Will do it by end of the week.

**Comment by antonio-te** [comment]
Thank you very much!

**Comment by prameshj** [comment]
No worries.. they are being promoted here - https://github.com/kubernetes/k8s.io/pull/1763

**Comment by antonio-te** [comment]
Looks like this issue is closable. Thanks again!

**Comment by prameshj** [comment]
Thanks. 
/close
