### ISSUE TITLE
Question: HA solution for node-cache

### ISSUE THREAD

**Issue by mlowery** [kubernetes/dns#447]
In an [older KEP for NodeLocal DNSCache](https://github.com/kubernetes/enhancements/tree/4f43d2c8005488180c1af7d3ad60f119755ed383/keps/sig-network/1024-nodelocal-cache-dns), it seems to suggest that, when in IPTABLES mode, the official HA solution is some kind of "nanny" component that watches the local node-cache then flips a switch when it becomes unhealthy:

> We still need some component to dynamically determine when to use node-local-dns and when to flip to kube-dns endpoints.

Is there a reference implementation for this nanny component?

On a related note, is there any discussion about what a Topology-aware service routing solution would look like (mentioned in [newer KEP for NodeLocal DNSCache](https://github.com/kubernetes/enhancements/tree/c325642588ce979a277d9ed17bc886e0141579bd/keps/sig-network/1024-nodelocal-cache-dns):

> A nodelocaldns service can be created with a hard requirement of same-node endpoint, once we have this supported. All the pods in the nodelocaldns daemonset will be endpoints, the one running locally will be selected. iptables rules to NOTRACK connections can still be added, in order to skip DNAT in the iptables kube-proxy implementation.

**Comment by prameshj** [comment]
Hi Mat, there isn't a reference implementation for the component that flips the switch between node-local-dns pods and clusterDNS pods.

The high level idea is that the nanny component will be checking the responsiveness of node-local-dns on the 169.254.20.10 address and if n(maybe 5) DNS lookups fail in a row, it will flip the switch to the kube-dns service, while continuing to check node-local-dns and flip the switch back once it is responsive.

The topology discussion hasn't progressed much. I think it is removed in the latest version of the KEP - https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1024-nodelocal-cache-dns
Is there a specific usecase you are asking about?

**Comment by mlowery** [comment]
Thanks @prameshj.

> Is there a specific usecase you are asking about?

IPVS mode and what HA options are available for that mode.
