### ISSUE TITLE
Add Vagrantfile to ease development on DNS

### ISSUE THREAD

**Issue by cmluciano** [kubernetes/dns#45]
I have a Vagrantfile that sets up a Ubuntu 16.04 box to build/test this repository. I've been using it since this repository contains scripts that don't play well on Darwin.

 I can open a PR to add this to the root path if we think that it would be beneficial.

**Comment by bowei** [comment]
Sounds useful, yes unfortunately there are some tiny differences between the BSD and Linux userland.
