### ISSUE TITLE
Container images for v1.18.0 missing

### ISSUE THREAD

**Issue by ScheererJ** [kubernetes/dns#451]
From the [release page](https://github.com/kubernetes/dns/releases), it looks like v1.18.0 has been released. However, I cannot find/pull the corresponding container image for the dns node cache (k8s.gcr.io/dns/k8s-dns-node-cache:1.18.0).

Will the container image created or is it now located somewhere else?

**Comment by DockToFuture** [comment]
Any update on this issue?

**Comment by superseb** [comment]
@prameshj can you look at this? Or someone else from the OWNERS?

**Comment by prameshj** [comment]
Most images were promoted in https://github.com/kubernetes/k8s.io/pull/2118, I see one was missed. I am promoting it in https://github.com/kubernetes/k8s.io/pull/2251

It should work once that PR merges.

**Comment by ScheererJ** [comment]
Thanks a lot.

It seems like the k8se-dns-node-cache container image is now available.
