### ISSUE TITLE
Support for k8s 1.20

### ISSUE THREAD

**Issue by Shahard2** [kubernetes/dns#454]
Hello,
Once i updated my cluster of EKS to 1.20 (CoreDNS and kubeproxy as well)

nodelocaldns started to do problems and my hashicorp consul couldn't start.

Can you make sure it's supporting the changes of k8s 1.20 ?

**Comment by SuperQ** [comment]
https://github.com/kubernetes/dns/pull/455 should help.

**Comment by Shahard2** [comment]
> https://github.com/kubernetes/dns/pull/455 should help.

Thanks alot, will try this ASAP!

**Comment by prameshj** [comment]
What is the specific issue with nodelocaldns on k8s 1.20?

**Comment by Shahard2** [comment]
Our consul had problem with finding the node addresses...

i didn't deep dive to why but I'm waiting for #455 to be merged and I will try again

**Comment by prameshj** [comment]
> Our consul had problem with finding the node addresses...
> 
> i didn't deep dive to why but I'm waiting for #455 to be merged and I will try again

PR #455 updates k8s dependency to 1.19. I am not sure if that could help with the issue you described, because node-local-dns does not depend on kubernetes version. It does not watch any k8s resources, it is only a DNS cache. Can you describe more about the issue or share node-local-dns logs ?

**Comment by prameshj** [comment]
@Shahard2 any updates on the issue?

**Comment by chrisohaver** [comment]
@prameshj, @Shahard2 recently opened https://github.com/coredns/coredns/issues/4765, which I am assuming is the same issue?

CoreDNS logs have not yet been provided.

**Comment by prameshj** [comment]
I see..Thanks!
 I am unable to understand how nodelocaldns fits in/errors out here? Any specific logs from nodelocaldns, @Shahard2 ?

From the CoreDNS issue that Chris linked, looks like the DNS name for a consul LoadBalancer service is not created and that is the issue? If it was not created by coreDNS, then nodelocaldns won't be able to look it up either. But if it is a pure lookup issue for an existing name, we need more logs to debug.

**Comment by Shahard2** [comment]
Right, closing it since it related to coredns only.
