### ISSUE TITLE
Add a dns presubmit in prow

### ISSUE THREAD

**Issue by prameshj** [kubernetes/dns#458]
Travis CI is no longer running - https://travis-ci.org/github/kubernetes/dns due to migration to travis-ci.com. 

The prow job in https://github.com/kubernetes/test-infra/blob/1c8419d11198aecd8b66df8549a7ca17c8183fbf/config/jobs/kubernetes/sig-network/sig-network-misc.yaml#L182 needs to be updated to run all the commands executed by the travis job.

The recommendation is also to use podutils, since bootstrap.py is deprecated.  https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#why-use-pod-utilities

migration guide - https://gist.github.com/dims/c1296f8ed42238baea0a5fcae45f4cf4

The following steps should be followed:

1) reset the prow job to be a no-op.
2) Merge https://github.com/kubernetes/dns/pull/457
3) Modify prow job to invoke the script
4) migrate to using podutils.

**Comment by prameshj** [comment]
cc @MrHohn @aojea

**Comment by prameshj** [comment]
Migration to podutils is in progress - https://github.com/kubernetes/test-infra/pull/22681

**Comment by prameshj** [comment]
The presubmit now gets triggered optionally, but fails at docker run command with error 125.

This is the makefile location - https://github.com/kubernetes/dns/blob/bfe1dddaadc0cf6fcad6f0633db4456fa1726b0a/images/dnsmasq/Makefile#L122

Failed logs - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/dns/461/pull-kubernetes-dns-test/1408068353863454720/build-log.txt

```
k8s.gcr.io/build-image/debian-base-amd64:buster-v1.6.0
make[3]: *** [Makefile:122: _output/amd64/docker/dnsmasq] Error 125
make[3]: Leaving directory '/home/prow/go/src/k8s.io/dns/images/dnsmasq'
make[2]: *** [Makefile:66: test-dnsmasq] Error 2
make[2]: Leaving directory '/home/prow/go/src/k8s.io/dns/images'
make[1]: *** [Makefile:49: test] Error 2
make[1]: Leaving directory '/home/prow/go/src/k8s.io/dns/images'
make: *** [rules.mk:210: images-test] Error 2
```

From (docker docs](https://docs.docker.com/engine/reference/run/#exit-status), error 125 means some flag was not provided correctly. The script should be running as root (I checked from running the same pod image locally), so it is not a permissions issue.

I suspect `service docker start` is not enough to start docker on the pod.

**Comment by prameshj** [comment]
cc @fejta @BenTheElder - Is anything extra needed in order for the prow job to run docker? 
https://github.com/kubernetes/test-infra/blob/a2944e60bca47041837304e6e98907c6cd49adb1/config/jobs/kubernetes/sig-network/sig-network-misc.yaml#L182 is the job config.

**Comment by aojea** [comment]
at least  IIRC
```
    labels:
      preset-dind-enabled: "true"
```

**Comment by BenTheElder** [comment]
Yes. And you must wrap your command with the image's shellscript if you're using podutils. For kubekins-e2e this is `runner.sh your-command`

**Comment by prameshj** [comment]
Thanks Antonio and Ben! I have included the new label in https://github.com/kubernetes/test-infra/pull/22694 and we are already using runner.sh ./presubmits.sh. 

The build is working now, the failure now is an actual test failure/flake. I am looking into it.
