### ISSUE TITLE
node-cache 1.18.1 failed to build for ARM

### ISSUE THREAD

**Issue by prameshj** [kubernetes/dns#466]
build logs are [here](https://storage.googleapis.com/kubernetes-jenkins/logs/dns-push-images/1408485603208597504/build-log.txt)

```
Status: Downloaded newer image for k8s.gcr.io/build-image/debian-iptables-arm:buster-v1.6.3
 ---> e0f1bb6100a2
Step 2/6 : RUN update-alternatives --set ebtables /usr/sbin/ebtables-legacy
 ---> [Warning] The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 8c7f17e2beb7
[91mstandard_init_linux.go:219: exec user process caused: no such file or directory
[0mThe command '/bin/sh -c update-alternatives --set ebtables /usr/sbin/ebtables-legacy' returned a non-zero code: 1
make[1]: *** [rules.mk:151: .gcr.io_k8s-staging-dns_k8s-dns-node-cache-arm_1.18.1-container] Error 1
make: *** [rules.mk:68: push-arm] Error 2
ERROR
```

@luigibk do you know what might be wrong here? Looks like building from an amd64 based image is causing the warning. Similar issue - https://github.com/dani-garcia/vaultwarden/discussions/1264

But the actual error might be that `/usr/sbin/ebtables-legacy` is not found. 

https://github.com/kubernetes/dns/blob/c515c13038d40da3af71ab1c544ef67935293235/Dockerfile.node-cache#L16 is the line that references ebtables-legacy.

**Comment by prameshj** [comment]
If I revert rules.mk change in https://github.com/kubernetes/dns/pull/456/files, build works fine without the warning or the error.

But it fails, even with buster-v1.6.5. @justaugustus

**Comment by justaugustus** [comment]
@kubernetes/release-engineering -- can you assist in debugging here?

**Comment by wespanther** [comment]
The "exec user process caused: no such file or directory" log line is a bit of a red herring, it's actually because we can't run the arm debian-iptables image on amd64. This is because node-cache is relying on the existence of qemu-$arch-static that gets pulled in from the base image (debian-base). The reason it just started failing for arm is because it's the first non-x86 arch (and x86 succeeds on the prow hosts).

In this case, it starts to fail between debian-base:buster-v1.7.1 and buster-v1.7.2. It was removed in this PR:

https://github.com/kubernetes/release/pull/2113

**Comment by luigibk** [comment]
Hi @wespanther do I understand correctly that even removing this line:

`RUN update-alternatives --set ebtables /usr/sbin/ebtables-legacy`

in [Dockerfile.node-cache](https://github.com/kubernetes/dns/blob/master/Dockerfile.node-cache#L16)

would not fix the issue?

**Comment by prameshj** [comment]
Thanks for debugging this, Weston!

> Hi Wes Panther do I understand correctly that even removing this line:
> 
> `RUN update-alternatives --set ebtables /usr/sbin/ebtables-legacy`
> 
> in [Dockerfile.node-cache](https://github.com/kubernetes/dns/blob/master/Dockerfile.node-cache#L16)
> 
> would not fix the issue?

That is exactly what I tried, and removing that line did finish building successfully.  However, the ARM image is not able to run iptables.

1.18.0 works

```
docker run --rm -it --entrypoint=iptables k8s.gcr.io/dns/k8s-dns-node-cache-arm64:1.18.0
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
iptables v1.8.5 (legacy): no command specified
Try `iptables -h' or 'iptables --help' for more information.
```

1.18.1 does not

```
 docker run --rm -it --entrypoint=iptables gcr.io/pavithrar-k8s-dev/k8s-dns-node-cache-arm64:1.18.1-7-g80d4886-dirty
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: no such file or directory
```

Looks like this would break node-cache on other environments since the binary will invoke iptables to install the necessary rules. Looks like qemu should be added back, or is there any other recommendation on how this should work? @rikatz

**Comment by wespanther** [comment]
I would expect that for the same reasons if you run the arm image on your x86 host. Here it is on my machine without the `update-alternatives` line you mentioned

```
wpanther@wpanther ~/kubernetes/dns master ±# docker run --rm -it --entrypoint=iptables gcr.io/wpanther-gke-dev/k8s-dns-node-cache-arm:1.18.1-dirty
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: no such file or directory
```
After running `docker run --rm --privileged multiarch/qemu-user-static --reset -p yes` it works
```
 wpanther@wpanther ~/kubernetes/dns master ±# docker run --rm -it --entrypoint=iptables gcr.io/wpanther-gke-dev/k8s-dns-node-cache-arm:1.18.1-dirty
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64) and no specific platform was requested
iptables v1.8.5 (legacy): no command specified
Try `iptables -h' or 'iptables --help' for more information.
```
So if you need that line, you'll have to include the qemu binary so we can run the command. Otherwise, the image is built and it should run on arm successfully.

**Comment by prameshj** [comment]
Thanks Weston! @luigibk can you check if we can drop the ebtables line from the Dockerfile and still get the ebtables functionality? Maybe we need to modify $PATH or create a symlink. I guess any RUN command will have the same issue, so maybe the code needs to change the $PATH if ebtables setup is needed? Or we could restrict ebtables support to just amd64 and add a conditional in the Dockerfile.

**Comment by luigibk** [comment]
Thanks @wespanther 

@prameshj I am not really sure that code is needed anymore as Azure (AKS) now use a different CNI, see: [transparent CNI](https://github.com/Azure/AKS/issues/1954). That was my use case for it.
I like your idea of restricting ebtables support to amd64 and I would probably also deprecate it at this point as there is no support for it in ebtables-nft
What do you think?

**Comment by prameshj** [comment]
@luigibk deprecating support for ebtables sounds good to me. Would you be able to create an issue about it and tag all the relevant folks that you know might be using it?

Since it is an optional flag, I am wondering if we can remove support in a new minor version of node-cache right away? We could change the Dockerfile to support ebtables by copying qemu, but if it is not used anymore, I would rather keep the Makefile/Dockerfile simple.

**Comment by luigibk** [comment]
Hi @prameshj 

I've created an issue as you suggested: https://github.com/kubernetes/dns/issues/467

I've also created this: https://github.com/kubernetes/dns/pull/468 in case the decision is to remove the setupebtables option.

**Comment by prameshj** [comment]
1.19.0 tag has been cut with ebtables support removed. I will push the images by end of the week.
