### ISSUE TITLE
Deprecate/Remove setupebtables option in node-cache

### ISSUE THREAD

**Issue by luigibk** [kubernetes/dns#467]
Currently all images builds for architectures different from amd64 are failing at the following line:

`RUN update-alternatives --set ebtables /usr/sbin/ebtables-legacy`

in [Dockerfile.node-cache](https://github.com/kubernetes/dns/blob/master/Dockerfile.node-cache#L16)

this is due to the removal of qemu from the debian-base image see: [kubernetes/release PR-213](https://github.com/kubernetes/release/pull/2113).

The removal of that line would fix those builds. As the setupebtables option does not seem necessary anymore, since its main use case (Azure AKS) has now switched to a [transparent CNI](https://github.com/Azure/AKS/issues/1954) that does not need that option for node-cache to work, the following solutions are being considered:

1. Restrict the setupebtables to amd64 and deprecate it with the idea of removing it altogether in the near future
2. Remove the option without deprecation

This is also driven by the fact that ebtables-nft does not support the functionalities needed for that option to work.

Is that option still in use? is it worth supporting it for a while even if just for amd64?

The options was added to solve: [AKS-1642](https://github.com/Azure/AKS/issues/1642)

CC: @feiskyer, @saiyan86 and @timja

**Comment by prameshj** [comment]
@luigibk is there a slack channel where we can ask about this?

**Comment by luigibk** [comment]
@prameshj good question,  I'd say #provider-azure or #sig-network

**Comment by prameshj** [comment]
Thanks @luigibk , I posted on the 2 channels as well.

**Comment by luigibk** [comment]
Option 1 implemented

**Comment by prameshj** [comment]
@luigibk , you meant option2 right?
> Remove the option without deprecation

**Comment by luigibk** [comment]
> @luigibk , you meant option2 right?
> 
> > 1. Remove the option without deprecation

Yes, I did. Sorry!

**Comment by prameshj** [comment]
No worries.. thank you! We haven't really heard back from anyone in the past 2 days. I acknowledge it was short notice, but we do have support for ebtables upto image version 1.18.0, so hopefully that works. Thanks again @luigibk

**Comment by prameshj** [comment]
I will cut 1.19.0 tag later today.

**Comment by luigibk** [comment]
No worries. The new transparent CNI is really much better so I agree with you this was the right choice moving forward.

**Comment by prameshj** [comment]
> No worries. The new transparent CNI is really much better so I agree with you this was the right choice moving forward.

👍  I have just now cut 1.19.0 tag. Will push the images by end of the week.[](url)
