### ISSUE TITLE
Versioning schema

### ISSUE THREAD

**Issue by manuelbuil** [kubernetes/dns#474]
I'd like to understand what version I should use: https://github.com/kubernetes/dns/releases. 

When looking at the releases, it seems this project follows the Kubernetes versioning but if that is the case, I am missing several releases, e.g. 1.21.x

Thanks!

**Comment by prameshj** [comment]
The versions here do not map to kubernetes releases. There is no dependency on a particular k8s version, you could use any DNS version with any k8s version. 

Are you asking specifically about node-local-dns/node-cache?
You could use the latest one here - 1.20.0 which uses coreDNS 1.8.3 and upgraded to pick up latest debian-base vulnerability patches. 1.19.0 uses an older version of CoreDNS(1.7).

**Comment by manuelbuil** [comment]
> The versions here do not map to kubernetes releases. There is no dependency on a particular k8s version, you could use any DNS version with any k8s version.
> 
> Are you asking specifically about node-local-dns/node-cache?
> You could use the latest one here - 1.20.0 which uses coreDNS 1.8.3 and upgraded to pick up latest debian-base vulnerability patches. 1.19.0 uses an older version of CoreDNS(1.7).

Ok, thanks!
