### ISSUE TITLE
NodeLocal DNS version 1.21.0 fails to tear down interfaces on SIGTERM

### ISSUE THREAD

**Issue by rtheis** [kubernetes/dns#479]
NodeLocal DNS version 1.21.0 fails to tear down interfaces on SIGTERM

NodeLocal DNS version 1.21.0 logs on container termination
```
[INFO] SIGTERM: Shutting down servers then terminating
```

NodeLocal DNS version 1.20.0 logs on container termination
```
[INFO] SIGTERM: Shutting down servers then terminating
[INFO] Tearing down
[WARNING] Exiting iptables/interface check goroutine
```

NodeLocal DNS version 1.17.3 logs on container termination
```
[INFO] SIGTERM: Shutting down servers then terminating
[INFO] Tearing down
[WARNING] Exiting iptables/interface check goroutine
```

**Comment by Rustem05** [comment]
Dns

**Comment by Rustem05** [comment]
Intra

**Comment by Rustem05** [comment]
Dns intra

**Comment by prameshj** [comment]
Thanks for filing this! I was able to repro it by deleting a node-local-dns pod. Fix is in https://github.com/kubernetes/dns/pull/482

Please tag/assign issues to me, I get notified only for those. I noticed this almost a week late. Thanks again for catching this.

**Comment by rtheis** [comment]
@prameshj Thanks for the quick fix.  Do you have an eta on pushing the updated image to https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/us/dns/k8s-dns-node-cache?

**Comment by prameshj** [comment]
I am promoting it in https://github.com/kubernetes/k8s.io/pull/2759, the images will show up few minutes after the PR merges.

**Comment by prameshj** [comment]
/assign @rtheis 

Can you verify if this is fixed with the latest image? Thanks!

**Comment by rtheis** [comment]
Thanks folks.  I've verified this issue is now fixed.
