### ISSUE TITLE
Missing ready plugin on k8s-dns-node-cache

### ISSUE THREAD

**Issue by SataQiu** [kubernetes/dns#485]
The `ready` plugin is useful to check whether the server is ready.
Can we add `ready` to the plugin list on: 
https://github.com/kubernetes/dns/blob/master/cmd/node-cache/main.go?

**Comment by chrisohaver** [comment]
The _ready_ plugin interface (`Readiness`) is not implemented by any plugins used by k8s-dns-node-cache, so it would not serve any purpose (it would always report ready).

**Comment by prameshj** [comment]
Thanks Chris!

/assign @SataQiu 
Can this be closed?

**Comment by SataQiu** [comment]
Thanks @chrisohaver 
/close
