### ISSUE TITLE
gcr missing k8s-dns-node-cache release 1.19.1

### ISSUE THREAD

**Issue by sahilbadla** [kubernetes/dns#486]
Looks like k8s gcr is missing k8s-dns-node-cache release 1.19.1. All other releases are fine

```
docker pull k8s.gcr.io/dns/k8s-dns-node-cache:1.19.1     
Error response from daemon: manifest for k8s.gcr.io/dns/k8s-dns-node-cache:1.19.1 not found: manifest unknown: Failed to fetch "1.19.1" from request "/v2/dns/k8s-dns-node-cache/manifests/1.19.1".
```
/kind bug

**Comment by prameshj** [comment]
Good catch, based on the file history - https://github.com/kubernetes/k8s.io/commits/main/k8s.gcr.io/images/k8s-staging-dns, 1.19.1 was not pushed.  Promoting in https://github.com/kubernetes/k8s.io/pull/2878
