### ISSUE TITLE
Compatibility alignment with k8s releases

### ISSUE THREAD

**Issue by jcstanaway** [kubernetes/dns#487]
It is unclear if there is any type of version compatibility requirements between node-local-dns releases and k8s releases.

In the latest version of https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml it specifies 1.17.0. Is this just stale information?  Or is 1.17.0 the latest version that is compatible with k8s?

Or is expected that the latest version of node-local-dns can be used with any k8s release?

**Comment by jcstanaway** [comment]
@prameshj, is there a reason that https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml does not refer to the latest version of node-local-dns? This discrepancy is continuing to cause some confusion.

**Comment by prameshj** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/106189 to resolve this.

We just missed updating https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml , since that is only used by some CI tests. Good idea to update those.

**Comment by max-rocket-internet** [comment]
> we do not have a dependency on kubernetes/kubernetes in nodelocaldns.

@prameshj can I make a PR to update the README with this information?

**Comment by dpasiukevich** [comment]
> > we do not have a dependency on kubernetes/kubernetes in nodelocaldns.
> 
> @prameshj can I make a PR to update the README with this information?

@max-rocket-internet what information you'd like to add? That nodelocaldns version does not depend on K8S version? 

If yes, lgtm if the PR would help to avoid confusion.

**Comment by max-rocket-internet** [comment]
> That nodelocaldns version does not depend on K8S version?

Exactly: https://github.com/kubernetes/dns/pull/580
