### ISSUE TITLE
gcr missing k8s-dns-node-cache release 1.21.4

### ISSUE THREAD

**Issue by sarahhodne** [kubernetes/dns#499]
This looks similar to #486, it looks like 1.21.4 wasn't pushed correctly to GCR (but it looks like it was released, since there's a tag for it on the repo from over a week ago):

```
❯ docker pull k8s.gcr.io/dns/k8s-dns-node-cache:1.21.4
Error response from daemon: manifest for k8s.gcr.io/dns/k8s-dns-node-cache:1.21.4 not found: manifest unknown: Failed to fetch "1.21.4" from request "/v2/dns/k8s-dns-node-cache/manifests/1.21.4".
```

**Comment by prameshj** [comment]
This was done in https://github.com/kubernetes/k8s.io/pull/3267 last week. 

> docker pull k8s.gcr.io/dns/k8s-dns-node-cache:1.21.4 
worked now.
