### ISSUE TITLE
kubedns nslookup: can't resolve

### ISSUE THREAD

**Issue by githubvick** [kubernetes/dns#51]
I have successfully setup a Kube cluster and trying to setup KubeDNS.

Version:

kubectl version

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"86dc49aa137175378ac7fba7751c3d3e7f18e5fc", GitTreeState:"clean", BuildDate:"2016-12-15T16:57:18Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"86dc49aa137175378ac7fba7751c3d3e7f18e5fc", GitTreeState:"clean", BuildDate:"2016-12-15T16:57:18Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

When I deploy kubedns, I get this error in journalctl -xe

"Error syncing deployment kube-system/kube-dns-v20: Operation cannot be fulfilled on deployments.extensions "kube-dns-v20": the object has been modified; please apply your changes to the latest version and try again"

But didn't find enough info on that, so ignored it to atleast see where I could reach.

kubectl cluster-info

`Kubernetes master is running at http://192.168.6.101:8080 
KubeDNS is running at http://192.168.6.101:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns`

 mongodb and webapp are my pods

```
kubectl exec mongodb cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local     federated.fds
nameserver 10.254.0.2
nameserver 8.8.8.8
nameserver 8.8.4.4
options ndots:5

[osboxes@kubemaster kubernetes]$ kubectl exec webapp cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local federated.fds
nameserver 10.254.0.2
nameserver 8.8.8.8
nameserver 8.8.4.4
options ndots:5
```

on the master and node, in etc/kubernetes/config, I have this

```
ENABLE_CLUSTER_DNS="${KUBE_ENABLE_CLUSTER_DNS:-true}"
DNS_SERVER_IP="10.254.0.2"
DNS_DOMAIN="cluster.local"
DNS_REPLICAS=1
```

I have passed the required arguments in the node in kubelet on startup --cluster_dns=10.254.0.2 --cluster_domain=cluster.local

```
`kubectl exec webapp -- cat /etc/hosts
127.0.0.1   localhost
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
172.17.23.2 webapp`
```

When I do a nslookup on the container
```

kubectl exec -it webapp -- nslookup kubernetes.default.svc.cluster.local localhost
;; connection timed out; no servers could be reached

error: error executing remote command: error executing command in container: Error executing in Docker Container: 1

```

But this works,

```
kubectl --namespace=kube-system exec -ti kube-dns-v20-2502365070-2rmzl -c     kubedns --  nslookup kubernetes.default.svc.cluster.local localhost
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      kubernetes.default.svc.cluster.local
Address 1: 10.254.0.1 kubernetes.default.svc.cluster.local
```

No other errors in logs kubedns, dnsmasq or healthz. I can

**Comment by MrHohn** [comment]
I think neither `cluster.local` nor `kubernetes.cluster.local` is a valid name for DNS lookup. Your last input `kubernetes.default.svc.cluster.local` seems correct, though you are using `localhost` as the DNS server instead of kube-dns service's cluterIP.

**Comment by githubvick** [comment]
Hi MrHorn, yep. Just noticed that this worked, so closed the issue. If there is a way , maybe you can delete it. Sorry for the trouble 

kubectl exec -it webapp -- nslookup kubernetes.default.svc.cluster.local
Server:		10.254.0.2
Address:	10.254.0.2#53

Non-authoritative answer:
Name:	kubernetes.default.svc.cluster.local
Address: 10.254.0.1

**Comment by MrHohn** [comment]
No worry, glad you figured it out :)

For a pod in default namespace, you could also use these to query (we have default search paths configured):
- kubernetes
- kubernetes.default
- kubernetes.default.svc
