### ISSUE TITLE
images for s390x

### ISSUE THREAD

**Issue by XiLongZheng** [kubernetes/dns#52]
When will the dns images for s390x ready? Along with kubentetes 1.6.0 release?

**Comment by bowei** [comment]
Which images specifically?

**Comment by bowei** [comment]
Hmm -- I need some help in this area, would be great if someone with experience with s390x can get the dnsmasq s390x build working

**Comment by XiLongZheng** [comment]
I found the file dns/images/dnsmasq/Makefile already had s390x defined but not in ALL_ARCH definition. Also found build instruction for s390x on https://github.com/linux-on-ibm-z/docs/wiki/Building-kube-dnsmasq.

else ifeq ($(ARCH),s390x)
        BASEIMAGE ?=s390x/busybox:glibc
        TRIPLE    ?=s390x-linux-gnu
        QEMUARCH  :=s390x
else

**Comment by gajju26** [comment]
@bowei : I will look into dnsmasq s390x build working.

**Comment by gajju26** [comment]
Raised a PR (#56 ) for s390x build

**Comment by XiLongZheng** [comment]
When will it be ready? Thought kubernetes 1.6 code freeze is around the end of Feb, whether DNS will also have a release with kuberentes 1.6?

**Comment by bowei** [comment]
These have been pushed. I have a PR to update the version referenced in the cluster addons.

gcr.io/google_containers/k8s-dns-dnsmasq-s390x:1.13.0
gcr.io/google_containers/k8s-dns-sidecar-s390x:1.13.0
gcr.io/google_containers/k8s-dns-kube-dns-s390x:1.13.0

**Comment by bowei** [comment]
You can track the PR here: https://github.com/kubernetes/kubernetes/pull/41657

**Comment by bowei** [comment]
This should be resolved, reopen if not.
