### ISSUE TITLE
Container images for 1.22.6 missing 

### ISSUE THREAD

**Issue by yosshi825** [kubernetes/dns#536]
From the [release page](https://github.com/kubernetes/dns/tags), 1.22.6 has already been released, but I can't  pull image(registry.k8s.io/dns/k8s-dns-node-cache:1.22.6). Seems to be due to not being added to [images.yaml](https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-dns/images.yaml)

```
$ docker image pull registry.k8s.io/dns/k8s-dns-node-cache:1.22.6         
Error response from daemon: manifest for registry.k8s.io/dns/k8s-dns-node-cache:1.22.6 not found: manifest unknown: Failed to fetch "1.22.6" from request "/v2/dns/k8s-dns-node-cache/manifests/1.22.6".
```

ref 
- https://github.com/kubernetes/dns/issues/520

**Comment by dpasiukevich** [comment]
Thanks! I just didn't have time to promote the image. Was planning to do that this week.

**Comment by dpasiukevich** [comment]
https://github.com/kubernetes/k8s.io/pull/3993 is merged

**Comment by yosshi825** [comment]
@dpasiukevich
Thank you for releasing 1.22.6  and labeling the PR with `/ok-to-test`
Since it was merged, I can pull the image.

Thanks! 
```
$ docker image pull registry.k8s.io/dns/k8s-dns-node-cache:1.22.6
1.22.6: Pulling from dns/k8s-dns-node-cache
Digest: sha256:f71f2b3c4b55b8203b8cf6352a1c365ef0a364f3bffdcc64697069ba07f65fb3
Status: Image is up to date for registry.k8s.io/dns/k8s-dns-node-cache:1.22.6
registry.k8s.io/dns/k8s-dns-node-cache:1.22.6
```
