### ISSUE TITLE
NodeLocalDNS send finish flag before get answer

### ISSUE THREAD

**Issue by zvlb** [kubernetes/dns#538]
Sometimes i see strange error in NodeLocalDNS logs:
```
[ERROR] plugin/errors: 2 {{DOMAIN}}. SRV: read udp {{NODE_IP}}:51483->{{DNS_SERVER}}:53: i/o timeout
```

In TCPDump i see:
```
15:45:40.151621 IP {{NODE_IP}}.42761 > {{DNS_SERVER}}.domain: 51038+ SRV? {{DOMAIN}}. (50)
15:45:40.151777 IP {{DNS_SERVER}}.domain > {{NODE_IP}}.42761: 51038| 0/0/0 (50)
15:45:40.152005 IP {{NODE_IP}}.51483 > {{DNS_SERVER}}.domain: Flags [P.], seq 59:111, ack 1923, win 501, length 52 51038+ SRV? {{DOMAIN}}. (50)
15:45:40.152041 IP {{NODE_IP}}.51483 > {{DNS_SERVER}}.domain: Flags [F.], seq 111, ack 1923, win 501, length 0
15:45:40.152069 IP {{DNS_SERVER}}.domain > {{NODE_IP}}.51483: Flags [R], seq 1459978077, win 0, length 0
```

First 2 line - CoreDNS send UDP request for resolve domain, and DNS server answered: "Use TCP"
3 line -  CoreDNS send TCP request for resolve domain
4 line - CoreDNS send F flag (finish connection)
5 line - DNS server answer with R flag, bc CoreDNS send F flag (RESET connection)

I can't understand why NodeLocalDNS send F flag, before DNS server answered on resolv request

**Comment by dpasiukevich** [comment]
/remove-lifecycle stale

I'd deduplicates this in favor of https://github.com/coredns/coredns/issues/5541 as nodelocaldns only uses `forward` plugin with the default settings:

`forward . __PILLAR__UPSTREAM__SERVERS__`
