### ISSUE TITLE
Container images for 1.22.9 are missing

### ISSUE THREAD

**Issue by rtheis** [kubernetes/dns#541]
While https://github.com/kubernetes/dns/releases/tag/1.22.9 was released about a month ago, the associated release images have not been published to `registry.k8s.io/dns`.

**Comment by dpasiukevich** [comment]
Contents are the same as in the 1.22.8. I just released a new tag (lightweight 1.22.8 vs annotated 1.22.9) as previously there were always annotated tags and some CIs aren't set to work with lightweight.

I will still publish 1.22.9 along with the new 1.22.10 or 1.23.0 when it appears if you don't mind.
And 1.22.9 is the same as the 1.22.8

**Comment by rtheis** [comment]
Thank you
