### ISSUE TITLE
Flag to override TTL to never exceed X seconds?

### ISSUE THREAD

**Issue by jdub55** [kubernetes/dns#546]
Given the modern DNS implementations of multiple records, round robin and geo IP based lookups, is it possible to set a Max TTL value which will be enforced even if the upstream response returns something unusually high. We had a recent situation where an extremely large TTL value was cached and it was extremely difficult to track down. Having a maxTTL setting would help to ensure DNS lookups work as expected with modern applications and underlying IP changes. (e.g. a cached record in kube-dns should probably never have a TTL larger than 600 or 900 seconds)

**Comment by chrisohaver** [comment]
In kube-dns, this would be configurable in the dnsmasq sidecar.
In CoreDNS, this is configurable via the cache plugin.  The default CoreDNS max is configured to 30 seconds in most k8s deployments.

**Comment by dpasiukevich** [comment]
Yep, nodelocaldns also uses 30 sec for cache TTL.

As for kubedns it also returns 30 sec as TTL [source](https://github.com/kubernetes/dns/blob/a9693938be8c93b6f5e56fa7fc15784b082a9b96/pkg/dns/util/util.go#L41)

So it makes sense to set --max-cache-ttl=30 in the dnsmasq. The only thing that this option should not be hardcoded here in this repo but should be set when dnsmasq is started via configuration
