### ISSUE TITLE
Container images not available for v1.22.14/v1.22.15

### ISSUE THREAD

**Issue by stephan2012** [kubernetes/dns#553]
It looks like the container images for v1.22.14/v1.22.15 are not available at `registry.k8s.io/dns/k8s-dns-node-cache`. I also observed this issue for some previous versions. Is the registry the correct one or is the upload error-prone?

**Comment by dpasiukevich** [comment]
I didn't have time to promote these new tags.
I'd appreciate if you could do that. I will approve the PR worst case on Monday.

example: https://github.com/kubernetes/k8s.io/pull/4301
guide: https://github.com/kubernetes/dns/blob/master/README.md#release-process
starting from the step 8.
