### ISSUE TITLE
Kubernetes Plugin returns NoError for TXT queries for non-existent domains

### ISSUE THREAD

**Issue by adammw** [kubernetes/dns#555]
Kubernetes Plugin returns NoError for TXT queries for all domains including non-existent domains, resulting in DNS queries using multiple ndots candidates being accepted in the Kubernetes with no records returned instead of passed on to the next candidate.

**Comment by adammw** [comment]
Wrong repo. 😅

**Comment by chrisohaver** [comment]
See https://github.com/coredns/coredns/issues/5736 and PR in progress: https://github.com/coredns/coredns/pull/5737

**Comment by adammw** [comment]
Way ahead of me. Thanks!
