### ISSUE TITLE
[makefile] make build don't work correct

### ISSUE THREAD

**Issue by wondywang** [kubernetes/dns#558]
**What steps did you take and what happened:**

whenI use the latest code to build node-cache, throwing an exception.
```bash
$make containers CONTAINER_BINARIES=node-cache
```

The output looks like:
```bash
building : bin/amd64/node-cache
1.18-bullseye: Pulling from library/golang
Digest: sha256:4902830c8b7a79f71479ec17aa3e302cef3c89372e6701ca9bb98e29653031cb
Status: Image is up to date for golang:1.18-bullseye
docker.io/library/golang:1.18-bullseye
container: bin/amd64/node-cache (gcr.io/k8s-staging-dns/k8s-dns-node-cache-amd64)
WARN[0000] quiet currently not implemented
[+] Building 3.1s (7/7) FINISHED
 => [internal] load build definition from .node-cache-amd64-dockerfile                                        0.0s
 => => transferring dockerfile: 50B                                                                           0.0s
 => [internal] load .dockerignore                                                                             0.0s
 => => transferring context: 2B                                                                               0.0s
 => [internal] load metadata for gcr.io/gke-release/distroless-iptables:v0.1.2-gke.1                          0.8s
 => [1/2] FROM gcr.io/gke-release/distroless-iptables:v0.1.2-gke.1@sha256:61127e36554627460fc3c853f58e7b38bc  0.0s
 => [internal] load build context                                                                             2.1s
 => => transferring context: 48.52MB                                                                          2.1s
 => CACHED [2/2] ADD bin/amd64/node-cache /node-cache                                                         0.0s
 => exporting to image                                                                                        0.0s
 => => exporting layers                                                                                       0.0s
 => => writing image sha256:c5b2995ac81dd5e254440af43edb26a4638b28902aaa1420d15ec77cf46a021a                  0.0s
 => => naming to gcr.io/k8s-staging-dns/k8s-dns-node-cache-amd64:1.22.15-4-g390fca7d                          0.0s
building : _output/amd64/docker/dnsmasq
bullseye-v1.4.1: Pulling from build-image/debian-base-amd64
Digest: sha256:a74834abd9ef451a735aab8740a2bbac335a14e9c9076115eaa21e384485a14a
Status: Image is up to date for k8s.gcr.io/build-image/debian-base-amd64:bullseye-v1.4.1
k8s.gcr.io/build-image/debian-base-amd64:bullseye-v1.4.1
make[3]: *** [_output/amd64/docker/dnsmasq] Error 2
make[2]: *** [containers-dnsmasq] Error 2
make[1]: *** [containers] Error 2
make: *** [images-containers] Error 2
```

**Environment:**
go version: go1.19.2 darwin/amd64
OS (e.g: cat /etc/os-release): Mac

**Comment by dpasiukevich** [comment]
My output on "Debian GNU/Linux"

```
building : bin/amd64/node-cache
1.18-bullseye: Pulling from library/golang
Digest: sha256:4902830c8b7a79f71479ec17aa3e302cef3c89372e6701ca9bb98e29653031cb
Status: Image is up to date for golang:1.18-bullseye
docker.io/library/golang:1.18-bullseye
generating Dockerfile .node-cache-amd64-dockerfile from Dockerfile.node-cache
container: bin/amd64/node-cache (gcr.io/k8s-staging-dns/k8s-dns-node-cache-amd64)
```

What is your .node-cache-amd64-dockerfile?

Mine is:
```
FROM gcr.io/gke-release/distroless-iptables:v0.1.2-gke.1
ADD bin/amd64/node-cache /node-cache
EXPOSE 53 53/udp
EXPOSE 53 53/tcp
ENTRYPOINT ["/node-cache"]
```

**Comment by dpasiukevich** [comment]
Also, you note that `docker buildx build` is used.

If .node-cache-amd64-dockerfile is generated correctly (the same as I pasted above)
You can try to run build command manually
https://github.com/kubernetes/dns/blob/390fca7d8248131d18c694d0e5caa283f5d01a5f/rules.mk#L144

e.g.
```
buildx build					\
		--platform linux/$(ARCH)			\
		-t $(CONTAINER_NAME):$(VERSION)		\
		-f .node-cache-amd64-dockerfile .
```

example params:
CONTAINER_NAME=gcr.io/k8s-staging-dns/k8s-dns-node-cache-amd64
VERSION=1.22.15
ARCH=amd64

**Comment by dpasiukevich** [comment]
Btw, I've also noticed in your output the command tries to build `dnsmasq` but you explicitly set `node-cache`

1. Could you confirm that running `make containers CONTAINER_BINARIES=node-cache` also tries to build `dnsmasq`?
2. Could you manually build `node-cache` image (as shown in the comment above) and show the output if the build fails?

**Comment by wondywang** [comment]
> My output on "Debian GNU/Linux"
> 
> ```
> building : bin/amd64/node-cache
> 1.18-bullseye: Pulling from library/golang
> Digest: sha256:4902830c8b7a79f71479ec17aa3e302cef3c89372e6701ca9bb98e29653031cb
> Status: Image is up to date for golang:1.18-bullseye
> docker.io/library/golang:1.18-bullseye
> generating Dockerfile .node-cache-amd64-dockerfile from Dockerfile.node-cache
> container: bin/amd64/node-cache (gcr.io/k8s-staging-dns/k8s-dns-node-cache-amd64)
> ```
> 
> What is your .node-cache-amd64-dockerfile?
> 
> Mine is:
> 
> ```
> FROM gcr.io/gke-release/distroless-iptables:v0.1.2-gke.1
> ADD bin/amd64/node-cache /node-cache
> EXPOSE 53 53/udp
> EXPOSE 53 53/tcp
> ENTRYPOINT ["/node-cache"]
> ```

My `.node-cache-amd64-dockerfile` output is the same as yours.

**Comment by wondywang** [comment]
> 

Yes, I confirm. 
1. when I run `make containers CONTAINER_BINARIES=node-cache`, it also tries to build dnsmasq (as shown above).
2. when I manually build node-cache image, it's ok. 
```bash
docker buildx build  --platform linux/amd64 -t gcr.io/k8s-staging-dns/k8s-dns-node-cache-amd64:1.22.15 -f .node-cache-amd64-dockerfile .
```

output:
```bash
$ docker buildx build  --platform linux/amd64 -t gcr.io/k8s-staging-dns/k8s-dns-node-cache-amd64:1.22.15 -f .node-cache-amd64-dockerfile .
[+] Building 4.4s (7/7) FINISHED
 => [internal] load build definition from .node-cache-amd64-dockerfile                                        0.1s
 => => transferring dockerfile: 800B                                                                          0.0s
 => [internal] load .dockerignore                                                                             0.0s
 => => transferring context: 2B                                                                               0.0s
 => [internal] load metadata for gcr.io/gke-release/distroless-iptables:v0.1.2-gke.1                          1.3s
 => [1/2] FROM gcr.io/gke-release/distroless-iptables:v0.1.2-gke.1@sha256:61127e36554627460fc3c853f58e7b38bc  0.0s
 => [internal] load build context                                                                             2.7s
 => => transferring context: 48.52MB                                                                          2.7s
 => CACHED [2/2] ADD bin/amd64/node-cache /node-cache                                                         0.0s
 => exporting to image                                                                                        0.0s
 => => exporting layers                                                                                       0.0s
 => => writing image sha256:c5b2995ac81dd5e254440af43edb26a4638b28902aaa1420d15ec77cf46a021a                  0.0s
 => => naming to gcr.io/k8s-staging-dns/k8s-dns-node-cache-amd64:1.22.15                                      0.0s
```

**Comment by dpasiukevich** [comment]
Ok, due to `containers: $(CONTAINER_BUILDSTAMPS) images-containers` in [rules.mk](https://github.com/kubernetes/dns/blob/a5658d8ec4cb0dc7f754b5f918920070248eb043/rules.mk#L156) it will always try to run `make containers` recursively in each subdir of ./images

I'd like to see why it's failing.

Could you run: `cd images/dnsmasq && rm -rf _output && VERBOSE=1 make containers` to see why the build is failing?

**Comment by wondywang** [comment]
I found that building on the Linux platform has no problem. It's just that building on my local Mac will also tries to build dnsmasq. Then, I succeeded this time.

And when I run `cd images/dnsmasq && rm -rf _output && VERBOSE=1 make containers`, output like this:
```bash
make: sha256sum: No such file or directory
make: *** [_output/amd64/dnsmasq.tar.xz] Error 1
```

Maybe is this a special case for me?

**Comment by dpasiukevich** [comment]
Looks like you don't have a sha256sum binary. It's used to verify downloaded dnsmasq archive.

So to fix your problem right away - just install sha256sum.

On the other hand `make containers CONTAINER_BINARIES=node-cache` should just build node-cache. And not try to build dnsmasq as it's unrelated to the node-cache. So a correct solution is to update `rules.mk` to invoke all `images-*` commands only if `CONTAINER_BINARIES` contain `dnsmasq-nanny`. Because only dnsmasq-nanny depends on the dnsmasq.

**Comment by wondywang** [comment]
Thanks dpasiukevich :tulip: :tulip:, and I will close this issue.
