### ISSUE TITLE
Add comments to iptables rules to indicate where they came from

### ISSUE THREAD

**Issue by 2rs2ts** [kubernetes/dns#566]
At my company, in order to make it easier to pass security audits, we automatically scrape iptables rules from our hosts and put them into a big spreadsheet, and we use comments as the mechanism for explaining why a rule is there. Since adding the NodeLocal DNSCache app, our scraped results now contain some rules without comments, which of course raises some eyebrows. We could add something custom to fill in comments after the cache app starts up, but we think it's not a lot to ask to have the cache app include the comments itself.

I may take a crack at this myself when I have the time, but I'm filing the issue first so that it can be tracked, and also to give an opportunity for anyone to speak up if they think this is a bad idea for some reason.

**Comment by dpasiukevich** [comment]
In general, the idea to add comments for the iptables rules seems ok to me.

But I believe, having the comment in this repo will not work for your use-case (in the long run):
1. Comment format may be different for the requirements for security audits in your company and between the format we may use in this repo.
2. Even if they would be aligned and the same right now, they may change in the future (either your requirements change or there could be changes in this repo)

Both options would result in that eventually you'd have to make an adapter in your company's codebase to produce comments in the desired format.

So you can just make an adapter in your codebase right now without modifying the repo. Or you could add comments for iptables here. The comments should be intuitive (e.g. moving code comments to iptables comments with minor adjustments if needed).
Both options LGTM.

**Comment by 2rs2ts** [comment]
@dpasiukevich Honestly, if all it said was "NodeLocal DNSCache" or something extremely basic that indicated where it was coming from, that would do us a lot of favors. And, I think it would help a lot of other people debugging their systems, too. Take for example Calico's iptables comments: they aren't super useful (they're not even human readable, they're just like, `cali<workload name>`, but at least they let you the rules are created by Calico!

Of course, more elaborate comments would be nice, but like you said, things can change over time. People may want to reword things. Our company will be flexible and allow for changes to occur over time. As long as we can still tell that the rules came from this app, then we are happy. If we have to write an adapter to satisfy new auditing rules, so be it, but that's unlikely for us.

Now, for other users, I am less sure. But I do think that any comment makes it easier to find the firewall rule and either edit it in a `postStart` hook, or have your auditing software do a transformation during its report, than having no comment at all.
