### ISSUE TITLE
Broken link in the readme

### ISSUE THREAD

**Issue by rafalkrupinski** [kubernetes/dns#581]
https://github.com/kubernetes/dns/blob/5b640bba8e25e867f27b77db0d5abf54c9585b71/README.md?plain=1#L7

The link https://kubernetes.io/docs/admin/dns/ returns 404 not found, althou it's neatly hidden in the tab title.

I guess [this link](https://kubernetes.io/docs/tasks/access-application-cluster/configure-dns-cluster/) would be valid, but someone please check.

**Comment by dpasiukevich** [comment]
Thanks for spotting that!

The suggested link LGTM. 
I'd only update the link text to be [Kubernetes DNS (kube-dns and nodelocaldns)](...link here...)

@rafalkrupinski would it be ok for you to make a small PR for that?
