### ISSUE TITLE
`CoreDNS` pod deployment specification

### ISSUE THREAD

**Issue by Zhenye-Na** [kubernetes/dns#582]
### Problem Statement

Is there any specific ordering mechanism that Kubernetes select node/instance to deploy the `CoreDNS` pod to ?

### Context

I am using AWS EKS as the service provider to create a cluster. In the domain of AWS EKS service, there are

- EKS Managed Node Group, which AWS EKS team provision and manage the Kubernetes worker nodes
- EKS Self-managed Nodes, which customer themselves provision and managed the worker nodes

I have noticed that it seems like `CoreDNS` pods are "randomly" assigned to worker nodes. So I am wondering is there any mechanisms that I could configure in Kubernetes level, to see `CoreDNS` always go to some worker nodes ?

Thanks

**Comment by johnbelamaric** [comment]
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

But it requires that EKS gives you some access to the deployment for CoreDNS.

/close

**Comment by johnbelamaric** [comment]
Closed since this is an EKS-specific issue, not directly K8s DNS related.
