### ISSUE TITLE
Image for 1.22.27 missing

### ISSUE THREAD

**Issue by Christoph-Raab** [kubernetes/dns#613]
Release 1.22.27 has been release last week, containing some important security fixes. 

Sadly the image has not been made available. [Last time I checked](https://github.com/kubernetes/dns/issues/579) I'd need a google cloud account to access the information required for that. I can't set this up on my workstation, since we don't use google cloud.

Would be great if you could release that rather soon. If the gcloud account isn't necessary anymore I'm happy to open a PR.

**Comment by alk-jozog** [comment]
Same issue with 1.22.28 now

**Comment by vardhaman22** [comment]
1.22.27 images seems to be available now but there is an issue with 1.22.28 now.

**Comment by Christoph-Raab** [comment]
I'll close this one since the maintainers don't seam to really care. 

IMO there should be some sort of automation for publishing images on release. But that's probably something for a different issue.
