### ISSUE TITLE
1.23.0 is missing from registry.k8s.io/dns/k8s-dns-node-cache

### ISSUE THREAD

**Issue by rgdev** [kubernetes/dns#624]
Tag 1.23.0 seems to be missing from the official container repository despite being referenced [here](https://github.com/kubernetes/kubernetes/blob/756628b3a85f0cbc5850c79ac05651371ead11dc/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml#L141)

```
docker pull registry.k8s.io/dns/k8s-dns-node-cache:1.23.0
Error response from daemon: manifest for registry.k8s.io/dns/k8s-dns-node-cache:1.23.0 not found: manifest unknown: Failed to fetch "1.23.0"
```

**Comment by liangyuanpeng** [comment]
This PR is working for it. https://github.com/kubernetes/k8s.io/pull/6500

**Comment by mubarak-j** [comment]
@liangyuanpeng the latest version `1.23.1` is now missing
