### ISSUE TITLE
KubeDNS consistently dies

### ISSUE THREAD

**Issue by Agrosis** [kubernetes/dns#65]
Hi there! I'm running a vanilla Kubernetes v1.5.1 cluster inside VirtualBox with a flannel overlay network. All of that worked perfectly, so I decided to get cluster DNS working today.

I'm having a couple of issues here. First off is sometimes when KubeDNS starts it can't reach the apiserver. I have to restart it a couple of times before it reaches it correctly. The second problem is that the service seems to stop serving DNS and stop responding to the health checks, so I have to restart it again. The dnsmasq container seems to be fine, but I get this error message on the KubeDNS container around when things stop working:

```
Ignoring signal terminated (can only be terminated by SIGKILL)
```

KubeDNS does work for a couple of minutes at a time, but only for a couple of minutes.

Its gotten kind of frustrating and I've tried to hunt down any docs. I'm not pasting any logs in this issue because there's so much to sift through, so any ideas on where to start?

**Comment by bowei** [comment]
This sounds like an issue with flannel connectivity.

kube-dns runs a set of health checks to both dnsmasq and the kube-dns component. If these health checks fail repeatedly, then the pod will be restarted. What I would do is run tcpdump and netcat to see if your packets are being delivered properly.

Regarding the SIGKILL, the behavior is to enable a graceful termination of the DNS service. When the pod is being torn-down, the service is first removed from the cluster IP VIP and sent a SIGTERM, then after the graceful termination period, a SIGKILL is sent.

**Comment by Agrosis** [comment]
It does seem like there's an issue with flannel. When KubeDNS starts on a non-master node, it can't hit the apiserver, which explains my first problem. I'll try to get that fixed up first, and see if that resolves the second problem.

**Comment by Agrosis** [comment]
So it seems like pods without host networking can communicate fine across the overlay network, but pods on worker machines can't hit pods that run use hostNetwork on the master. I'll just force the kubedns pod to run on the master for now until I can figure something else out.

**Comment by Agrosis** [comment]
I managed to find https://github.com/kubernetes-incubator/kargo/issues/258 and setting `advertise-address` on the kube-apiserver fixed the problem where a pod on the node couldn't hit the apiserver on the master.

Its still failing health checks, so I'll get to fixing that.

**Comment by Agrosis** [comment]
Well, I figured out the second problem. The liveness health check for the kubedns pod is executed on a port that's exposed for sidecar, which I had commented out when I was trying to debug the first problem. So the request was timing out and that's why it was consistently being restarted. Thanks for the help!
