### ISSUE TITLE
kubedns dnsmasq pod fails with blank IP for the DNS host

### ISSUE THREAD

**Issue by sgmiller** [kubernetes/dns#66]
Can't get a cluster started using kubeadm on v1.6.0-beta1 (kube-dns v1.14.1).  The dnsmasq pod fails with:
```
I0308 16:30:25.353537       1 nanny.go:108] dnsmasq[11]: bad address at /etc/hosts line 7
I0308 16:30:25.353540       1 nanny.go:108] dnsmasq[11]: read /etc/hosts - 6 addresses
```

/etc/hosts contains:

```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
	kube-dns-1630391940-grt67
```
So presumably it can't get the information it needs from the ConfigMap?

**Comment by MrHohn** [comment]
kube-dns ConfgiMap won't affect `/etc/hosts` file. Instead, kubelet is responsible to setting the hosts file up (https://github.com/kubernetes/kubernetes/blob/c3d7ee11d176d94108831bed2e76e94039338fd2/pkg/kubelet/kubelet_pods.go#L186-L207).

And seems like you've got a empty pod IP for this kube-dns pod. Can you also check the output of `$ kubectl get pods KUBE_DNS_POD_NAME --namespace=kube-system -o yaml`? Are the other pods having the same issue?

It would be helpful if you could also check kubeclet's logs on the node where kube-dns pod is on.

**Comment by sgmiller** [comment]
I see.  Other pods don't seem to have this problem.  Looking on kube-proxy for example has a complete hosts file.

The kube-dns pod's yaml is attached.
[kube-dns.txt](https://github.com/kubernetes/dns/files/828520/kube-dns.txt)

**Comment by sgmiller** [comment]
This line from syslog on the master (the only node so far) is interesting:

 NetworkPlugin cni failed on the status hook for pod "kube-dns-1630391940-bnl7d_kube-system": Unexpected command output Device "eth0" does not exist.

**Comment by sgmiller** [comment]
And indeed, ifconfig in the kubedns container has only "lo":

```
# kubectl exec kube-dns-1630391940-bnl7d -c kubedns ifconfig
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:732 errors:0 dropped:0 overruns:0 frame:0
          TX packets:732 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:64918 (63.3 KiB)  TX bytes:64918 (63.3 KiB)
```

**Comment by MrHohn** [comment]
Hmm, could you check other pods that are not using hostNetwork (kube-proxy set hostNetwork=true)? From your yaml file it seems like it does not have podIP allocated. I wonder is the underlying network broken?

Here is a similar issue: https://github.com/projectcalico/calicoctl/issues/1407

**Comment by MrHohn** [comment]
Yeah, it was trying to reach the apiserver through the default kubernetes service but failed.

Not sure how kubeadm set this up, but as I know kube-dns either use the kubecfg file specified by `--kubecfg-file` and `kube-master-url` flags or use the env vars (KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT, which should be set up automatically when pod is created) as the configurations when creating its k8s client.

**Comment by sgmiller** [comment]
Its the env vars, and they're wrong.  What controls setting those?

**Comment by MrHohn** [comment]
These values are piped into kubelet through `--kubeconfig` or `--api-servers` flags.

I'm not pretty sure if the real issue is about "incorrect kubernetes service IP/port" or not. Feel like there may be some mechanism in kubeadm I misunderstood. You may want to open an issue against kubeadm to seek for the real root cause.

**Comment by MrHohn** [comment]
Oops, looks like I am wrong. Those env vars are generated from services themselves but not from flags:
https://github.com/kubernetes/kubernetes/blob/c3d7ee11d176d94108831bed2e76e94039338fd2/pkg/kubelet/kubelet_pods.go#L389
https://github.com/kubernetes/kubernetes/blob/c3d7ee11d176d94108831bed2e76e94039338fd2/pkg/kubelet/envvars/envvars.go#L27-L60

**Comment by sgmiller** [comment]
I agree, I don't think kube-dns has anything to do with this, closing.
