### ISSUE TITLE
Unable to pull the image for dns/k8s-dns-node-cache:1.24.0

### ISSUE THREAD

**Issue by shashank-shridhar** [kubernetes/dns#662]
Hello, I'm trying to pull the image for dns/k8s-dns-node-cache:1.24.0 through the command:

docker pull registry.k8s.io/dns/k8s-dns-node-cache:1.24.0

However, I am facing the following issue:

~ % docker pull registry.k8s.io/dns/k8s-dns-node-cache:1.24.0
Error response from daemon: failed to resolve reference "registry.k8s.io/dns/k8s-dns-node-cache:1.24.0": registry.k8s.io/dns/k8s-dns-node-cache:1.24.0: not found

Can someone help me out here? Thanks in advance!

**Comment by DamianSawicki** [comment]
We are in the process of releasing `1.24.0`. The above command won't work until https://github.com/kubernetes/k8s.io/pull/7607 is merged.

**Comment by shashank-shridhar** [comment]
Thank you @DamianSawicki for the comment; will wait for the merge then :)

**Comment by DamianSawicki** [comment]
@shashank-shridhar It works already :) Please check on your end and confirm.

**Comment by shashank-shridhar** [comment]
Thank you so much @DamianSawicki , I'm able to pull the image. With this we can close the issue. Thanks again!
