### ISSUE TITLE
Federations config should work with or without trailing dots in the zone names

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/dns#67]
`Federations` config either passed through a flag or a ConfigMap is validated to ensure that the zone names (the domain name suffix) are valid [RFC 1123](https://tools.ietf.org/html/rfc1123) subdomain names. Most DNS zone configurations take a trailing dot in their configuration, but the regex we use in `kube-dns` has a format that does not match trailing dots. This mismatch is a cognitive overhead for our users. We should just accept zone names in `Federations` config with or without trailing dots.

**Comment by perotinus** [comment]
Does this back us into any corners or make things harder in the future? If we're more liberal with what we accept now, will that mean that in the future we'll have to break people by becoming more restrictive and requiring the dot?

(I don't know enough about DNS names to be sure, but it seems like it could be significant.)

**Comment by madhusudancs** [comment]
I don't see a future where we will require dots. Someone might push back on changing the current state of things, that is requiring to not have a dot. However, I don't see a reason to make that a requirement.
