### ISSUE TITLE
Error with pod hostname query

### ISSUE THREAD

**Issue by bowei** [kubernetes/dns#70]
Query for the `<pod-hostname>.<ns>.pods.cluster.local` is not returning the A record for the pod

```
/ # dig customer-deployment-onuwixzygi4tkn3fgztgeylfgnrdm-62180010musmy.staging.pod.cluster.local.
```

kube-dns logs
```
I0316 16:18:30.889074       1 logs.go:41] skydns: error from backend: Invalid IP Address customer.deployment.onuwixzygi4tkn3fgztgeylfgnrdm.62180010musmy
```

**Comment by thockin** [comment]
Unless I misunderstand, we don't support that query, on purpose.  We don't want DNS to have to watch all pods.

**Comment by exarkun** [comment]
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ led me to believe this would work.  However, a more careful re-reading now suggests that I probably combined information from a few different section - like the "Pods / A Records" section and the "A Records and hostname based on Pod’s hostname and subdomain fields" section - and invented the idea that this style hostname would  work when the document doesn't appear to actually say this.

**Comment by bowei** [comment]
yeah -- brain fart on my part -- we should fix the documentation however, I don't think it's very clear

**Comment by seh** [comment]
If I understand the documentation correctly, so long as a headless _Service_ named with the subdomain exists in the same namespace as the pods, _kube-dns_ should publish A records for the pods. I find that this works only if the _Service_ defines **at least one port**, even though [the documentation says](https://github.com/kubernetes/website/blame/master/docs/concepts/services-networking/dns-pod-service.md#L109), "Actually, no port is needed."

Is the documentation wrong here, and a port should be required, or is this a defect in the implementation?

**Comment by thockin** [comment]
I think it should work without ports.  File a new bug please, with a simple
repro?

On Tue, Oct 24, 2017 at 10:13 AM, Steven E. Harris <notifications@github.com

**Comment by seh** [comment]
@thockin, please see #174.
