### ISSUE TITLE
dnsmasq --server flags causing upstream name server calls to hang and time out sporadically

### ISSUE THREAD

**Issue by michaelajr** [kubernetes/dns#76]
Hello. I had a problem recently where external name resolution, E.g., `www.google.com`, would not resolve. From the perspective of the client (`nslookup`) the call would just time out. From looking at the `dnsmasq` logs, it appears the calls were hanging. Every now and then… they would work… and cache.  Once the TTL expired… they would fail… and then sporadically work and cache again. 

I validated that calls directly to the upstream nameserver worked fine, E.g., `nslookup www.google.com <NAME_SERVER_IP>`. If fact, they never failed. I tested this from inside a pod, and on the host where the upstream name servers are configured in `~/etc/resolv.conf`. I then tried configuring the name servers using the new `ConfigMap`. Same result. 

Odd thing was, this only happened in the `1.6.x` release of K8s. Not the `1.5.4` release that we are currently using. 

I looked at the `dnsmasq` flags in the 1.6.x release and noticed there were three `--server` flags:

```
--server=/cluster.local/127.0.0.1#10053
--server=/in-addr.arpa/127.0.0.1#10053
--server=/in6.arpa/127.0.0.1#10053
```

As opposed to s single server flag in the 1.5.4 release, that just references the `kubedns` address.

```
--server=127.0.0.1#10053
```

I removed the three `--server` flags, and replaced them with the single `--server` flag which simply referenced the `kubedns` ... and suddenly everything worked!

I do not understand what those three server flags are doing differently from the single one (stubDoamins?) but they DID NOT WORK when trying to resolve names outside the cluster.

Again the workaround was to just remove them and replace them with one server flag referencing `kubedns`. 

My cluster was created using `kops 1.6.0-alpha2`. Tagging @justinsb 

Let me know if you need any other information. 

Thanks.
M

UPDATE:  Also, cluster name lookups ALWAYS worked. Regardless of number of dots. E.g., `kubernetes`, or `kubernetes.default`, or `kubernetes.detault.svc`, etc. No issues there.

**Comment by bowei** [comment]
In 1.6, dnsmasq will only forward requests that pertain to cluster.local (and reverse record lookups) to kube-dns. All other requests will go out directly to the upstream resolver.

Can you post your /etc/resolv.conf from the container?

**Comment by michaelajr** [comment]
Sorry I did not see this sooner. The etc resolv.conf in the dnsmasq container is the same as the host's ```nameserver 10.236.129.75
nameserver 10.236.129.85```

These are our VPC name servers. The work fine from this host and inside the dnsmasq container:
```# nslookup www.google.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      www.google.com
Address 1: 172.217.5.228 iad30s07-in-f4.1e100.net
Address 2: 2607:f8b0:4004:804::2004 iad30s07-in-x04.1e100.net```

**Comment by bowei** [comment]
That nslookup looks to be correct -- the first `(null)` is a the result of a reverse lookup for the nameserver itself.

Is it possible to `tcpdump -i any -n port 53` on the kube-dns pod node to see what packets are being sent?
