### ISSUE TITLE
use flannel and add-on kube-dns， but kube-dns don't work

### ISSUE THREAD

**Issue by wadee** [kubernetes/dns#77]
####here is my procedure of setup kube cluster：
* system env: 
	* HypriotOS (Debian GNU/Linux 8)
	* use wifi iface wlan0
        * kube version:
![image](https://cloud.githubusercontent.com/assets/2749943/25163642/6bc6e414-24fe-11e7-98c3-8849b9f13cc2.png)

	
* 	On master
	* kubeadm init --pod-network-cidr 10.244.0.0/16 --apiserver-advertise-address 192.168.31.199
	* kubectl create -f kube-flannel-rbac.yml
	* kubectl create --namespace kube-system -f kube-flannel.yml
		* specially node use wifi for connected, so i modify the kube-flannel.yml configure params as below：
```
image: quay.io/coreos/flannel:v0.7.0-arm
command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr", "--iface=wlan0"]
```

* On slaves
	* kubeadm join --token 8bbadd.3a118002a3e82964 192.168.31.199:6443

* On each node (include master)
	* use the flannel subnet.env /run/flannel/subnet.env config to restart dockerd, a example as below :
```
FLANNEL_NETWORK=10.244.0.0/16
FLANNEL_SUBNET=10.244.2.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```
	*  so dockerd is run as : /usr/bin/dockerd --bip=10.244.2.1/24 --ip-masq=false --mtu=1450 --storage-driver overlay -H fd://		

#### question
![image](https://cloud.githubusercontent.com/assets/2749943/25163307/cf5aaa72-24fb-11e7-9e10-fcf864e7c03c.png)

upon the  above screenshots, you will notice that the kube-dns at the colunm 'ready' is always 2/3,

and kube-dns pod include 3 container： kubedns , dnsmaqs ,carside

there is logs about the kubedns container:
 
![image](https://cloud.githubusercontent.com/assets/2749943/25163390/87d0a0ca-24fc-11e7-8f48-07720e571ced.png)

so, the kube-dns pod just keep restart over and over again。

I have been struggling wiht this problem for a couple day........

is that any mistake I have make lead to this problem?
can anyone have the same issue?

**Comment by Blfrg** [comment]
I recently resolved the same issue, however I use canal (calico+flannel) on standard kubernetes hyperkube (no kubeadm) on CoreOS (Container Linux). This is likely a k8s/flannel issue and not a kube-dns issue.

Flannel is in the process of merging with calico (combined = canal), so I recommend checking it out if possible for your environment. Canal has a [kubeadm specific install](https://github.com/projectcalico/canal/tree/master/k8s-install/kubeadm) and additional info on the [calico site](http://docs.projectcalico.org/v2.1/getting-started/kubernetes/installation/hosted/kubeadm/). This is more simplified than the original flannel instructions, and is now fully instantiated from within kubernetes itself (no having to tweak docker).

_Note the different 1.5 and 1.6 install guides and files. Don't forget to update the iface in your case._

For my resolution ([self/standard hosted install](https://github.com/projectcalico/canal/tree/master/k8s-install)), I upgraded the canal images to their latest whole versions found on [quay.io/organization/calico](https://quay.io/organization/calico). The kubeadm specific install appears to use the latest image versions already with the exception of calico/node:v1.1.0 => v1.1.1 (though it may not be necessary to update it).

I hope that helps or leads you to more helpful information.

**Comment by wadee** [comment]
@Blfrg appreciate your reply,I will try it out soon！！

**Comment by cmluciano** [comment]
@wadee Can you please post the details on how you install flannel? Did you grab the latest from master?

**Comment by wadee** [comment]
@cmluciano sorry for replying so late ……

kubectl create --namespace kube-system -f kube-flannel.yml
and I modify the attrs as below:

image: quay.io/coreos/flannel:v0.7.0-arm
command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr", "--iface=wlan0"]

and i am sure that flannel:v0.7.0-arm is the latest flannel for the arm-system.

and here is the whole deploy file:
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "type": "flannel",
      "delegate": {
        "isDefaultGateway": true
      }
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
  namespace: kube-system
  labels:
    tier: node
    app: flannel
spec:
  template:
    metadata:
      labels:
        tier: node
        app: flannel
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: arm
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: flannel
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.7.0-arm
        command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr", "--iface=wlan0"]
        securityContext:
          privileged: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: run
          mountPath: /run
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      - name: install-cni
        image: quay.io/coreos/flannel:v0.7.0-arm
        command: [ "/bin/sh", "-c", "set -e -x; cp -f /etc/kube-flannel/cni-conf.json /etc/cni/net.d/10-flannel.conf; while true; do sleep 3600; done" ]
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
        - name: run
          hostPath:
            path: /run
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: flannel-cfg
          configMap:
            name: kube-flannel-cfg

**Comment by cmluciano** [comment]
Your deployment seems similar to [flannel's latest example](https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml), with the exception of the arm platform reference and a custom iface. 

Can you retry with the v0.7.1-arm image?

I agree that this issue might be better served in the [flannel repository](https://github.com/coreos/flannel).

**Comment by wadee** [comment]
yeah, I agree with u. 
I will try the latest v0.7.1-arm image and I will create the same issue to the flannel repository.
so I decide to close the issue.
thx to all guys!
