### ISSUE TITLE
kube-dns doesn't support using service name in stubDomains as docs and code seem to suggest

### ISSUE THREAD

**Issue by bdimcheff** [kubernetes/dns#82]
According to the [announcement](http://blog.kubernetes.io/2017/04/configuring-private-dns-zones-upstream-nameservers-kubernetes.html) blog post, I should be able to use a service as an upstream for stubDomains (note the note):

```
stubDomains (optional)

    Format: a JSON map using a DNS suffix key (e.g.; “acme.local”) and a value consisting of a JSON array of DNS IPs.
    Note: The target nameserver may itself be a Kubernetes service. For instance, you can run your own copy of dnsmasq to export custom DNS names into the ClusterDNS namespace.
```

However if I try to point at our unbound service, the dnsmasq container crashes:

```
I0505 21:26:49.795586       1 main.go:76] opts: {{/usr/sbin/dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053] true} /etc/k8s/dns/dnsmasq-nanny 10000000000}
I0505 21:26:49.795988       1 sync.go:167] Updated stubDomains to map[example.com:[unbound]]
I0505 21:26:49.796066       1 nanny.go:86] Starting dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053 --server /example.com/unbound]
I0505 21:26:49.797178       1 nanny.go:111]
W0505 21:26:49.797301       1 nanny.go:112] Got EOF from stdout
F0505 21:26:49.797341       1 nanny.go:182] dnsmasq exited: exit status 1
I0505 21:26:49.797283       1 nanny.go:115]
E0505 21:26:49.797501       1 nanny.go:116] Error reading from stderr: read |0: bad file descriptor
```

[This test](https://github.com/kubernetes/dns/blob/1.14.1/pkg/dns/config/config_test.go#L32) also seems to indicate that names are allowed in stubDomains, but from what I can tell, dnsmasq doesn't allow a name in a `--server` parameter (in the above example, it's sending `--server /example.com/unbound`)

We can currently use the clusterIP of a service as upstream DNS, but that seems pretty error prone.  Is there something else we should be doing here, or am I misinterpreting the documentation?

**Comment by cmluciano** [comment]
@kubernetes/dns-maintainers @kubernetes/sig-network-misc

**Comment by vongohren** [comment]
Any activity on this?

**Comment by bowei** [comment]
Can you try using the service VIP instead of the DNS name?

**Comment by vongohren** [comment]
@bowei How do I get the VIP? Or is it the 10.51.250.165 in the following describe?
That IP also works, but it's difficult to create a template based on this though.
Any suggestions?

``` kubectl --namespace kube-system describe svc/internal-dns
Name:			internal-dns
Namespace:		kube-system
Labels:			<none>
Annotations:		kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"internal-dns","namespace":"kube-system"},"spec":{"ports":[{"port":54,"targetPo...
Selector:		app=internal-dns
Type:			ClusterIP
IP:			10.51.250.165
Port:			<unset>	54/TCP
Endpoints:		10.48.2.7:54
Session Affinity:	None
Events:			<none>``

**Comment by bowei** [comment]
@vongohren what is your setup? The ClusterIP should be reachable from the kube-dns pod.

You can ask for a specific cluster IP by setting it explicitly in the spec.

**Comment by vongohren** [comment]
This is my setup, am i missing something?
Im still new to kubernetes so still learning.
Ah so I cant set a clusterIP in the service spec? How? 
Meaning its easier to template 👍 

```
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: internal-dns
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: internal-dns
    spec:
      containers:
      - name: appname
        image: repository:imagetag
        ports:
        - containerPort: 54
---
apiVersion: v1
kind: Service
metadata:
  name: internal-dns
  namespace: kube-system
spec:
  selector:
    app: internal-dns
  ports:
  - port: 54
    targetPort: 54
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"domaintopickup":["10.51.250.165"]}

```

**Comment by bowei** [comment]
Take a look at the kube-dns YAML itself. It uses a statically allocated cluster IP.

**Comment by vongohren** [comment]
Ok thanks, but so two problems.
I cant find a IP range that let's me allocate an IP

```
"10.0.171.239": provided IP is not in the valid range
"192.168.1.100": provided IP is not in the valid range
```

The second part is that when I left out the IP and used the autogenerated VIP and put that in my dns config-map. That did not work either.

Currently im testing so that kube-dns, my internal-dns is in namespace kube-system.
It is rigged up with domain cool.com -> the VIP that I found.
Then when I ping test.cool.com, from a simple busybox in the default namespace, I get a bad addrees.

I have confirmed this on a different cluster where I used the POD IP directly.

But one thing is that this new cluster runs two kube DNS pods, so I cant even target the pod directly.

Any suggestions whats going on?

**Comment by bdimcheff** [comment]
The ClusterIP definitely works for us (that's what we're doing now as a workaround).  It just doesn't seem stable enough, certainly not across cluster rebuilds.  Pointing to a service name seems valuable, I'm just not sure if it's a the intended behavior or not.  Tests seem to indicate yes, but it definitely won't work the way it is now.

We could probably do a host lookup somewhere and then pass the IP to dnsmasq, which would work as long as kube-dns is restarted after the service changes.  I'm sure someone else has a better idea for listening changes via the api.  Open to suggestions, and happy to take a crack at it.

**Comment by bowei** [comment]
@vongohren : you have to pick an IP from the service CIDR range that you selected for your cluster.

@bdimcheff : we could add the functionality to resolve the name directly from the API server into dnsmasq-nanny, it should be a small patch, perfect for a first-time contributor if I don't get to it quickly enough...

**Comment by jaredallard** [comment]
Any chance of this being implemented?

**Comment by chrisohaver** [comment]
I dont think CoreDNS has this issue - though I have not tested it specifically.

CoreDNS does CNAME lookups by feeding name to itself, meaning that it should have no problem resolving a CNAME target that is a service name (as long as it's fully qualified).

**Comment by andy2046** [comment]
@bowei hi BoWei, the functionality to resolve the name should be added inside [here](https://github.com/kubernetes/dns/blob/master/pkg/dnsmasq/nanny.go#L73)? if yes I would like to add this small patch as my first-time contribution
