### ISSUE TITLE
kubedns panic "fatal error: concurrent map writes"

### ISSUE THREAD

**Issue by SleepyBrett** [kubernetes/dns#88]
See linked issue for stacktraces:
https://github.com/kubernetes/kubernetes/issues/45593

For my case my cluster is very quiet, it's just a test cluster with no other users, my kubedns is a bit overscaled atm, however over two days I'm seeing several crashing (I've maybe applied half a dozen services a few times)

```
kube-dns-1251125892-0172d                                       3/3       Running   4          2d
kube-dns-1251125892-bmbm7                                       3/3       Running   1          2d
kube-dns-1251125892-ns3qg                                       3/3       Running   4          2d
kube-dns-1251125892-xrm3p                                       3/3       Running   7          2d
```

**Comment by bowei** [comment]
This should be fixed by  https://github.com/kubernetes/dns/pull/79
