### ISSUE TITLE
Are these peaks normal ?

### ISSUE THREAD

**Issue by alok87** [kubernetes/dns#91]
We are seeing in newrelic high response time for kube-dns under transactions. Its around 4-5 seconds for lookup.

Please see below graph
How to debug and fix these kube dns issues. We are running around 8-10 pods of kube-dns with replication controller.

@bowei  Added details below - 
We are running kubernetes 1.4.5 in aws cloud. Kubernetes was installed using `kube-up.sh` in our production. That time we did not have expertise on using kops private cluster. It uses aws routing as networking. Issue happens only when the rpm is high and when we switch traffic to our newly deployed pods(its a blue green deployment)

<img width="1255" alt="screen shot 2017-05-20 at 10 10 37 am" src="https://cloud.githubusercontent.com/assets/9006763/26273162/bb9c7524-3d47-11e7-909f-8172723122ef.png">
<img width="1258" alt="screen shot 2017-05-20 at 10 11 01 am" src="https://cloud.githubusercontent.com/assets/9006763/26273164/bbb28daa-3d47-11e7-9dbb-1964f0cb7a9e.png">
<img width="1236" alt="screen shot 2017-05-20 at 10 11 14 am" src="https://cloud.githubusercontent.com/assets/9006763/26273163/bba692ac-3d47-11e7-832f-82b5b96f70b2.png">

**Comment by bowei** [comment]
Can you post your setup? Cloud or bare-metal environment, OS, how Kubernetes was installed, which networking solution was used.

**Comment by alok87** [comment]
@bowei added details

**Comment by bowei** [comment]
what is the version on kube-dns

**Comment by alok87** [comment]
@bowei `gcr.io/google_containers/kubedns-amd64:1.8` image: gcr.io/google_containers/kube-dnsmasq-amd64:1.4``image: gcr.io/google_containers/exechealthz-amd64:1.2`

**Comment by bowei** [comment]
Is it possible for you to upgrade to newer version? We did some tuning and performance improvements to the kube-dns system since that release.

**Comment by alok87** [comment]
@bowei Upgrading solved this issue thanks 👍
