### ISSUE TITLE
Publish metrics of cached entries

### ISSUE THREAD

**Issue by zihaoyu** [kubernetes/dns#94]
It would be helpful if we can get dnsmasq cached entries number from its metrics endpoint. 

If this metric is already published, I apologize and please let me know the name of it. 

Thank you.

**Comment by bowei** [comment]
dnsmasq cache is limited to 10k entries total. Would the number of evictions be more useful? What are you trying to determine?

from `k8s.io/dns/pkg/dnsmasq/mterics.go:`

```
const ( 
        // CacheHits from dnsmasq.
        CacheHits MetricName = "hits"
        // CacheMisses from dnsmasq
        CacheMisses MetricName = "misses"
        // CacheEvictions from dnsmasq
        CacheEvictions MetricName = "evictions"
        // CacheInsertions from dnsmasq
        CacheInsertions MetricName = "insertions"
        // CacheSize from dnsmasq
        CacheSize MetricName = "cachesize"
)
```

**Comment by zihaoyu** [comment]
I see. That works too. Thank you. 

I was wanting to see how many entries are cached so I can adjust the cache size flag accordingly. Is there any reason I don't want to set cache to max size?

**Comment by bowei** [comment]
10k entries takes 10 Mb. Unless you are extremely resource constrained, I would set it to max.

**Comment by zihaoyu** [comment]
Thanks. Noted.

**Comment by zihaoyu** [comment]
@bowei So I'm seeing zero evictions and constant insertions. Does that mean the entries are being overwritten all the time? From the graph below, it looks like I'm using about 200 to 250 cache entries. Is that correct? Thanks.

![cache](https://cloud.githubusercontent.com/assets/464299/26381592/e1415a0c-3ff3-11e7-8b96-78a0b8e4de96.png)
